// Copyright 2026 The Simlin Authors. All rights reserved.
// Use of this source code is governed by the Apache License,
// Version 2.0, that can be found in the LICENSE file.

describe('CSS module stub for Node.js', () => {
  it('should return empty string for any property access', () => {
    // This tests the behavior of the CSS module stubs generated by build:css-stubs
    // The stubs use: module.exports = new Proxy({}, { get: () => '' });
    const stub: Record<string, string> = new Proxy({}, { get: () => '' });

    expect(stub.canvas).toBe('');
    expect(stub.anyPropertyName).toBe('');
    expect(stub.simlinCanvas).toBe('');
    expect(stub.nonExistentClass).toBe('');
  });

  it('should work correctly in template literals', () => {
    const stub: Record<string, string> = new Proxy({}, { get: () => '' });

    // When used in template literals, empty string should not produce "undefined"
    const className = `${stub.canvas} simlin-canvas`;
    expect(className).toBe(' simlin-canvas');
    expect(className).not.toContain('undefined');
  });

  it('should work correctly with string concatenation', () => {
    const stub: Record<string, string> = new Proxy({}, { get: () => '' });

    const className = stub.module + ' simlin-module';
    expect(className).toBe(' simlin-module');
    expect(className).not.toContain('undefined');
  });

  it('should be safe to use with clsx-style operations', () => {
    const stub: Record<string, string> = new Proxy({}, { get: () => '' });

    // clsx filters falsy values, empty string is falsy
    const classes = [stub.canvas, 'simlin-canvas'].filter(Boolean);
    expect(classes).toEqual(['simlin-canvas']);
  });
});
