initial nonrenewable resources = 2E12
desired food ratio = 5
desired persistent pollution index = 1E-12
desired resource use rate = 1E-12
technology development delay = 2
air pollution policy implementation time = 1995
land life policy implementation time = 1995
crowding multiplier from industry table (
  (0,.05),(200,.05),(400,0),(1600,0))
industrial capital output ratio multiplier from resource table (
  (0,3),(1,3))
industrial capital output ratio multiplier from pollution table (
 (0,1),(1,1))
persistent pollution technology change mult table (
  (-1,-.05),(0,0))
resource technology change mult table (
 (-1,-.05),(0,0))
land yield technology change rate multiplier table (
  (0,0),(1,.05))
urban and industrial land required per capita table (
 (0,.005),(200,.008),(400,.015),(600,.018),
 (800,.019),(1000,.02),(1600,.02))
industrial capital output ratio multiplier table (
 (1,1),(2,1))
