// Copyright 2026 The Simlin Authors. All rights reserved.
// Use of this source code is governed by the Apache License,
// Version 2.0, that can be found in the LICENSE file.

//! Diagnostics must be a function of the model, not of hash-map iteration
//! order (GH #999).
//!
//! Two runs of the same binary over the corpus produced diagnostic sets
//! differing by ~184 lines -- all UNIT warnings, differing in which variable
//! was named and how many rows appeared. The mechanism: unit-inference
//! constraints were generated by iterating `ModelStage1::variables` (a
//! `HashMap`), so the CONSTRAINT ORDER varied per map instance; the conflict
//! reporter (`find_constraint_mismatches`) keeps the FIRST constraint of each
//! signature group as the comparison anchor, so a different order names a
//! different variable (and can change the pair count). Same class as GH #595
//! (init runlist) and GH #633 (layout): an unordered collection reaching an
//! observable.
//!
//! The tests build the same model on independent fresh databases repeatedly
//! (each fresh `HashMap` draws new hash keys, so ~half of two-entry maps
//! iterate in the other order -- the `fragment_determinism_tests` recipe) and
//! assert the FORMATTED diagnostic sets are byte-identical.

use crate::db::{SimlinDb, collect_all_diagnostics, sync_from_datamodel_incremental};
use crate::test_common::TestProject;

/// A three-way unit conflict on one shared metavariable: `b` carries no
/// units, and three consumers pin it to widgets, gadgets, and meters. Which
/// pair of constraints gets reported -- and which variable is named first --
/// depended on generation order.
fn conflicting_units_fixture() -> TestProject {
    TestProject::new("unit_conflict")
        .with_sim_time(0.0, 4.0, 1.0)
        .aux("b", "7", None)
        .aux("ua", "b", Some("widgets"))
        .aux("uc", "b", Some("gadgets"))
        .aux("ud", "b", Some("meters"))
        .aux("ue", "b", Some("liters"))
}

/// The same model, built on 16 independent fresh databases, must produce the
/// SAME diagnostics -- same rows, same order, same named variables.
#[test]
fn unit_diagnostics_are_reproducible_across_runs() {
    let datamodel = conflicting_units_fixture().build_datamodel();

    let mut first: Option<Vec<String>> = None;
    for run in 0..16 {
        let mut db = SimlinDb::default();
        let sync = sync_from_datamodel_incremental(&mut db, &datamodel, None);
        let rendered: Vec<String> = collect_all_diagnostics(&db, sync.project)
            .iter()
            .map(|d| format!("{:?} [{:?}] {:?}", d.variable, d.severity, d.error))
            .collect();
        assert!(
            !rendered.is_empty(),
            "the fixture must produce unit diagnostics for the test to constrain anything"
        );
        match &first {
            None => first = Some(rendered),
            Some(expected) => assert_eq!(
                expected, &rendered,
                "run {run} produced a different diagnostic set than run 0"
            ),
        }
    }
}

/// The other three order-reaching observables found while fixing GH #999,
/// exercised together: a mixed-units ARRAYED variable (element order decided
/// both the solver's binding for the array's metavariable and the
/// consistency pass's anchor element -- content AND count varied), plus a
/// second model (the models map's order reordered per-model diagnostic
/// blocks).
#[test]
fn arrayed_and_multi_model_diagnostics_are_reproducible() {
    use crate::testutils::{x_aux, x_model, x_module_named};

    let mut first: Option<Vec<String>> = None;
    for run in 0..16 {
        let sub = x_model(
            "sub",
            vec![
                x_aux("inner_a", "1", Some("widgets")),
                x_aux("inner_b", "inner_a", Some("gadgets")),
            ],
        );
        let main = x_model(
            "main",
            vec![
                x_aux("plain", "3", None),
                crate::datamodel::Variable::Aux(crate::datamodel::Aux {
                    ident: "mixed".to_string(),
                    equation: crate::datamodel::Equation::Arrayed(
                        vec!["D".to_string()],
                        vec![
                            ("d1".to_string(), "3 {widgets}".to_string(), None, None),
                            ("d2".to_string(), "plain".to_string(), None, None),
                            ("d3".to_string(), "4 {gadgets}".to_string(), None, None),
                        ],
                        None,
                        false,
                    ),
                    documentation: String::new(),
                    units: Some("widgets".to_string()),
                    gf: None,
                    ai_state: None,
                    uid: None,
                    compat: crate::datamodel::Compat::default(),
                }),
                x_module_named("m", "sub", &[], None),
            ],
        );
        let mut datamodel = crate::testutils::x_project(
            crate::datamodel::SimSpecs {
                start: 0.0,
                stop: 4.0,
                dt: crate::datamodel::Dt::Dt(1.0),
                save_step: None,
                sim_method: crate::datamodel::SimMethod::Euler,
                time_units: Some("month".to_string()),
            },
            &[main, sub],
        );
        datamodel.dimensions = vec![crate::datamodel::Dimension::named(
            "D".to_string(),
            vec!["d1".to_string(), "d2".to_string(), "d3".to_string()],
        )];

        let mut db = SimlinDb::default();
        let sync = sync_from_datamodel_incremental(&mut db, &datamodel, None);
        let rendered: Vec<String> = collect_all_diagnostics(&db, sync.project)
            .iter()
            .map(|d| {
                format!(
                    "{}: {:?} [{:?}] {:?}",
                    d.model, d.variable, d.severity, d.error
                )
            })
            .collect();
        match &first {
            None => first = Some(rendered),
            Some(expected) => assert_eq!(
                expected, &rendered,
                "run {run} produced a different diagnostic set than run 0"
            ),
        }
    }
}
