// Copyright 2026 The Simlin Authors. All rights reserved.
// Use of this source code is governed by the Apache License,
// Version 2.0, that can be found in the LICENSE file.

//! The per-model body layout query (`compute_layout`): the salsa-tracked,
//! role-independent slot assignment for explicit variables, implicit
//! (SMOOTH/DELAY/TREND) helpers, and -- when LTM is enabled -- the LTM
//! synthetic variables and their implicit helpers. Offsets start at 0; the
//! root module's `IMPLICIT_VAR_COUNT` shift is applied later at assembly via
//! `VariableLayout::root_shifted`.

use std::collections::HashMap;

use super::*;

#[salsa::tracked(returns(ref))]
pub fn compute_layout(
    db: &dyn Db,
    model: SourceModel,
    project: SourceProject,
) -> crate::compiler::symbolic::VariableLayout {
    use crate::compiler::symbolic::{LayoutEntry, VariableLayout};

    let source_vars = model.variables(db);
    let var_names = model.variable_names(db);

    let mut sorted_names: Vec<&String> = var_names.iter().collect();
    sorted_names.sort_unstable();

    // This is the role-independent *body* layout: offsets always start at
    // 0. The root (main) module's +IMPLICIT_VAR_COUNT shift for the implicit
    // globals (time/dt/initial_time/final_time) is applied later, at
    // assembly, via `VariableLayout::root_shifted`. Keeping this query body-
    // only makes a submodel's layout byte-identical whether it is reached as
    // the root or as a submodule, so the diagnostic pass and assembly share
    // one salsa cache entry per submodule variable.
    let mut entries = HashMap::new();
    let mut offset = 0;

    let project_models = project.models(db);

    for name in &sorted_names {
        let size = if let Some(svar) = source_vars.get(name.as_str()) {
            if svar.kind(db) == SourceVariableKind::Module {
                // Module variables occupy the sub-model's total n_slots
                let sub_model_name = canonicalize(svar.model_name(db));
                if let Some(sub_model) = project_models.get(sub_model_name.as_ref()) {
                    let sub_layout = compute_layout(db, *sub_model, project);
                    sub_layout.n_slots
                } else {
                    1
                }
            } else {
                variable_size(db, *svar, project)
            }
        } else {
            1
        };

        entries.insert(name.to_string(), LayoutEntry { offset, size });
        offset += size;
    }

    // Include implicit variables (generated by SMOOTH, DELAY, TREND builtins)
    // after all explicit variables.
    let implicit_info = model_implicit_var_info(db, model, project);
    let mut implicit_names: Vec<&String> = implicit_info.keys().collect();
    implicit_names.sort_unstable();
    for name in implicit_names {
        let info = &implicit_info[name];
        let size = if info.is_module {
            if let Some(sub_model_name) = &info.model_name {
                let sub_canonical = canonicalize(sub_model_name);
                project_models
                    .get(sub_canonical.as_ref())
                    .map(|sm| compute_layout(db, *sm, project).n_slots)
                    .unwrap_or(info.size)
            } else {
                info.size
            }
        } else {
            info.size
        };
        entries.insert(name.clone(), LayoutEntry { offset, size });
        offset += size;
    }

    // Section 3: LTM synthetic variables (only when ltm_enabled).
    // Scalar LTM vars occupy 1 slot; A2A LTM vars occupy
    // product(dim_lengths) slots, computed from the variable's
    // `dimensions` field. When ltm_enabled is false, this section is
    // skipped entirely (zero overhead). Models without feedback loops
    // (e.g. passthrough modules) get an empty LTM var list from
    // model_ltm_variables (also zero overhead).
    //
    // No salsa dependency cycle: model_ltm_variables calls only analysis
    // functions (model_causal_edges, model_loop_circuits) that don't
    // depend on compute_layout.
    if project.ltm_enabled(db) {
        let ltm_vars = model_ltm_variables(db, model, project);
        let dim_context = project_dimensions_context(db, project);

        let mut sorted_ltm_vars: Vec<&LtmSyntheticVar> = ltm_vars.vars.iter().collect();
        sorted_ltm_vars.sort_unstable_by_key(|v| &v.name);

        for ltm_var in sorted_ltm_vars {
            let size = if ltm_var.dimensions.is_empty() {
                1
            } else {
                ltm_var
                    .dimensions
                    .iter()
                    .map(|dim_name| {
                        let canonical = crate::common::CanonicalDimensionName::from_raw(dim_name);
                        dim_context.get(&canonical).map(|d| d.len()).unwrap_or(1)
                    })
                    .product()
            };
            entries.insert(ltm_var.name.clone(), LayoutEntry { offset, size });
            offset += size;
        }

        // Section 3b: Implicit variables generated by LTM equation
        // parsing. Helper auxes and any expanded module vars need their
        // own slots in the parent model's layout.
        let ltm_implicit = model_ltm_implicit_var_info(db, model, project);
        let mut ltm_im_names: Vec<&String> = ltm_implicit.keys().collect();
        ltm_im_names.sort_unstable();
        for name in ltm_im_names {
            let meta = &ltm_implicit[name];
            entries.insert(
                name.clone(),
                LayoutEntry {
                    offset,
                    size: meta.size,
                },
            );
            offset += meta.size;
        }
    }

    VariableLayout::new(entries, offset)
}
