// Copyright 2026 The Simlin Authors. All rights reserved.
// Use of this source code is governed by the Apache License,
// Version 2.0, that can be found in the LICENSE file.

//! Slot order, stated once.
//!
//! `compute_layout` is the per-model body layout query: the salsa-tracked,
//! role-independent slot assignment for explicit variables, implicit
//! (SMOOTH/DELAY/TREND) helpers, and -- when LTM is enabled -- the LTM
//! synthetic variables and their implicit helpers. Offsets start at 0; the
//! root module's `IMPLICIT_VAR_COUNT` shift is applied at assembly via
//! `VariableLayout::root_shifted`. `flattened_offsets` is that layout read
//! back out as the results-offset map, so the slot a name reads is the slot
//! `resolve_module` addressed its fragment against.

use std::collections::HashMap;

use super::*;
use crate::common::{Canonical, Ident};

#[salsa::tracked(returns(ref))]
pub fn compute_layout(
    db: &dyn Db,
    model: SourceModel,
    project: SourceProject,
) -> crate::compiler::symbolic::VariableLayout {
    use crate::compiler::symbolic::{LayoutEntry, VariableLayout};

    let source_vars = model.variables(db);
    let var_names = model.variable_names(db);

    let mut sorted_names: Vec<&String> = var_names.iter().collect();
    sorted_names.sort_unstable();

    // This is the role-independent *body* layout: offsets always start at
    // 0. The root (main) module's +IMPLICIT_VAR_COUNT shift for the implicit
    // globals (time/dt/initial_time/final_time) is applied later, at
    // assembly, via `VariableLayout::root_shifted`. Keeping this query body-
    // only makes a submodel's layout byte-identical whether it is reached as
    // the root or as a submodule, so the diagnostic pass and assembly share
    // one salsa cache entry per submodule variable.
    let mut entries = HashMap::new();
    let mut offset = 0;

    let project_models = project.models(db);

    for name in &sorted_names {
        let size = if let Some(svar) = source_vars.get(name.as_str()) {
            if svar.kind(db) == SourceVariableKind::Module {
                // Module variables occupy the sub-model's total n_slots
                let sub_model_name = canonicalize(svar.model_name(db));
                if let Some(sub_model) = project_models.get(sub_model_name.as_ref()) {
                    let sub_layout = compute_layout(db, *sub_model, project);
                    sub_layout.n_slots
                } else {
                    1
                }
            } else {
                variable_size(db, *svar, project)
            }
        } else {
            1
        };

        entries.insert(name.to_string(), LayoutEntry { offset, size });
        offset += size;
    }

    // Include implicit variables (generated by SMOOTH, DELAY, TREND builtins)
    // after all explicit variables.
    let implicit_info = model_implicit_var_info(db, model, project);
    let mut implicit_names: Vec<&String> = implicit_info.keys().collect();
    implicit_names.sort_unstable();
    for name in implicit_names {
        let info = &implicit_info[name];
        let size = if info.is_module {
            if let Some(sub_model_name) = &info.model_name {
                let sub_canonical = canonicalize(sub_model_name);
                project_models
                    .get(sub_canonical.as_ref())
                    .map(|sm| compute_layout(db, *sm, project).n_slots)
                    .unwrap_or(info.size)
            } else {
                info.size
            }
        } else {
            info.size
        };
        entries.insert(name.clone(), LayoutEntry { offset, size });
        offset += size;
    }

    // Section 3: LTM synthetic variables (only when ltm_enabled).
    // Scalar LTM vars occupy 1 slot; A2A LTM vars occupy
    // product(dim_lengths) slots, computed from the variable's
    // `dimensions` field. When ltm_enabled is false, this section is
    // skipped entirely (zero overhead). Models without feedback loops
    // (e.g. passthrough modules) get an empty LTM var list from
    // model_ltm_variables (also zero overhead).
    //
    // No salsa dependency cycle: model_ltm_variables calls only analysis
    // functions (model_causal_edges, model_loop_circuits) that don't
    // depend on compute_layout.
    if project.ltm_enabled(db) {
        let ltm_vars = model_ltm_variables(db, model, project);
        let dim_context = project_dimensions_context(db, project);

        let mut sorted_ltm_vars: Vec<&LtmSyntheticVar> = ltm_vars.vars.iter().collect();
        sorted_ltm_vars.sort_unstable_by_key(|v| &v.name);

        for ltm_var in sorted_ltm_vars {
            let size = if ltm_var.dimensions.is_empty() {
                1
            } else {
                ltm_var
                    .dimensions
                    .iter()
                    .map(|dim_name| {
                        let canonical = crate::common::CanonicalDimensionName::from_raw(dim_name);
                        dim_context.get(&canonical).map(|d| d.len()).unwrap_or(1)
                    })
                    .product()
            };
            entries.insert(ltm_var.name.clone(), LayoutEntry { offset, size });
            offset += size;
        }

        // Section 3b: Implicit variables generated by LTM equation
        // parsing. Helper auxes and any expanded module vars need their
        // own slots in the parent model's layout.
        let ltm_implicit = model_ltm_implicit_var_info(db, model, project);
        let mut ltm_im_names: Vec<&String> = ltm_implicit.keys().collect();
        ltm_im_names.sort_unstable();
        for name in ltm_im_names {
            let meta = &ltm_implicit[name];
            entries.insert(
                name.clone(),
                LayoutEntry {
                    offset,
                    size: meta.size,
                },
            );
            offset += meta.size;
        }
    }

    VariableLayout::new(entries, offset)
}

/// The results-offset map: every saved series' canonical name mapped to its
/// absolute slot in the root module's data buffer. This is
/// `CompiledSimulation::offsets`, and through it `Results::offsets` -- what the
/// VM's `get_series`, libsimlin's variable list, the CLI's TSV columns and the
/// LTM result readers resolve a name with.
///
/// It is the root's `compute_layout`, root-shifted, flattened through every
/// module instance: a top-level variable is keyed by its canonical name at its
/// layout slot; a module variable contributes no key of its own but its
/// sub-model's map, each name prefixed `module·` and each slot based at the
/// module's; an arrayed explicit variable is keyed per element as
/// `name[e1,e2]` in the VM's row-major storage order (the conveyor and queue
/// plans index belts by these keys); an arrayed implicit or LTM variable is
/// keyed once, by its bare name, at its base slot (readers widen it by the
/// variable's own dimensions); and a standalone lookup-only table keeps its
/// layout slot but has no key, because it produces no series (GH #606).
pub(crate) fn flattened_offsets(
    db: &dyn Db,
    project: SourceProject,
    root: SourceModel,
) -> HashMap<Ident<Canonical>, usize> {
    let mut offsets = HashMap::new();
    let layout = compute_layout(db, root, project).root_shifted();
    flatten_model(db, project, root, &layout, 0, None, &mut offsets);
    offsets
}

/// How one layout entry reaches the results map.
enum Flatten<'a> {
    /// A module instance: its sub-model's map, based at this slot. `None`
    /// when the project holds no such model -- there is nothing to flatten.
    Module(Option<SourceModel>),
    /// A static table (GH #606): the slot is reserved, there is no series.
    Table,
    /// An arrayed explicit variable: one key per element, row-major.
    Elements(&'a [crate::dimensions::Dimension]),
    /// One key at the entry's base slot.
    Series,
}

/// Insert one model's layout into `offsets`: every entry at `base +
/// entry.offset`, keyed under `prefix·name`. A module variable recurses into
/// its sub-model's body layout with the module's slot as the new base.
fn flatten_model(
    db: &dyn Db,
    project: SourceProject,
    model: SourceModel,
    layout: &crate::compiler::symbolic::VariableLayout,
    base: usize,
    prefix: Option<&Ident<Canonical>>,
    offsets: &mut HashMap<Ident<Canonical>, usize>,
) {
    let project_models = project.models(db);
    let source_vars = model.variables(db);
    let implicit_info = model_implicit_var_info(db, model, project);
    let ltm_implicit = model_ltm_implicit_var_info(db, model, project);
    let sub_model = |name: &str| project_models.get(canonicalize(name).as_ref()).copied();
    let qualified = |local: Ident<Canonical>| match prefix {
        Some(prefix) => Ident::join(&prefix.as_canonical_str(), &local.as_canonical_str()),
        None => local,
    };

    for (name, entry) in layout.iter() {
        let slot = base + entry.offset;
        let kind = if let Some(svar) = source_vars.get(name) {
            if svar.kind(db) == SourceVariableKind::Module {
                Flatten::Module(sub_model(svar.model_name(db)))
            } else if source_var_is_table_only(db, *svar) {
                Flatten::Table
            } else if entry.size > 1 {
                // The entry's size is the product of these dimensions.
                Flatten::Elements(variable_dimensions(db, *svar, project))
            } else {
                Flatten::Series
            }
        } else if let Some(info) = implicit_info.get(name)
            && info.is_module
        {
            Flatten::Module(info.model_name.as_deref().and_then(sub_model))
        } else if let Some(meta) = ltm_implicit.get(name)
            && meta.is_module
        {
            Flatten::Module(meta.model_name.as_deref().and_then(sub_model))
        } else {
            // A scalar or arrayed implicit helper, an LTM synthetic variable,
            // or one of the root's implicit globals.
            Flatten::Series
        };
        match kind {
            Flatten::Module(Some(sub)) => {
                let sub_layout = compute_layout(db, sub, project);
                let module_ident = qualified(Ident::<Canonical>::new(name));
                flatten_model(
                    db,
                    project,
                    sub,
                    sub_layout,
                    slot,
                    Some(&module_ident),
                    offsets,
                );
            }
            Flatten::Module(None) | Flatten::Table => {}
            Flatten::Elements(dims) => {
                for (j, subscripts) in crate::dimensions::SubscriptIterator::new(dims).enumerate() {
                    let element = format!("{name}[{}]", subscripts.join(","));
                    offsets.insert(
                        qualified(Ident::<Canonical>::from_unchecked(element)),
                        slot + j,
                    );
                }
            }
            Flatten::Series => {
                offsets.insert(qualified(Ident::<Canonical>::new(name)), slot);
            }
        }
    }
}

/// The shape of `model` as a module INSTANCE: every variable's slot inside the
/// block (`compute_layout`) together with its dimensions and kind, nested
/// module variables carrying their own model's shape -- what a parent
/// fragment resolves a cross-module read `m·x` (or `m·n·x`) through, and what
/// its reference-extent table is projected from.
///
/// Keyed per model, like `compute_layout`, because that is the value's
/// granularity: a cross-module read depends on the whole sub-model's layout
/// (inserting a variable ahead of `x` moves `x`'s slot), so a fragment that
/// resolves one genuinely depends on this whole value, and the memo backdates
/// when the sub-model's shape is unchanged. The `Arc` is what the fragment
/// constructors clone into `DepKind::Module`, so a shape is derived once per
/// revision and shared by every fragment that reads the sub-model.
///
/// When LTM is enabled the sub-model is itself LTM-augmented: its layout
/// carries the synthetic LTM variables, most importantly the per-input-port
/// composite score `$⁚ltm⁚composite⁚{port}`, which a parent equation
/// references across the module boundary (the exhaustive-mode input->macro
/// link score is the composite-reference form
/// `"{module}·$⁚ltm⁚composite⁚{port}"`, GH #548). Those variables and the
/// LTM implicit helpers are registered at their layout slots so the
/// cross-module reference resolves the same way the flattened-offset assembly
/// does; without them the parent fragment fails to compile, `assemble_module`
/// drops it, and the link score reads a constant 0 -- silently zeroing every
/// loop that runs through the macro.
#[salsa::tracked(returns(ref))]
pub(crate) fn model_shape(
    db: &dyn Db,
    model: SourceModel,
    project: SourceProject,
) -> std::sync::Arc<crate::compiler::fragment::ModelShape> {
    use crate::compiler::fragment::{DepShape, ModelShape, ShapeEntry};

    let layout = compute_layout(db, model, project);
    let source_vars = model.variables(db);
    let mut vars: crate::common::IdentMap<Ident<Canonical>, ShapeEntry> = Default::default();

    for (name, svar) in source_vars.iter() {
        let Some(entry) = layout.get(name.as_str()) else {
            continue;
        };
        let shape = if svar.kind(db) == SourceVariableKind::Module {
            module_dep_shape(db, project, svar.model_name(db))
        } else {
            DepShape::var(variable_dimensions(db, *svar, project).clone())
        };
        vars.insert(
            Ident::new(name.as_str()),
            ShapeEntry {
                offset: entry.offset,
                shape,
            },
        );
    }

    if project.ltm_enabled(db) {
        let dim_context = project_dimensions_context(db, project);
        for ltm_var in &model_ltm_variables(db, model, project).vars {
            let Some(entry) = layout.get(&ltm_var.name) else {
                continue;
            };
            // A2A link/loop scores carry dimensions, so a subscripted
            // cross-module read resolves an element offset rather than
            // collapsing to slot 0.
            let dims = ltm_var
                .dimensions
                .iter()
                .filter_map(|name| {
                    dim_context
                        .get(&crate::common::CanonicalDimensionName::from_raw(name))
                        .cloned()
                })
                .collect();
            vars.entry(Ident::new(&ltm_var.name)).or_insert(ShapeEntry {
                offset: entry.offset,
                shape: DepShape::var(dims),
            });
        }
        for (im_name, meta) in model_ltm_implicit_var_info(db, model, project).iter() {
            let Some(entry) = layout.get(im_name) else {
                continue;
            };
            let shape = if meta.is_module {
                module_dep_shape(db, project, meta.model_name.as_deref().unwrap_or(""))
            } else {
                let dim_names = match meta.variable.get_equation() {
                    Some(
                        datamodel::Equation::ApplyToAll(dim_names, _)
                        | datamodel::Equation::Arrayed(dim_names, _, _, _),
                    ) => dim_names.as_slice(),
                    _ => &[],
                };
                DepShape::var(
                    dim_names
                        .iter()
                        .filter_map(|name| {
                            dim_context
                                .get(&crate::common::CanonicalDimensionName::from_raw(name))
                                .cloned()
                        })
                        .collect(),
                )
            };
            vars.entry(Ident::new(im_name)).or_insert(ShapeEntry {
                offset: entry.offset,
                shape,
            });
        }
    }

    std::sync::Arc::new(ModelShape {
        vars,
        n_slots: layout.n_slots,
    })
}

/// The shape of an instance of the model named `model_name`: a
/// `DepKind::Module` over that model's [`model_shape`], or over an empty
/// shape when the project has no such model (the reference then fails to
/// resolve, `DoesNotExist`, exactly as a reference into a missing sub-model
/// must).
pub(crate) fn module_dep_shape(
    db: &dyn Db,
    project: SourceProject,
    model_name: &str,
) -> crate::compiler::fragment::DepShape {
    use crate::compiler::fragment::{DepShape, ModelShape};

    let sub_canonical = canonicalize(model_name);
    let shape = match project.models(db).get(sub_canonical.as_ref()) {
        Some(sub_model) => model_shape(db, *sub_model, project).clone(),
        None => std::sync::Arc::new(ModelShape::default()),
    };
    DepShape::module(shape)
}
