// Copyright 2026 The Simlin Authors. All rights reserved.
// Use of this source code is governed by the Apache License,
// Version 2.0, that can be found in the LICENSE file.

//! Demand-driven read queries over the salsa inputs: per-variable parsing
//! (`parse_source_variable_with_module_context` and its `_impl`), the
//! project-global cached contexts (`project_units_context`,
//! `project_datamodel_dims`, `project_dimensions_context`,
//! `project_converted_dimensions`), the module-ident context
//! (`module_ident_context_for_model`/`model_module_ident_context`), the
//! per-variable direct-dependency extraction
//! (`variable_direct_dependencies` and its `_impl`, plus the
//! `canonical_module_input_set` helper and the `VariableDeps` value), the
//! implicit-variable metadata (`ImplicitVarMeta`/`model_implicit_var_info`),
//! the recursive module map (`model_module_map`), and the dimension-read
//! queries (`variable_relevant_dimensions`/`variable_dimensions`/
//! `variable_size`).

use std::collections::{BTreeSet, HashMap, HashSet};

use super::*;
use crate::common::{Canonical, Ident};

/// Result of parsing a single variable, including any implicit variables
/// generated by builtin expansion (e.g., DELAY1, SMTH create internal stocks).
#[derive(Clone, PartialEq, salsa::Update)]
pub struct ParsedVariableResult {
    pub variable: crate::model::VariableStage0,
    pub implicit_vars: Vec<datamodel::Variable>,
}

impl std::fmt::Debug for ParsedVariableResult {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ParsedVariableResult")
            .field("ident", &self.variable.ident())
            .field("implicit_vars_count", &self.implicit_vars.len())
            .finish()
    }
}

/// Cached units context -- computed once per project, reused across all variables.
/// Subsumes the per-variable Context::new_with_builtins calls.
///
/// Reads the datamodel `Vec<Unit>` and `SimSpecs` directly off the salsa input
/// (the inputs now store the datamodel types, so no per-call conversion is
/// needed).
///
/// Unit definition parsing errors are accumulated as diagnostics so they
/// appear in `collect_all_diagnostics`.
#[salsa::tracked(returns(ref))]
pub fn project_units_context(db: &dyn Db, project: SourceProject) -> crate::units::Context {
    use salsa::Accumulator;
    let dm_units = project.units(db);
    let dm_sim_specs = project.sim_specs(db);
    // Construction is partial: keep the context built from the valid unit
    // declarations and surface each conflicting/duplicate declaration as a
    // project-level diagnostic, rather than discarding every unit definition on
    // the first conflict. An empty context would lose all alias normalization
    // project-wide (yr/year, person/people, model-defined equivalences) and
    // re-create a spurious unit-mismatch flood -- the context-layer parallel of
    // the inference partial-results fix (GH #614).
    let (ctx, unit_parse_errors) = crate::units::Context::new_with_builtins(dm_units, dm_sim_specs);
    for (unit_name, eq_errors) in &unit_parse_errors {
        for eq_err in eq_errors {
            CompilationDiagnostic(Diagnostic {
                model: String::new(),
                variable: Some(unit_name.clone()),
                error: DiagnosticError::Unit(crate::common::UnitError::DefinitionError(
                    eq_err.clone(),
                    None,
                )),
                severity: DiagnosticSeverity::Error,
            })
            .accumulate(db);
        }
    }
    ctx
}

/// Cached datamodel dimensions -- computed once per project.
///
/// The dimensions input now stores `Vec<datamodel::Dimension>` directly, so
/// this is a clone of the input field. It is retained as a tracked function
/// so downstream queries (`project_dimensions_context`, `parse_source_variable`)
/// keep their existing `returns(ref)` dependency edge on it.
#[salsa::tracked(returns(ref))]
pub fn project_datamodel_dims(db: &dyn Db, project: SourceProject) -> Vec<datamodel::Dimension> {
    project.dimensions(db).clone()
}

/// Cached project-global dimension context -- computed once per project.
///
/// This is the project's immutable `DimensionsContext`, the same value the
/// per-variable compile sites used to rebuild on every variable via
/// `DimensionsContext::from(project_datamodel_dims(..))`. Building it
/// canonicalizes every dimension element name, so doing it once per project
/// (instead of once per explicit-and-implicit variable compilation) removes a
/// dominant allocation cost on large models. Keyed only on `project` -- and
/// reading `project_datamodel_dims`, which depends solely on the project's
/// dimensions input -- so it recomputes exactly when the dimensions change, the
/// SAME dependency granularity the inline rebuild took. The shared context's
/// only interior mutability is its `relationship_cache` `Mutex`, so it is safe
/// to share across the rayon-parallel variable compilations (and the
/// subdimension-relationship memo is now computed once and reused rather than
/// discarded per variable).
#[salsa::tracked(returns(ref))]
pub fn project_dimensions_context(
    db: &dyn Db,
    project: SourceProject,
) -> crate::dimensions::DimensionsContext {
    crate::dimensions::DimensionsContext::from(project_datamodel_dims(db, project).as_slice())
}

/// Cached project-global converted dimensions -- computed once per project.
///
/// The `Vec<crate::dimensions::Dimension>` form of `project_datamodel_dims`,
/// previously rebuilt per variable via
/// `project_datamodel_dims(..).iter().map(Dimension::from).collect()`. Each
/// `Dimension::from` re-canonicalizes the dimension's element names, so caching
/// it once per project removes that repeated work. Same input dependency
/// (`project_datamodel_dims`) and hence same invalidation granularity as the
/// inline rebuild. The interned-backed `Dimension`s clone cheaply, so a
/// consumer that genuinely needs an owned `Vec` can still `.to_vec()` the slice.
#[salsa::tracked(returns(ref))]
pub fn project_converted_dimensions(
    db: &dyn Db,
    project: SourceProject,
) -> Vec<crate::dimensions::Dimension> {
    project_datamodel_dims(db, project)
        .iter()
        .map(crate::dimensions::Dimension::from)
        .collect()
}

fn parse_source_variable_impl(
    db: &dyn Db,
    var: SourceVariable,
    project: SourceProject,
    module_idents: Option<&HashSet<Ident<Canonical>>>,
    macro_registry: Option<&crate::module_functions::MacroRegistry>,
) -> ParsedVariableResult {
    let relevant_dim_names = variable_relevant_dimensions(db, var);
    let dims: Vec<datamodel::Dimension> = if relevant_dim_names.is_empty() {
        // Scalar variable: no dim dependency, so dim changes don't invalidate.
        vec![]
    } else {
        let all_source_dims = project.dimensions(db);
        let expanded = expand_maps_to_chains(relevant_dim_names, all_source_dims);
        project_datamodel_dims(db, project)
            .iter()
            .filter(|d| expanded.contains(&d.name))
            .cloned()
            .collect()
    };
    let units_ctx = project_units_context(db, project);
    let dm_var = datamodel_variable_from_source(db, var);
    let mut implicit_vars = Vec::new();
    let variable = crate::variable::parse_var_with_module_context(
        &dims,
        &dm_var,
        &mut implicit_vars,
        units_ctx,
        |mi| Ok(Some(mi.clone())),
        module_idents,
        // No model-var-names set: the per-variable parse must not depend on
        // the model's full name set, or any variable add/remove/rename would
        // invalidate every cached parse (dimension-granularity incrementality).
        // Bare element subscripts in user equations therefore keep the
        // conservative helper-aux path; the LTM parse path (whose equations
        // are regenerated wholesale anyway) passes the set instead.
        None,
        macro_registry,
        crate::db::macro_registry::enclosing_macro_for_var(db, project, var), // #554
    );

    ParsedVariableResult {
        variable,
        implicit_vars,
    }
}

#[salsa::tracked(returns(ref))]
pub fn parse_source_variable_with_module_context<'db>(
    db: &'db dyn Db,
    var: SourceVariable,
    project: SourceProject,
    module_ident_context: ModuleIdentContext<'db>,
) -> ParsedVariableResult {
    let module_idents: HashSet<Ident<Canonical>> = module_ident_context
        .idents(db)
        .iter()
        .map(|ident| Ident::new(ident.as_str()))
        .collect();
    // Reaches the BuiltinVisitor so a macro call expands (salsa-cached).
    let macro_registry = &crate::db::macro_registry::project_macro_registry(db, project).registry;
    parse_source_variable_impl(db, var, project, Some(&module_idents), Some(macro_registry))
}

fn module_ident_context_for_model<'db>(
    db: &'db dyn Db,
    model: SourceModel,
    project: SourceProject,
    extra_module_idents: &[String],
) -> ModuleIdentContext<'db> {
    let source_vars = model.variables(db);
    let dm_vars: Vec<datamodel::Variable> = source_vars
        .values()
        .map(|source_var| datamodel_variable_from_source(db, *source_var))
        .collect();
    // Pre-classification must recognize macro calls as module calls too
    // (so `PREVIOUS(y)` rewrites correctly when `y = MYMACRO(...)`), the
    // same way it already recognizes `y = SMTH1(...)`.
    let macro_registry = &crate::db::macro_registry::project_macro_registry(db, project).registry;
    let mut module_ident_list: Vec<String> =
        crate::model::collect_module_idents(&dm_vars, macro_registry)
            .into_iter()
            .map(|ident| ident.as_str().to_owned())
            .collect();
    module_ident_list.extend(
        extra_module_idents
            .iter()
            .map(|ident| canonicalize(ident).into_owned()),
    );
    module_ident_list.sort();
    module_ident_list.dedup();
    ModuleIdentContext::new(db, module_ident_list)
}

#[salsa::tracked]
pub fn model_module_ident_context<'db>(
    db: &'db dyn Db,
    model: SourceModel,
    project: SourceProject,
    extra_module_idents: Vec<String>,
) -> ModuleIdentContext<'db> {
    module_ident_context_for_model(db, model, project, &extra_module_idents)
}

#[derive(Clone, Debug, PartialEq, Eq, salsa::Update)]
pub struct VariableDeps {
    /// Dependencies used during normal dt timestep calculations.
    pub dt_deps: BTreeSet<String>,
    /// Dependencies used during initial value calculations.
    pub initial_deps: BTreeSet<String>,
    /// Dependencies for implicit variables generated by builtin expansion
    /// (e.g., SMOOTH, DELAY create internal stocks).
    pub implicit_vars: Vec<ImplicitVarDeps>,
    /// Variables referenced by BuiltinFn::Init in this variable's equation.
    /// These must be included in the Initials runlist so their values are
    /// captured in the initial_values snapshot.
    pub init_referenced_vars: BTreeSet<String>,
    /// Variables referenced only through INIT(...) in dt AST (pruned only for dt ordering).
    pub dt_init_only_referenced_vars: BTreeSet<String>,
    /// Variables referenced *only* through PREVIOUS(...) in the normal dt AST.
    pub dt_previous_referenced_vars: BTreeSet<String>,
    /// Variables referenced *only* through PREVIOUS(...) in the initial AST.
    pub initial_previous_referenced_vars: BTreeSet<String>,
    /// Standalone lookup tables referenced via `LOOKUP(table, x)`. These are
    /// layout references (codegen needs the table's offset for its reverse-map)
    /// but NOT data-flow dependencies, so they are kept out of `dt_deps` /
    /// `initial_deps` (no runlist-ordering or causal/LTM edge) and reunited with
    /// the dep set only by the fragment compiler's metadata/tables build (#606).
    pub referenced_tables: BTreeSet<String>,
}

pub(crate) fn canonical_module_input_set(
    module_input_names: &[String],
) -> BTreeSet<Ident<Canonical>> {
    module_input_names
        .iter()
        .map(|name| Ident::new(canonicalize(name).as_ref()))
        .collect()
}

fn variable_direct_dependencies_impl(
    db: &dyn Db,
    var: SourceVariable,
    project: SourceProject,
    module_inputs: Option<&BTreeSet<Ident<Canonical>>>,
    module_ident_context: ModuleIdentContext,
) -> VariableDeps {
    match var.kind(db) {
        SourceVariableKind::Module => {
            let refs: BTreeSet<String> = var
                .module_refs(db)
                .iter()
                .map(|mr| canonicalize(&mr.src).into_owned())
                .collect();
            VariableDeps {
                dt_deps: refs.clone(),
                initial_deps: refs,
                implicit_vars: Vec::new(),
                init_referenced_vars: BTreeSet::new(),
                dt_init_only_referenced_vars: BTreeSet::new(),
                dt_previous_referenced_vars: BTreeSet::new(),
                initial_previous_referenced_vars: BTreeSet::new(),
                // A module never references a lookup table via LOOKUP(...).
                referenced_tables: BTreeSet::new(),
            }
        }
        _ => {
            let parsed =
                parse_source_variable_with_module_context(db, var, project, module_ident_context);
            // The datamodel-form dims are still needed for the implicit-var
            // parse below; the canonicalized context + converted dims come from
            // the project-global salsa-cached queries (no per-variable rebuild).
            let dims = project_datamodel_dims(db, project);
            let dim_context = project_dimensions_context(db, project);
            let converted_dims = project_converted_dimensions(db, project);
            let models = HashMap::new();
            let scope = crate::model::ScopeStage0 {
                models: &models,
                dimensions: dim_context,
                model_name: "",
            };
            let lowered = crate::model::lower_variable(&scope, &parsed.variable);

            // Two calls to classify_dependencies replace 7 separate walker calls.
            let dt_classification = match lowered.ast() {
                Some(ast) => {
                    crate::variable::classify_dependencies(ast, converted_dims, module_inputs)
                }
                None => crate::variable::DepClassification::default(),
            };
            let init_classification = match lowered.init_ast() {
                Some(ast) => {
                    crate::variable::classify_dependencies(ast, converted_dims, module_inputs)
                }
                None => crate::variable::DepClassification::default(),
            };

            let implicit_vars =
                extract_implicit_var_deps(parsed, dims, dim_context, converted_dims, module_inputs);

            VariableDeps {
                dt_deps: dt_classification
                    .all
                    .into_iter()
                    .map(|id| id.to_string())
                    .collect(),
                initial_deps: init_classification
                    .all
                    .into_iter()
                    .map(|id| id.to_string())
                    .collect(),
                implicit_vars,
                init_referenced_vars: dt_classification.init_referenced,
                dt_init_only_referenced_vars: dt_classification.init_only,
                dt_previous_referenced_vars: dt_classification.previous_only,
                initial_previous_referenced_vars: init_classification.previous_only,
                referenced_tables: dt_classification
                    .referenced_tables
                    .into_iter()
                    .chain(init_classification.referenced_tables)
                    .collect(),
            }
        }
    }
}

/// Per-variable direct dependency extraction.
///
/// `module_ident_context` is the caller's module-ident set (the empty
/// `ModuleIdentContext` for callers whose model is unknown), and
/// `module_inputs` is the module instance's input wiring (the empty
/// `ModuleInputSet` for the no-inputs case).
///
/// This collapses what were four separately-keyed tracked variants
/// (`variable_direct_dependencies`, `_with_inputs`, `_with_context`,
/// `_with_context_and_inputs`) into one. The empty `ModuleInputSet` is treated
/// IDENTICALLY to the old `None`-inputs path: `classify_dependencies`
/// special-cases an `isModuleInput(...)` conditional only when given
/// `Some(inputs)` (then walks the matching branch), so `None` and
/// `Some(empty_set)` are NOT equivalent there -- `None` walks all three
/// branches. The old no-inputs variants passed `None`, and the only live
/// inputs caller (`build_var_info`) passed `Some(..)` exclusively for a
/// non-empty set. Mapping the empty `ModuleInputSet` to `None` therefore
/// preserves the old behavior exactly.
#[salsa::tracked(returns(ref))]
pub fn variable_direct_dependencies<'db>(
    db: &'db dyn Db,
    var: SourceVariable,
    project: SourceProject,
    module_ident_context: ModuleIdentContext<'db>,
    module_inputs: ModuleInputSet<'db>,
) -> VariableDeps {
    let canonical_inputs = module_inputs.canonical_input_set(db);
    // An empty input set is the old `None` path (no `isModuleInput` branch
    // selection); a non-empty set is the old `Some(&set)` path.
    let module_inputs_opt = if canonical_inputs.is_empty() {
        None
    } else {
        Some(&canonical_inputs)
    };
    variable_direct_dependencies_impl(db, var, project, module_inputs_opt, module_ident_context)
}

/// Metadata for a single implicit variable generated by builtin expansion.
#[derive(Clone, PartialEq, Eq, salsa::Update)]
pub struct ImplicitVarMeta {
    pub parent_source_var: SourceVariable,
    pub index_in_parent: usize,
    pub is_stock: bool,
    pub is_module: bool,
    pub model_name: Option<String>,
    pub size: usize,
}

impl std::fmt::Debug for ImplicitVarMeta {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ImplicitVarMeta")
            .field("index_in_parent", &self.index_in_parent)
            .field("is_stock", &self.is_stock)
            .field("size", &self.size)
            .finish()
    }
}

/// Collect metadata about all implicit variables in a model.
/// The returned map is keyed by the canonical implicit variable name.
#[salsa::tracked(returns(ref))]
pub fn model_implicit_var_info(
    db: &dyn Db,
    model: SourceModel,
    project: SourceProject,
) -> HashMap<String, ImplicitVarMeta> {
    let source_vars = model.variables(db);
    let module_ident_context = model_module_ident_context(db, model, project, vec![]);
    let mut result = HashMap::new();

    for source_var in source_vars.values() {
        let parsed = parse_source_variable_with_module_context(
            db,
            *source_var,
            project,
            module_ident_context,
        );
        for (index, implicit_var) in parsed.implicit_vars.iter().enumerate() {
            let name = canonicalize(implicit_var.get_ident()).into_owned();
            let is_stock = matches!(implicit_var, datamodel::Variable::Stock(_));
            let is_module = matches!(implicit_var, datamodel::Variable::Module(_));
            let model_name = match implicit_var {
                datamodel::Variable::Module(m) => Some(m.model_name.clone()),
                _ => None,
            };
            result.insert(
                name,
                ImplicitVarMeta {
                    parent_source_var: *source_var,
                    index_in_parent: index,
                    is_stock,
                    is_module,
                    model_name,
                    size: 1,
                },
            );
        }
    }

    result
}

#[salsa::tracked(returns(ref))]
pub fn model_module_map(
    db: &dyn Db,
    model: SourceModel,
    project: SourceProject,
) -> HashMap<Ident<Canonical>, HashMap<Ident<Canonical>, Ident<Canonical>>> {
    let source_vars = model.variables(db);
    let project_models = project.models(db);
    let model_name_ident: Ident<Canonical> = Ident::new(model.name(db));

    let mut all_models: HashMap<Ident<Canonical>, HashMap<Ident<Canonical>, Ident<Canonical>>> =
        HashMap::new();
    let mut current_mapping: HashMap<Ident<Canonical>, Ident<Canonical>> = HashMap::new();

    let mut sorted_names: Vec<&String> = source_vars.keys().collect();
    sorted_names.sort_unstable();

    for name in sorted_names {
        let svar = &source_vars[name];
        if svar.kind(db) == SourceVariableKind::Module {
            let sub_model_name_str = svar.model_name(db);
            let sub_model_ident: Ident<Canonical> = Ident::new(sub_model_name_str);
            let var_ident: Ident<Canonical> = Ident::new(name);
            current_mapping.insert(var_ident, sub_model_ident.clone());

            let sub_canonical = canonicalize(sub_model_name_str);
            if let Some(sub_model) = project_models.get(sub_canonical.as_ref()) {
                let sub_map = model_module_map(db, *sub_model, project);
                all_models.extend(sub_map.iter().map(|(k, v)| (k.clone(), v.clone())));
            }
        }
    }

    let implicit_vars = model_implicit_var_info(db, model, project);
    for (name, meta) in implicit_vars.iter() {
        if meta.is_module
            && let Some(sub_model_name) = &meta.model_name
        {
            let sub_model_ident: Ident<Canonical> = Ident::new(sub_model_name);
            let var_ident: Ident<Canonical> = Ident::new(name);
            current_mapping.insert(var_ident, sub_model_ident.clone());

            let sub_canonical = canonicalize(sub_model_name);
            if let Some(sub_model) = project_models.get(sub_canonical.as_ref()) {
                let sub_map = model_module_map(db, *sub_model, project);
                all_models.extend(sub_map.iter().map(|(k, v)| (k.clone(), v.clone())));
            }
        }
    }

    all_models.insert(model_name_ident, current_mapping);
    all_models
}

/// Extracts the set of dimension names referenced in a variable's equation.
///
/// Reads only `var.equation(db)` -- never the project-level dimension list.
/// This means scalar variables produce an empty set without establishing a
/// dependency on `project.dimensions`, so dimension changes cannot
/// invalidate them. For arrayed variables the returned names come from the
/// equation definition, not from the project dimension list.
#[salsa::tracked(returns(ref))]
pub fn variable_relevant_dimensions(db: &dyn Db, var: SourceVariable) -> BTreeSet<String> {
    match var.equation(db) {
        datamodel::Equation::Scalar(_) => BTreeSet::new(),
        datamodel::Equation::ApplyToAll(dim_names, _) => dim_names.iter().cloned().collect(),
        datamodel::Equation::Arrayed(dim_names, _, _, _) => dim_names.iter().cloned().collect(),
    }
}

#[salsa::tracked(returns(ref))]
pub fn variable_dimensions(
    db: &dyn Db,
    var: SourceVariable,
    project: SourceProject,
) -> Vec<crate::dimensions::Dimension> {
    // Module context doesn't affect dimension extraction, so an empty
    // context is correct here.
    let empty_context = ModuleIdentContext::new(db, vec![]);
    let parsed = parse_source_variable_with_module_context(db, var, project, empty_context);
    match parsed.variable.get_dimensions() {
        Some(dims) => dims.to_vec(),
        None => Vec::new(),
    }
}

#[salsa::tracked]
pub fn variable_size(db: &dyn Db, var: SourceVariable, project: SourceProject) -> usize {
    let dims = variable_dimensions(db, var, project);
    if dims.is_empty() {
        1
    } else {
        dims.iter().map(|d| d.len()).product()
    }
}
