// Copyright 2026 The Simlin Authors. All rights reserved.
// Use of this source code is governed by the Apache License,
// Version 2.0, that can be found in the LICENSE file.

//! Demand-driven read queries over the salsa inputs: per-variable parsing
//! (`parse_source_variable`), the project-global cached contexts
//! (`project_units_context_result` and its `project_units_context`
//! projection, `project_datamodel_dims`, `project_dimensions_context`,
//! `project_converted_dimensions`), the per-variable direct-dependency
//! extraction (`variable_direct_dependencies`: the `DepRef` relation, its
//! `DepTarget` resolver and the `VariableDeps` value), the
//! implicit-variable metadata (`ImplicitVarMeta`/`model_implicit_var_info`),
//! the dimension-read queries (`variable_relevant_dimensions`/
//! `variable_dimensions`/`variable_size`), and the project's explicit
//! module-instance graph (`project_module_graph`).

use std::collections::{BTreeMap, BTreeSet, HashMap};

use super::*;
use crate::builtins_visitor::SnapshotIndexFacts;
use crate::capture::{CaptureKind, ImplicitVar};
use crate::common::{Canonical, Ident};
use crate::variable::DepLag;

/// Result of parsing a single variable, including any implicit variables
/// generated by builtin expansion (e.g., DELAY1, SMTH create internal stocks).
#[derive(Clone, PartialEq)]
pub struct ParsedVariableResult {
    pub variable: crate::model::ParsedVariable,
    pub implicit_vars: Vec<ImplicitVar>,
}

impl std::fmt::Debug for ParsedVariableResult {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ParsedVariableResult")
            .field("ident", &self.variable.ident())
            .field("implicit_vars_count", &self.implicit_vars.len())
            .finish()
    }
}

/// The project's units context together with the definition errors that
/// building it produced.
///
/// The errors ride the RESULT rather than a salsa accumulator because a bad
/// unit declaration is a PROJECT-level fact -- there is one `units` list per
/// project, belonging to no model. Accumulating it from inside this query's
/// body meant `collect_all_diagnostics` reported one copy per model (every
/// model's diagnostic subtree reaches this query), and that after an unrelated
/// salsa revision bump the accumulator DFS pruned the subtree and the errors
/// vanished from the collection entirely. `collect_all_diagnostics` now reads
/// this field and emits each error once. See `db::macro_registry` for the
/// sibling case and `db/diagnostic_tests.rs` for the regression tests.
#[derive(Clone, PartialEq)]
pub struct UnitsContextResult {
    pub ctx: crate::units::Context,
    /// One entry per unit declaration that failed to parse: its name and the
    /// equation errors it produced.
    pub definition_errors: Vec<(String, Vec<crate::common::EquationError>)>,
}

/// Cached units context -- computed once per project, reused across all variables.
/// Subsumes the per-variable Context::new_with_builtins calls.
///
/// Reads the datamodel `Vec<Unit>` and `SimSpecs` directly off the salsa input
/// (the inputs now store the datamodel types, so no per-call conversion is
/// needed).
#[salsa::tracked(returns(ref))]
pub fn project_units_context_result(db: &dyn Db, project: SourceProject) -> UnitsContextResult {
    let dm_units = project.units(db);
    let dm_sim_specs = project.sim_specs(db);
    // Construction is partial: keep the context built from the valid unit
    // declarations and report each conflicting/duplicate declaration, rather
    // than discarding every unit definition on the first conflict. An empty
    // context would lose all alias normalization project-wide (yr/year,
    // person/people, model-defined equivalences) and re-create a spurious
    // unit-mismatch flood -- the context-layer parallel of the inference
    // partial-results fix (GH #614).
    let (ctx, definition_errors) = crate::units::Context::new_with_builtins(dm_units, dm_sim_specs);
    UnitsContextResult {
        ctx,
        definition_errors,
    }
}

/// The project's units context, for the many callers that want the context and
/// not the definition errors that came with it.
///
/// This is a salsa PROJECTION over [`project_units_context_result`], not a plain
/// accessor, and the distinction is load-bearing. A caller that reads a plain
/// accessor takes a dependency on the whole `UnitsContextResult`, so it is
/// invalidated whenever EITHER half changes -- and the two halves move
/// independently: a unit whose equation fails to parse is left out of `ctx`
/// entirely, so editing a malformed unit equation (every intermediate state of
/// typing one) changes `definition_errors` while `ctx` stays byte-identical.
/// Every variable parse in the project would rebuild on each keystroke.
///
/// As a tracked query it re-executes when the result changes but salsa BACKDATES
/// it when the projected `Context` compares equal, so its readers keep exactly
/// the dependency they had when the errors rode the salsa accumulator instead.
/// Pinned by `db::dimension_invalidation_tests::
/// unit_definition_error_only_change_does_not_invalidate_context_readers`.
///
/// **What the projection costs.** `Context::new_with_builtins` still runs
/// exactly once, in the query above -- the cost is memory, not CPU. Salsa now
/// RETAINS two `units::Context` copies per project: the one inside
/// `UnitsContextResult` and the one in this query's memo. Each also costs a
/// clone in every revision where the units input changes. A `Context` is the
/// project's unit name/alias/equation maps, so this is small next to the model
/// memos of a large model and flat in the model count -- but it
/// is per project and permanent, so a future field on `Context` is paid twice.
#[salsa::tracked(returns(ref))]
pub fn project_units_context(db: &dyn Db, project: SourceProject) -> crate::units::Context {
    project_units_context_result(db, project).ctx.clone()
}

/// Cached datamodel dimensions -- computed once per project.
///
/// The dimensions input now stores `Vec<datamodel::Dimension>` directly, so
/// this is a clone of the input field. It is retained as a tracked function
/// so downstream queries (`project_dimensions_context`, `parse_source_variable`)
/// keep their existing `returns(ref)` dependency edge on it.
#[salsa::tracked(returns(ref))]
pub fn project_datamodel_dims(db: &dyn Db, project: SourceProject) -> Vec<datamodel::Dimension> {
    project.dimensions(db).clone()
}

/// Cached project-global dimension context -- computed once per project.
///
/// This is the project's immutable `DimensionsContext`. Building one
/// (`DimensionsContext::from(project_datamodel_dims(..))`) canonicalizes every
/// dimension element name, so it is built once per project rather than once
/// per explicit-and-implicit variable compilation, which would be a dominant
/// allocation cost on large models. Keyed only on `project` -- and reading
/// `project_datamodel_dims`, which depends solely on the project's dimensions
/// input -- so it recomputes exactly when the dimensions change. The shared context's
/// only interior mutability is its `relationship_cache` `Mutex`, which is what
/// makes the memo `Sync` and therefore shareable at all: one context serves
/// every variable's compilation instead of one being rebuilt per variable, and
/// the subdimension-relationship memo is computed once and reused rather than
/// discarded per variable. Those compilations are sequential today; the `Mutex`
/// is what keeps the sharing sound rather than evidence that they are not.
#[salsa::tracked(returns(ref))]
pub fn project_dimensions_context(
    db: &dyn Db,
    project: SourceProject,
) -> crate::dimensions::DimensionsContext {
    crate::dimensions::DimensionsContext::from(project_datamodel_dims(db, project).as_slice())
}

/// Whether the project declares the element a qualified `dimension·element`
/// spelling names -- the one fact a parse needs about a qualified
/// `PREVIOUS`/`INIT` subscript index (`builtins_visitor::SnapshotIndexFacts`).
///
/// A per-name projection of [`project_dimensions_context`]: the parse narrows
/// its own dimension context to the dimensions the variable declares, and a
/// qualified index may name any dimension in the project. Reading the whole
/// context would put every dimension edit on every such parse's dependency
/// list; this query re-executes on those edits but backdates on an unchanged
/// answer, so the parse re-runs only when the element it spells appears or
/// disappears (`db::dimension_invalidation_tests`).
#[salsa::tracked(returns(clone))]
pub(crate) fn project_has_qualified_element(
    db: &dyn Db,
    project: SourceProject,
    qualified: String,
) -> bool {
    project_dimensions_context(db, project)
        .lookup(&qualified)
        .is_some()
}

/// Cached project-global converted dimensions -- computed once per project.
///
/// The `Vec<crate::dimensions::Dimension>` form of `project_datamodel_dims`,
/// previously rebuilt per variable via
/// `project_datamodel_dims(..).iter().map(Dimension::from).collect()`. Each
/// `Dimension::from` re-canonicalizes the dimension's element names, so caching
/// it once per project removes that repeated work. Same input dependency
/// (`project_datamodel_dims`) and hence same invalidation granularity as the
/// inline rebuild. The interned-backed `Dimension`s clone cheaply, so a
/// consumer that genuinely needs an owned `Vec` can still `.to_vec()` the slice.
#[salsa::tracked(returns(ref))]
pub fn project_converted_dimensions(
    db: &dyn Db,
    project: SourceProject,
) -> Vec<crate::dimensions::Dimension> {
    project_datamodel_dims(db, project)
        .iter()
        .map(crate::dimensions::Dimension::from)
        .collect()
}

/// Parse one source variable.
///
/// Keyed on the variable and the project alone: the parse reads the
/// variable's own fields, the dimensions it names, the project's units context
/// and macro registry, and its owning model through [`variable_owner_model`]
/// -- for which macro, if any, it is the body of, and for the one question a
/// `PREVIOUS`/`INIT` subscript asks of the model, whether an identifier index
/// pins a declared element of the variable it subscripts
/// (`builtins_visitor::SnapshotIndexFacts::Axes`). That question goes through
/// the per-name projections `model_variable_by_name` and
/// [`variable_dimensions`], never the model's variable set, so no edit to a
/// sibling variable re-keys or re-executes it
/// (`db::fragment_char_tests::module_helper_add_reparses_only_the_added_variable`);
/// what the argument's NAME denotes is resolved at lowering from the
/// dependency's shape (`compiler::context::Context::snapshot_storage`). One
/// memo per variable serves the compile, diagnostic, analysis, LTM and layout
/// paths alike.
#[salsa::tracked(returns(ref))]
pub fn parse_source_variable(
    db: &dyn Db,
    var: SourceVariable,
    project: SourceProject,
) -> ParsedVariableResult {
    let relevant_dim_names = variable_relevant_dimensions(db, var);
    let dims: Vec<datamodel::Dimension> = if relevant_dim_names.is_empty() {
        // Scalar variable: no dim dependency, so dim changes don't invalidate.
        vec![]
    } else {
        let all_source_dims = project.dimensions(db);
        let expanded = expand_maps_to_chains(relevant_dim_names, all_source_dims);
        project_datamodel_dims(db, project)
            .iter()
            .filter(|d| expanded.contains(&d.name))
            .cloned()
            .collect()
    };
    // Built from the NARROWED `dims`, not from the project-wide
    // `project_dimensions_context`: this parse's dimension dependency is
    // deliberately only the dimensions the variable references, so that an
    // unrelated dimension edit does not invalidate every cached parse
    // (`db::dimension_invalidation_tests`). A scalar variable's `dims` is
    // empty, so this is free in the common case.
    let dim_ctx = crate::dimensions::DimensionsContext::from(&dims);
    let units_ctx = project_units_context(db, project);
    // Reaches the BuiltinVisitor so a macro call expands (salsa-cached).
    let macro_registry = &crate::db::macro_registry::project_macro_registry(db, project).registry;
    let owner = variable_owner_model(db, project, var);
    let axis_of = |base: &str, axis: usize| -> Option<crate::dimensions::Dimension> {
        let base = model_variable_by_name(db, owner?, canonicalize(base).into_owned())?;
        variable_dimensions(db, base, project).get(axis).cloned()
    };
    let is_qualified_element = |qualified: &str| -> bool {
        project_has_qualified_element(db, project, canonicalize(qualified).into_owned())
    };
    let ctx = crate::variable::ParseContext {
        dimensions: &dim_ctx,
        units_ctx,
        snapshot_index: SnapshotIndexFacts::Axes {
            axis_of: &axis_of,
            is_qualified_element: &is_qualified_element,
        },
        macro_registry: Some(macro_registry),
        enclosing_model: crate::db::macro_registry::enclosing_macro_for_var(db, project, var), // #554
    };
    let mut implicit_vars = Vec::new();
    let variable =
        crate::variable::parse_var(&ctx, variable_source(db, var), &mut implicit_vars, |mi| {
            Ok(Some(mi.clone()))
        });

    ParsedVariableResult {
        variable,
        implicit_vars,
    }
}

/// The phase of the reader's equation an occurrence was read in: the per-step
/// (dt) equation, or the initial-value equation.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum DepPhase {
    Dt,
    Init,
}

/// What a read names, in the model being compiled: the module instances a
/// qualified read crosses (`m·n·x` crosses `m` then `n`; a local read crosses
/// none) and the variable at the end of the path.
///
/// Every hop is proven against the model's metadata by
/// [`DepScope::resolve`]: a `·` in a name is only a candidate separator, so a
/// spelling whose head is not a module instance is one local name, and the
/// compiler refuses it at lowering exactly as it refuses any name the model
/// does not declare.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct DepTarget {
    pub module_path: Vec<Ident<Canonical>>,
    pub variable: Ident<Canonical>,
    /// `variable` is a stock of the sub-model the path ends in. The dt phase
    /// reads a stock from the prior step, so such a read orders the reader
    /// after nothing (`db::dep_graph::build_var_info`). Always `false` for a
    /// local read: the graph reads a local node's kind from its own entry.
    pub stock_output: bool,
}

impl DepTarget {
    fn local(variable: Ident<Canonical>) -> Self {
        DepTarget {
            module_path: Vec::new(),
            variable,
            stock_output: false,
        }
    }

    pub fn is_local(&self) -> bool {
        self.module_path.is_empty()
    }

    /// The node of the reading model this read orders after and links from:
    /// the first instance of a qualified read, otherwise the variable.
    pub fn head(&self) -> &Ident<Canonical> {
        self.module_path.first().unwrap_or(&self.variable)
    }

    /// A qualified read's name inside its first instance -- `x` for `m·x`,
    /// `n·x` for `m·n·x` -- which is how LTM names a sub-model's output ports;
    /// `None` for a local read.
    pub(crate) fn output_port(&self) -> Option<Ident<Canonical>> {
        let (_, inner) = self.module_path.split_first()?;
        Some(
            inner
                .iter()
                .rev()
                .fold(self.variable.clone(), |port, instance| {
                    Ident::join(&instance.as_canonical_str(), &port.as_canonical_str())
                }),
        )
    }
}

/// One read of one dependency: what it names, in which phase, and how.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct DepRef {
    pub target: DepTarget,
    pub phase: DepPhase,
    pub lag: DepLag,
}

/// A variable's reads, with the projections every scheduling consumer asks
/// for; the one dependency representation an explicit variable and a
/// parse-synthesized helper share.
#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct DepRefs(BTreeSet<DepRef>);

impl DepRefs {
    pub fn iter(&self) -> impl Iterator<Item = &DepRef> {
        self.0.iter()
    }

    pub fn phase(&self, phase: DepPhase) -> impl Iterator<Item = &DepRef> {
        self.0.iter().filter(move |dep| dep.phase == phase)
    }

    /// The head of every target, each once, in name order.
    pub fn heads(&self) -> BTreeSet<&Ident<Canonical>> {
        self.0.iter().map(|dep| dep.target.head()).collect()
    }

    /// Whether some read, in either phase and under any lag, names the local
    /// variable `name` itself.
    pub fn reads_local(&self, name: &Ident<Canonical>) -> bool {
        self.0
            .iter()
            .any(|dep| dep.target.is_local() && dep.target.variable == *name)
    }

    /// The dt-phase targets read through `PREVIOUS` and never currently: the
    /// lagged edges, which carry state across a step. An `INIT` read of the
    /// same target is a frozen snapshot, not an instantaneous read, so it
    /// does not cancel the lag (`PREVIOUS(x, INIT(x))` lags `x`).
    pub fn dt_previous_only(&self) -> BTreeSet<&DepTarget> {
        let current: BTreeSet<&DepTarget> = self
            .phase(DepPhase::Dt)
            .filter(|dep| dep.lag == DepLag::Current)
            .map(|dep| &dep.target)
            .collect();
        self.phase(DepPhase::Dt)
            .filter(|dep| dep.lag == DepLag::Previous && !current.contains(&dep.target))
            .map(|dep| &dep.target)
            .collect()
    }
}

impl FromIterator<DepRef> for DepRefs {
    fn from_iter<I: IntoIterator<Item = DepRef>>(iter: I) -> Self {
        DepRefs(iter.into_iter().collect())
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct VariableDeps {
    /// Every read of the variable's two equations.
    pub deps: DepRefs,
    /// Dependencies for implicit variables generated by builtin expansion
    /// (e.g., SMOOTH, DELAY create internal stocks).
    pub implicit_vars: Vec<ImplicitVarDeps>,
    /// Standalone lookup tables referenced via `LOOKUP(table, x)`. These are
    /// layout references (codegen needs the table's offset for its reverse-map)
    /// but NOT data-flow dependencies, so they are kept out of `deps` (no
    /// runlist-ordering or causal/LTM edge) and reunited with the dependency
    /// set only by the fragment compiler's metadata/tables build (#606).
    pub referenced_tables: BTreeSet<Ident<Canonical>>,
}

pub(crate) fn canonical_module_input_set(
    module_input_names: &[String],
) -> BTreeSet<Ident<Canonical>> {
    module_input_names
        .iter()
        .map(|name| Ident::new(canonicalize(name).as_ref()))
        .collect()
}

/// What a read is resolved in: the model that owns the reader (its explicit
/// module instances and, through `model_implicit_var_by_name`, the instances
/// every parse in it synthesized), the parse's own helpers, and the project
/// the hops are followed through. `model` is `None` only for a variable no
/// model owns, which a synced project never produces; every read then
/// resolves as a local name.
pub(crate) struct DepScope<'a> {
    pub db: &'a dyn Db,
    pub model: Option<SourceModel>,
    pub project: SourceProject,
    pub own_helpers: &'a [ImplicitVar],
}

impl DepScope<'_> {
    /// The model a module instance named `head` instantiates, when `head` is
    /// one: an explicit `Module` variable of the model, an instance this parse
    /// synthesized, or one a sibling parse synthesized -- each through its
    /// per-name firewall.
    fn instance_target_model(&self, head: &str) -> Option<String> {
        let db = self.db;
        if let Some(var) = self
            .model
            .and_then(|model| model_variable_by_name(db, model, head.to_string()))
            && var.kind(db) == SourceVariableKind::Module
        {
            return Some(canonicalize(var.model_name(db)).into_owned());
        }
        if let Some(module) = self
            .own_helpers
            .iter()
            .find(|helper| canonicalize(helper.ident()) == head)
            .and_then(ImplicitVar::module)
        {
            return Some(canonicalize(&module.model_name).into_owned());
        }
        self.model
            .and_then(|model| model_implicit_var_by_name(db, model, self.project, head.to_string()))
            .filter(|meta| meta.is_module)
            .and_then(|meta| meta.model_name)
            .map(|name| canonicalize(&name).into_owned())
    }

    /// What one read names.
    ///
    /// A leading `·` is XMILE's parent-scope spelling (`.x`), which every
    /// consumer reads as the bare name. A `·` inside the name is a module hop
    /// only where the metadata says so: the head must be a module instance in
    /// scope ([`Self::instance_target_model`]) and every further segment but
    /// the last a `Module` variable of the model the previous hop instantiates;
    /// the last segment is the variable, whose kind in that model is the
    /// target's `stock_output`. A spelling that fails a hop is one local name
    /// (the leading `·`, if any, stripped), which the compiler refuses at
    /// lowering, and which is what a `dimension·element` spelling is when the
    /// dimension is not one the lowering folded.
    pub(crate) fn resolve(&self, ident: &Ident<Canonical>) -> DepTarget {
        let db = self.db;
        let spelling = ident.as_canonical_str();
        let spelling = spelling.strip_prefix("\u{00B7}").unwrap_or(spelling);
        let local = || DepTarget::local(Ident::from_str_unchecked(spelling.as_str()));
        let Some((head, mut rest)) = spelling.split_at_dot() else {
            return local();
        };
        let Some(mut model_name) = self.instance_target_model(head.as_str()) else {
            return local();
        };
        let mut module_path = vec![Ident::from_str_unchecked(head.as_str())];
        loop {
            let Some(sub_model) = project_model_by_name(db, self.project, model_name) else {
                return local();
            };
            let Some((segment, tail)) = rest.split_at_dot() else {
                let variable = Ident::from_str_unchecked(rest.as_str());
                let stock_output =
                    model_variable_by_name(db, sub_model, variable.as_str().to_string())
                        .is_some_and(|var| var.kind(db) == SourceVariableKind::Stock);
                return DepTarget {
                    module_path,
                    variable,
                    stock_output,
                };
            };
            let Some(nested) = model_variable_by_name(db, sub_model, segment.as_str().to_string())
                .filter(|var| var.kind(db) == SourceVariableKind::Module)
            else {
                return local();
            };
            model_name = canonicalize(nested.model_name(db)).into_owned();
            module_path.push(Ident::from_str_unchecked(segment.as_str()));
            rest = tail;
        }
    }

    /// A module instance's reads: each input source, in both phases,
    /// currently.
    pub(super) fn module_input_deps(
        &self,
        sources: impl Iterator<Item = Ident<Canonical>>,
    ) -> DepRefs {
        let targets: BTreeSet<DepTarget> = sources.map(|source| self.resolve(&source)).collect();
        [DepPhase::Dt, DepPhase::Init]
            .into_iter()
            .flat_map(|phase| {
                targets.iter().cloned().map(move |target| DepRef {
                    target,
                    phase,
                    lag: DepLag::Current,
                })
            })
            .collect()
    }

    /// The reads of one parsed variable's two equations, classified once each
    /// on the typed tier and resolved here: its dependencies and the tables it
    /// calls. `dim_context` and `converted_dims` are the project's dimensions
    /// in the two forms the lowering and the walk read.
    pub(super) fn parsed_variable_deps(
        &self,
        parsed: &crate::model::ParsedVariable,
        dim_context: &crate::dimensions::DimensionsContext,
        converted_dims: &[crate::dimensions::Dimension],
        module_inputs: Option<&BTreeSet<Ident<Canonical>>>,
    ) -> (DepRefs, BTreeSet<Ident<Canonical>>) {
        // Classified on `Expr1`: builtins resolved, no array bounds, which is
        // all the walk reads. A typed-tier failure (an unknown builtin, a bad
        // arity) is the variable's parse error, reported by its fragment.
        let classify = |ast: Option<&crate::ast::Ast<crate::ast::Expr0>>| {
            ast.and_then(|ast| crate::ast::typed_ast(ast, dim_context).ok())
                .map(|ast| {
                    crate::variable::classify_dependencies(&ast, converted_dims, module_inputs)
                })
                .unwrap_or_default()
        };
        let dt = classify(parsed.ast());
        let init = classify(parsed.init_ast());
        // The two equations are one for most variables, so each name is
        // resolved once.
        let mut targets: BTreeMap<&Ident<Canonical>, DepTarget> = BTreeMap::new();
        let mut deps = BTreeSet::new();
        for (phase, classification) in [(DepPhase::Dt, &dt), (DepPhase::Init, &init)] {
            for occurrence in &classification.occurrences {
                let target = targets
                    .entry(&occurrence.ident)
                    .or_insert_with(|| self.resolve(&occurrence.ident))
                    .clone();
                deps.insert(DepRef {
                    target,
                    phase,
                    lag: occurrence.lag,
                });
            }
        }
        let referenced_tables = dt
            .referenced_tables
            .into_iter()
            .chain(init.referenced_tables)
            .collect();
        (DepRefs(deps), referenced_tables)
    }
}

fn variable_direct_dependencies_impl(
    db: &dyn Db,
    var: SourceVariable,
    project: SourceProject,
    module_inputs: Option<&BTreeSet<Ident<Canonical>>>,
) -> VariableDeps {
    let owner = variable_owner_model(db, project, var);
    match var.kind(db) {
        SourceVariableKind::Module => VariableDeps {
            deps: DepScope {
                db,
                model: owner,
                project,
                own_helpers: &[],
            }
            .module_input_deps(var.module_refs(db).iter().map(|mr| Ident::new(&mr.src))),
            implicit_vars: Vec::new(),
            // A module never references a lookup table via LOOKUP(...).
            referenced_tables: BTreeSet::new(),
        },
        _ => {
            let parsed = parse_source_variable(db, var, project);
            let scope = DepScope {
                db,
                model: owner,
                project,
                own_helpers: &parsed.implicit_vars,
            };
            // The canonicalized context + converted dims come from the
            // project-global salsa-cached queries (no per-variable rebuild).
            let dim_context = project_dimensions_context(db, project);
            let converted_dims = project_converted_dimensions(db, project);
            let (deps, referenced_tables) = scope.parsed_variable_deps(
                &parsed.variable,
                dim_context,
                converted_dims,
                module_inputs,
            );
            let implicit_vars = extract_implicit_var_deps(
                &scope,
                parsed,
                dim_context,
                converted_dims,
                module_inputs,
            );
            VariableDeps {
                deps,
                implicit_vars,
                referenced_tables,
            }
        }
    }
}

/// Per-variable direct dependency extraction: every read of the variable's
/// two equations and of the helpers its parse synthesized, as [`DepRef`]s.
///
/// `classify_dependencies` walks the typed `Expr1` of each equation once and
/// records each read with its lag; this query attaches the phase and resolves
/// each name through [`DepScope::resolve`], reading the owning model only
/// through the per-name firewall projections (`model_variable_by_name`,
/// `model_implicit_var_by_name`, `project_model_by_name`), so the memo depends
/// on the instances a qualified read crosses and on nothing else of the model.
///
/// `module_inputs` is the module instance's input wiring (the empty
/// `ModuleInputSet` for the no-inputs case), the one instance-specific fact
/// the extraction reads: `classify_dependencies` selects the live branch of
/// an `isModuleInput(...)` conditional only when given `Some(inputs)`, and
/// walks all three branches under `None`. The empty set maps to `None` --
/// the two are NOT equivalent there -- so a caller with no instance in hand
/// (analysis, LTM, layout, libsimlin) gets the input-agnostic set and every
/// such caller shares one memo per variable.
#[salsa::tracked(returns(ref))]
pub fn variable_direct_dependencies<'db>(
    db: &'db dyn Db,
    var: SourceVariable,
    project: SourceProject,
    module_inputs: ModuleInputSet<'db>,
) -> VariableDeps {
    let canonical_inputs = module_inputs.canonical_input_set(db);
    let module_inputs_opt = if canonical_inputs.is_empty() {
        None
    } else {
        Some(&canonical_inputs)
    };
    variable_direct_dependencies_impl(db, var, project, module_inputs_opt)
}

/// Metadata for a single implicit variable generated by builtin expansion.
#[derive(Clone, PartialEq, Eq)]
pub struct ImplicitVarMeta {
    pub parent_source_var: SourceVariable,
    /// Canonical name of this helper -- its IDENTITY, and the key it is filed
    /// under in [`model_implicit_var_info`].
    ///
    /// A name rather than a position in the parent's `implicit_vars` vector:
    /// a position is only meaningful against the exact vector it was taken
    /// from, and a consumer that resolved one against a re-ordered parse read
    /// a different helper (GH #1002). A name survives reordering. The parent
    /// has exactly one parse (`parse_source_variable` is keyed on the variable
    /// and the project), so every consumer resolves the name against the same
    /// list this metadata was derived from.
    pub name: String,
    /// The position `name` occupied in the parse it was derived from -- a
    /// lookup HINT, never the identity.
    ///
    /// [`ImplicitVarMeta::find_in`] tries this position first and accepts what
    /// it finds only if that helper carries `name`; otherwise it scans. So a
    /// stale or wrong hint costs one comparison and can never yield a helper
    /// other than `name`'s.
    ///
    /// That "cannot change the answer" rests on a PRECONDITION worth naming,
    /// because it did not always hold: no two entries of one
    /// `parsed.implicit_vars` may share a name. Otherwise the hint (which
    /// points at the LAST occurrence, since this map is name-keyed and
    /// last-wins) and the scan (which returns the first) could select
    /// different helpers, and the hint would stop being an optimization.
    /// `variable::parse_var` establishes it by MERGING
    /// helpers across the dt and initial passes rather than appending, so a
    /// byte-identical repeat collapses and a genuine collision is refused;
    /// `db::fragment_determinism_tests::implicit_helper_names_are_unique_within_one_parse`
    /// is what says so for every route into the vector.
    ///
    /// It exists because the scan alone is O(k) per helper and so O(k^2) per
    /// parent variable, and `k` is not small on ordinary models: an
    /// apply-to-all `SMTH1` over an N-element dimension mints ~2N helpers on
    /// ONE variable. The clock says N=800 costs 2.13s scanning where the parent
    /// commit costs 1.12s, and 1.16s with the hint; the instruction count says
    /// it without a timer, by counting entries examined per compile: 17,289,600
    /// scanning versus 14,400 with the hint, a 1200x reduction, at a 100% hit
    /// rate on every model tried (C-LEARN, WRLD3, scirev7, and the synthetic at
    /// both 200 and 800).
    pub index_hint: usize,
    /// The phase demand of a `PREVIOUS`/`INIT` capture; `None` for a hoisted
    /// argument or a module instance. An INIT-only capture keeps its layout
    /// slot but no results key (`db::layout::flattened_offsets`).
    pub capture_kind: Option<CaptureKind>,
    pub is_module: bool,
    pub model_name: Option<String>,
    pub size: usize,
    /// Datamodel dimension names for an *arrayed* implicit helper (empty when
    /// scalar). Almost every implicit helper (module-call arguments, scalar
    /// `PREVIOUS`/`INIT` arguments) is scalar; a STRUCTURAL capture -- a
    /// snapshot-only apply-to-all body, captured once over its parent's
    /// dimensions -- is an `Equation::ApplyToAll`, so a consumer that
    /// subscripts it (`helper[<elem>]`), shapes it as a dependency or lays it
    /// out needs its declared dimensions rather than a scalar stub.
    pub dimensions: Vec<String>,
}

impl ImplicitVarMeta {
    /// The helper this metadata names, within the parse of its parent.
    ///
    /// `parsed` must be the parse of `self.parent_source_var`. `None` means the
    /// parse synthesized no helper of that name -- a loud-safe skip for the
    /// caller.
    ///
    /// The `canonicalize` is defence in depth, not load-bearing: a synthesized
    /// helper's ident is built from its parent's already-canonical ident, so
    /// every name on both sides is canonical and a raw comparison resolves
    /// identically (checked on a parent named `"My Var"`). Kept because nothing
    /// in the type system says so and the cost is a borrow.
    pub(crate) fn find_in<'a>(&self, parsed: &'a ParsedVariableResult) -> Option<&'a ImplicitVar> {
        let is_mine = |v: &ImplicitVar| canonicalize(v.ident()) == self.name;
        // Verifying the name before accepting the hint is what keeps the hint
        // a pure optimization rather than positional identity; the scan below
        // is the exceptional path, but remains the source of truth.
        if let Some(hinted) = parsed.implicit_vars.get(self.index_hint)
            && is_mine(hinted)
        {
            return Some(hinted);
        }
        parsed.implicit_vars.iter().find(|v| is_mine(v))
    }
}

impl std::fmt::Debug for ImplicitVarMeta {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ImplicitVarMeta")
            .field("name", &self.name)
            // The hint is not identity, but a WRONG one is exactly what you are
            // looking at this for, so it is rendered rather than hidden.
            .field("index_hint", &self.index_hint)
            .field("capture_kind", &self.capture_kind.map(CaptureKind::as_str))
            .field("size", &self.size)
            .field("dimensions", &self.dimensions)
            .finish()
    }
}

/// Collect metadata about all implicit variables in a model.
/// The returned map is keyed by the canonical implicit variable name.
#[salsa::tracked(returns(ref))]
pub fn model_implicit_var_info(
    db: &dyn Db,
    model: SourceModel,
    project: SourceProject,
) -> HashMap<String, ImplicitVarMeta> {
    let source_vars = model.variables(db);
    let mut result = HashMap::new();

    for source_var in source_vars.values() {
        let parsed = parse_source_variable(db, *source_var, project);
        for (index, implicit_var) in parsed.implicit_vars.iter().enumerate() {
            let name = canonicalize(implicit_var.ident()).into_owned();
            let capture_kind = implicit_var.capture().map(|c| c.kind());
            let is_module = implicit_var.is_module();
            let model_name = implicit_var.module().map(|m| m.model_name.clone());
            // A structural capture applies over its parent's dimensions;
            // every other helper is scalar
            // (empty dims, size 1). Resolve the dimension sizes from the
            // project's dimension definitions so a consumer that subscripts the
            // helper sees its real array shape.
            let dimensions: Vec<String> = implicit_var.equation_dims().to_vec();
            let size = if dimensions.is_empty() {
                1
            } else {
                let all_dims = project_datamodel_dims(db, project);
                dimensions
                    .iter()
                    .map(|dim_name| {
                        // Canonical match: the helper's stored dim names are
                        // canonical (`region`); the project dims keep original
                        // casing (`Region`). A raw `==` would miss and the size
                        // would wrongly fall back to 1, corrupting the layout.
                        let canonical = canonicalize(dim_name);
                        all_dims
                            .iter()
                            .find(|d| canonicalize(d.name()) == canonical)
                            .map(|d| d.len())
                            .unwrap_or(1)
                    })
                    .product()
            };
            result.insert(
                name.clone(),
                ImplicitVarMeta {
                    parent_source_var: *source_var,
                    name,
                    index_hint: index,
                    capture_kind,
                    is_module,
                    model_name,
                    size,
                    dimensions,
                },
            );
        }
    }

    result
}

/// Resolve one *implicit* (SMOOTH/DELAY/TREND/PREVIOUS/INIT) helper of `model`
/// by its canonical name -- the firewall over `model_implicit_var_info`, the
/// third coarse edge on the per-variable fragment path.
///
/// `model_implicit_var_info` is derived from every variable's parse, so adding
/// a variable that synthesizes ANY implicit helper changes the whole map and
/// re-executes every fragment that reads it. `explicit_fragment_input` only
/// ever asks it "is this one name an implicit helper, and what shape is it",
/// so this projection returns that and backdates on it.
///
/// With it, an added helper of either kind -- a `PREVIOUS`/`INIT` capture or
/// a module-instantiating `SMTH1`/`DELAY`/macro call -- compiles only the new
/// variable (and, for a module, the sub-model's first instance): every other
/// variable's parse is keyed on the variable and the project alone, so
/// nothing re-keys it. Pinned by
/// `db::fragment_char_tests::implicit_helper_add_is_tight_for_plain_and_module_helpers`
/// and `module_helper_add_reparses_only_the_added_variable`, which count
/// every tracked query's executions rather than the fragment compilers alone.
#[salsa::tracked(returns(clone))]
pub(crate) fn model_implicit_var_by_name(
    db: &dyn Db,
    model: SourceModel,
    project: SourceProject,
    name: String,
) -> Option<ImplicitVarMeta> {
    model_implicit_var_info(db, model, project)
        .get(&name)
        .cloned()
}

/// Resolve one variable of `model` by its canonical name -- a salsa
/// *firewall* over the `SourceModel::variables` map field.
///
/// Reading `model.variables(db)` directly makes the reader depend on the whole
/// map, so adding, deleting or renaming ANY variable invalidates it. That is
/// what made every per-variable fragment in a model recompile whenever the
/// model's variable SET changed, even though the fragments were bit-identical
/// (GH #964's "layout-only project edits continue to reuse unchanged
/// salsa-cached fragments" criterion). This query still reads the whole map,
/// so it re-executes on any such edit -- but its VALUE is one handle, so salsa
/// backdates it whenever that one variable is untouched and no reader re-runs.
/// A fragment therefore depends on exactly the dependencies it looks up.
///
/// The handle is stable across unrelated edits because `sync` threads the
/// prior `SourceVariable` inputs through `PersistentSyncState`; a genuinely
/// re-created variable (delete + re-add, or a rename) gets a new handle, and
/// its readers -- only those that name it -- re-execute.
#[salsa::tracked(returns(clone))]
pub(crate) fn model_variable_by_name(
    db: &dyn Db,
    model: SourceModel,
    name: String,
) -> Option<SourceVariable> {
    model.variables(db).get(&name).copied()
}

/// Resolve one model of `project` by its canonical name -- the firewall over
/// the project's model map, for the same reason `model_variable_by_name` is
/// one over a model's variable map: a reader of the map depends on every
/// model in the project, while this query re-executes when a model is added
/// or removed and backdates on the unchanged handle. What the dependency
/// resolver reads to follow a module hop into the instantiated model.
#[salsa::tracked(returns(clone))]
pub(crate) fn project_model_by_name(
    db: &dyn Db,
    project: SourceProject,
    name: String,
) -> Option<SourceModel> {
    project.models(db).get(&name).copied()
}

/// The model `var` belongs to -- its `owner_model` name resolved in the
/// project's model map.
///
/// A projection for the same reason `model_variable_by_name` is one: the map
/// is one input field, so a reader of it depends on every model in the
/// project, while this query re-executes when a model is added or removed
/// and backdates on the unchanged handle. `None` only when the name resolves
/// to no model, which a synced project never produces: the stdlib models are
/// spliced into `project.models` on every sync too.
#[salsa::tracked(returns(clone))]
pub(crate) fn variable_owner_model(
    db: &dyn Db,
    project: SourceProject,
    var: SourceVariable,
) -> Option<SourceModel> {
    project.models(db).get(var.owner_model(db)).copied()
}

/// Extracts the set of dimension names referenced in a variable's equation.
///
/// Reads only `var.equation(db)` -- never the project-level dimension list.
/// This means scalar variables produce an empty set without establishing a
/// dependency on `project.dimensions`, so dimension changes cannot
/// invalidate them. For arrayed variables the returned names come from the
/// equation definition, not from the project dimension list.
#[salsa::tracked(returns(ref))]
pub fn variable_relevant_dimensions(db: &dyn Db, var: SourceVariable) -> BTreeSet<String> {
    match var.equation(db) {
        datamodel::Equation::Scalar(_) => BTreeSet::new(),
        datamodel::Equation::ApplyToAll(dim_names, _) => dim_names.iter().cloned().collect(),
        datamodel::Equation::Arrayed(dim_names, _, _, _) => dim_names.iter().cloned().collect(),
    }
}

/// A variable's DECLARED dimensions, resolved against the project.
///
/// Derived straight from `var.equation(db)`'s dimension-name list rather than
/// from a parse: the layout and the dependency shapes need only the declared
/// axes, which are one field read where a parse is a lex and a walk of the
/// equation.
///
/// The derivation mirrors `parse_source_variable`'s own narrowed
/// dimension context exactly -- `variable_relevant_dimensions` widened by
/// `expand_maps_to_chains` and filtered out of `project_datamodel_dims` -- so
/// a name resolves here iff it resolves there. Keeping the narrowing (rather
/// than reading the whole-project `project_dimensions_context`) is what
/// preserves dimension-granularity invalidation: a scalar variable takes the
/// early return and never depends on the project's dimensions at all
/// (`db::dimension_invalidation_tests`).
///
/// **`Ast::ApplyToAll` is built as `ast.map(|ast| ApplyToAll(dims, ast))`**, so
/// an A2A equation that yields no `Ast` yields no dimensions -- and `parse`
/// answers `Ok(None)` for exactly one reason, an input with no tokens. That is
/// reachable on VALID, COMPILING models: a standalone lookup-only table (an
/// empty A2A equation plus a `<gf>`, issue #606) and a module input port whose
/// own equation is dead are both empty-equation A2A variables, and reporting
/// their declared extent would widen `variable_size` from 1 and shift every
/// later variable's layout offset. The A2A arm therefore gates on
/// `parser::is_token_free`, which is a LEX rather than a parse.
///
/// **One arm still differs from the parse, deliberately.** An A2A equation that
/// is not token-free but does not PARSE (`Err`, not `Ok(None)`) reported no
/// dimensions and now reports its declared ones. That divergence is confined to
/// a project which already fails to assemble -- the parse error still reaches
/// `compile_var_fragment`, which drops the fragment and accumulates the
/// diagnostic -- and it moves the reported size from a wrong 1 toward the
/// declaration, so nothing that compiled before reads a different slot. The
/// unresolvable-dimension-name arm (`[]` on either path) and the `Arrayed` arm
/// (built unconditionally once its dims resolve, however many element equations
/// failed) are unchanged. Every arm is enumerated in
/// `db::variable_dimensions_tests`, asserted against the previous
/// implementation as an oracle rather than against hand-written expectations.
#[salsa::tracked(returns(ref))]
pub fn variable_dimensions(
    db: &dyn Db,
    var: SourceVariable,
    project: SourceProject,
) -> Vec<crate::dimensions::Dimension> {
    let dimension_names: &[String] = match var.equation(db) {
        datamodel::Equation::Scalar(_) => return Vec::new(),
        datamodel::Equation::ApplyToAll(dim_names, eqn) => {
            // `parse_equation`'s A2A arm is `ast.map(|ast| ApplyToAll(dims, ast))`,
            // so an equation that produces no `Ast` produces no dimensions --
            // and `parse` returns `Ok(None)` for exactly one reason: the input
            // contains no tokens. That is the case for a STANDALONE LOOKUP-ONLY
            // table (an empty `ApplyToAll` equation plus a `<gf>`) and for a
            // module input port whose dead equation is empty, both of which are
            // VALID and both of which compile -- so answering with the declared
            // dimensions here would widen their `variable_size` from 1 and shift
            // every later variable's layout offset on a working model.
            //
            // `is_token_free` is a lex, not a parse: it neither builds an AST
            // nor resolves anything, so this keeps the whole point of deriving
            // the dimensions instead of demanding `parse_source_variable_*`.
            if crate::parser::is_token_free(eqn, crate::lexer::LexerType::Equation) {
                return Vec::new();
            }
            dim_names
        }
        // `Arrayed` needs no such check: the parse builds its `Ast` whenever the
        // dimension names resolve, however many element equations failed.
        datamodel::Equation::Arrayed(dim_names, _, _, _) => dim_names,
    };
    // A module variable carries a synthesized equation but has no array shape
    // of its own (the parse's `Variable::Module` has no `ast` for
    // `get_dimensions` to read), so it must report none.
    if var.kind(db) == SourceVariableKind::Module {
        return Vec::new();
    }
    if dimension_names.is_empty() {
        return Vec::new();
    }
    let expanded = expand_maps_to_chains(
        variable_relevant_dimensions(db, var),
        project.dimensions(db),
    );
    let dims: Vec<datamodel::Dimension> = project_datamodel_dims(db, project)
        .iter()
        .filter(|d| expanded.contains(&d.name))
        .cloned()
        .collect();
    let dim_ctx = crate::dimensions::DimensionsContext::from(&dims);
    // `Err` is an unresolvable dimension name, which the parse also turns into
    // "no dimensions" (it pushes a `BadDimensionName` and drops the `Ast`).
    crate::variable::get_dimensions(&dim_ctx, dimension_names).unwrap_or_default()
}

#[salsa::tracked(returns(clone))]
pub fn variable_size(db: &dyn Db, var: SourceVariable, project: SourceProject) -> usize {
    let dims = variable_dimensions(db, var, project);
    if dims.is_empty() {
        1
    } else {
        dims.iter().map(|d| d.len()).product()
    }
}

/// The project's explicit module-instance graph: each model maps to the models
/// its `Variable::Module`s instantiate (only existing targets -- the same edges
/// the recursive `compute_layout` / `model_shape` queries follow). Built
/// with flat reads so cycle detection never recurses through salsa.
///
/// A cycle in this graph makes those recursive queries loop, which salsa turns
/// into an unrecoverable dependency-graph panic (the empty-`model_name` sibling
/// of this class was fixed in c1c4c954; GH #806). Every production compile /
/// diagnostic / analysis entry point consults this FIRST -- scoped to the models
/// reachable from the requested root -- so a cycle surfaces as a clean
/// `CircularDependency` error rather than aborting WASM, WITHOUT rejecting a
/// valid root just because an unrelated draft elsewhere in the project is cyclic.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ModuleReferenceGraph {
    edges: BTreeMap<Ident<Canonical>, Vec<Ident<Canonical>>>,
}

impl ModuleReferenceGraph {
    /// The first module cycle REACHABLE FROM `root` as a closed path of model
    /// names (start repeated at the end), or `None` if `root`'s reachable
    /// subgraph is acyclic (or `root` names no model). Iterative 3-color DFS so a
    /// pathologically deep chain cannot overflow the stack; deterministic given
    /// the sorted adjacency. Scoping to reachability is what keeps an unrelated
    /// draft cycle from rejecting a compile of `root` -- the recursive queries
    /// only loop for modules under the requested root.
    pub fn cycle_reachable_from(&self, root: &str) -> Option<Vec<Ident<Canonical>>> {
        let root_ident: Ident<Canonical> = Ident::new(root);
        if !self.edges.contains_key(&root_ident) {
            return None;
        }

        #[derive(Clone, Copy, PartialEq)]
        enum Color {
            Gray,
            Black,
        }

        // `path` mirrors the Gray frames currently on the stack, so a back-edge
        // yields the exact cycle. Owned idents keep the borrow simple; the graph
        // is model-sized, so the clones are cheap.
        let mut color: BTreeMap<Ident<Canonical>, Color> = BTreeMap::new();
        let mut stack: Vec<(Ident<Canonical>, usize)> = vec![(root_ident.clone(), 0)];
        let mut path: Vec<Ident<Canonical>> = vec![root_ident.clone()];
        color.insert(root_ident, Color::Gray);

        while let Some((node, child_idx)) = stack.last().cloned() {
            let Some(children) = self.edges.get(&node) else {
                stack.pop();
                path.pop();
                continue;
            };
            if child_idx >= children.len() {
                color.insert(node, Color::Black);
                stack.pop();
                path.pop();
                continue;
            }
            stack.last_mut().unwrap().1 += 1;
            let child = children[child_idx].clone();
            match color.get(&child).copied() {
                Some(Color::Gray) => {
                    // Back-edge: the cycle runs from `child`'s position in the
                    // current path, closed by `child` again.
                    let start = path.iter().position(|n| *n == child).unwrap();
                    let mut cycle = path[start..].to_vec();
                    cycle.push(child);
                    return Some(cycle);
                }
                Some(Color::Black) => {}
                None => {
                    color.insert(child.clone(), Color::Gray);
                    stack.push((child.clone(), 0));
                    path.push(child);
                }
            }
        }

        None
    }

    /// Whether some explicit module instance in the project instantiates the
    /// model named `model` (canonical name).
    pub fn is_target(&self, model: &str) -> bool {
        self.edges
            .values()
            .any(|targets| targets.iter().any(|t| t.as_str() == model))
    }

    /// Formats a cycle reachable from `root` as a `(CircularDependency, message)`
    /// diagnostic pair, or `None` if `root` reaches no cycle.
    pub fn cycle_error_from(&self, root: &str) -> Option<(crate::common::ErrorCode, String)> {
        self.cycle_reachable_from(root).map(|cycle| {
            let path = cycle
                .iter()
                .map(|m| m.as_str().to_string())
                .collect::<Vec<_>>()
                .join(" → ");
            (
                crate::common::ErrorCode::CircularDependency,
                format!("circular module reference: {path}"),
            )
        })
    }
}

/// Build the project's explicit module-instance graph (see
/// [`ModuleReferenceGraph`]). Reads each model's module variables and their
/// target `model_name`s with flat salsa reads (no recursion). Implicit
/// (SMOOTH/DELAY/TREND/stdlib/MACRO-call) modules are omitted, which keeps this
/// query structural: it reads variable KINDS and target names, never a parse
/// result, so it is invalidated by a variable being added, removed or retargeted
/// and not by an equation being typed. Every production entry point consults it,
/// so widening it to parse-derived edges would put every variable's parse on
/// every compile's dependency list.
///
/// # Why omitting implicit edges is nonetheless SOUND
///
/// The omission is sound only because `MacroRegistry::build`'s Pass 4 rejects a
/// `Variable::Module` inside a macro-marked model (`MacroContainsModule`).
/// Without that rejection it would not be: a MACRO call expands into an
/// implicit module targeting the macro's own model -- an ordinary user model --
/// and a macro whose body instantiated a module targeting a model that CALLED
/// that macro would close a cycle this graph does not see, so `compute_layout`
/// (which does follow implicit edges) would hit salsa's unrecoverable
/// dependency-graph cycle panic with this gate reporting no cycle at all. With
/// the rejection, every implicit module edge terminates somewhere that cannot
/// continue an invisible cycle:
///
///   - The edges are synthesized at ONE site,
///     `builtins_visitor::expand_module_function`, from a
///     `ModuleFunctionDescriptor`; that type has exactly two producers,
///     `module_functions::stdlib_descriptor` (target `stdlib⁚{name}`) and
///     `MacroRegistry::build`'s Pass 1 (target the macro's own model).
///   - A stdlib model is a SINK -- it instantiates no module, explicit or
///     implicit. Test-asserted over the SYNCED Stage0s by
///     `db::units_tests::stdlib_templates_are_scalar_and_instantiate_no_module`,
///     which is the tripwire if a template ever gains one.
///   - A macro model's three possible outgoing edges are all handled: an explicit
///     module in its body (Pass 4 rejects it), an implicit macro-to-macro edge
///     (Pass 3 rejects a cycle among those, and on ANY build failure the registry
///     the pipeline receives is EMPTY, so no call resolves as a macro and the edge
///     does not exist -- see `db::macro_registry::project_macro_registry`), or an
///     implicit stdlib edge (to a sink).
///
/// So every remaining cycle lies entirely in explicit edges, which is exactly what
/// this query records.
///
/// **RESIDUAL** (enumerated, not proved): the first bullet assumes builtin
/// expansion and macro expansion are the ONLY synthesisers of implicit module
/// vars. That came from reading the code paths -- the single
/// `expand_module_function` synthesis site and the two descriptor producers --
/// not from any exhaustiveness check.
///
/// Three things RECORD implicit module vars downstream of that one synthesis
/// site, and only one of them can open a cycle path:
///
///   - `model_implicit_var_info` (`is_module` + `model_name`) -- read by BOTH
///     recursive queries, which recurse on its module entries. This is the live
///     path, and the one the argument above is about.
///   - `db::ltm::model_ltm_implicit_var_info` (`LtmImplicitVarMeta`, same two
///     fields) -- `compute_layout` reads it but takes `meta.size` verbatim
///     rather than recursing (Section 3b), and `model_shape` recurses only
///     through `compute_layout`. Inert for cycle safety TODAY; listed because making it
///     recursive is a one-line edit that would silently reopen this.
///   - `db::model_scope_models` -- reads the explicit `Module` variables and
///     `model_implicit_var_info`'s module entries, but is an iterative
///     worklist, not a recursive tracked query, so a cycle terminates.
///
/// A future implicit-var synthesizer that mints a `Variable::Module` with some
/// other target would be invisible to this gate again, and NO test would go red:
/// the two tripwires that exist cover the stdlib-sink premise and the
/// empty-registry premise, not this one. Anyone adding an implicit-var
/// synthesizer, or making the LTM recorder recursive, has to check it by hand.
///
/// `db::model_scope_models` walks the same edges plus the implicit ones
/// and is iterative, so it is unaffected either way.
#[salsa::tracked(returns(ref))]
pub fn project_module_graph(db: &dyn Db, project: SourceProject) -> ModuleReferenceGraph {
    let models = project.models(db);

    // Build the adjacency deterministically (sorted models, sorted vars) so the
    // reported cycle is stable across processes and salsa invalidations.
    let mut sorted_models: Vec<(&String, &SourceModel)> = models.iter().collect();
    sorted_models.sort_by(|a, b| a.0.cmp(b.0));

    let mut edges: BTreeMap<Ident<Canonical>, Vec<Ident<Canonical>>> = BTreeMap::new();
    for (name, model) in sorted_models {
        let model_ident: Ident<Canonical> = Ident::new(name);
        let source_vars = model.variables(db);
        let mut sorted_var_names: Vec<&String> = source_vars.keys().collect();
        sorted_var_names.sort_unstable();

        let mut targets = Vec::new();
        for var_name in sorted_var_names {
            let svar = &source_vars[var_name];
            if svar.kind(db) == SourceVariableKind::Module {
                let target = canonicalize(svar.model_name(db));
                // Only follow targets that exist -- a dangling / empty
                // `model_name` is not a cycle (and is handled elsewhere).
                if models.contains_key(target.as_ref()) {
                    targets.push(Ident::new(target.as_ref()));
                }
            }
        }
        edges.insert(model_ident, targets);
    }

    ModuleReferenceGraph { edges }
}
