// Copyright 2026 The Simlin Authors. All rights reserved.
// Use of this source code is governed by the Apache License,
// Version 2.0, that can be found in the LICENSE file.

//! LTM (Loops That Matter) equation parsing and compilation.
//!
//! This module contains the per-equation compilation pipeline for LTM
//! synthetic variables: link scores, loop scores, and relative loop
//! scores. It handles PREVIOUS module expansion and produces symbolic
//! bytecodes for assembly by `assemble_module`.

use std::collections::{BTreeSet, HashMap, HashSet};

use crate::canonicalize;
use crate::common::{Canonical, Ident};
use crate::datamodel;

use super::{
    Db, LtmLinkId, ModelDepGraphResult, ParsedVariableResult, SourceModel, SourceProject,
    SourceVariableKind, VarFragmentResult, build_module_inputs, build_stub_variable,
    build_submodel_metadata, canonical_module_input_set, compute_layout, link_score_equation_text,
    model_implicit_var_info, model_ltm_all_link_synthetic_variables, model_ltm_synthetic_variables,
    model_module_map, parse_source_variable, project_datamodel_dims, project_units_context,
    variable_dimensions, variable_size,
};

/// Parse an LTM synthetic variable's equation string as a scalar aux.
///
/// Creates a transient `datamodel::Variable::Aux`, runs it through
/// `parse_var` (which invokes `BuiltinVisitor` and
/// `instantiate_implicit_modules`), and returns the parsed variable plus
/// any implicit module variables generated by PREVIOUS expansion.
pub(super) fn parse_ltm_equation(
    var_name: &str,
    equation: &str,
    dims: &[datamodel::Dimension],
    units_ctx: &crate::units::Context,
) -> ParsedVariableResult {
    let dm_var = datamodel::Variable::Aux(datamodel::Aux {
        ident: canonicalize(var_name).into_owned(),
        equation: datamodel::Equation::Scalar(equation.to_string()),
        documentation: String::new(),
        units: None,
        gf: None,
        ai_state: None,
        uid: None,
        compat: datamodel::Compat::default(),
    });

    let mut implicit_vars = Vec::new();
    let variable = crate::variable::parse_var(dims, &dm_var, &mut implicit_vars, units_ctx, |mi| {
        Ok(Some(mi.clone()))
    });

    ParsedVariableResult {
        variable,
        implicit_vars,
    }
}

/// Metadata about implicit variables generated by LTM equation parsing.
///
/// Each LTM link-score equation uses PREVIOUS() which creates implicit
/// stdlib module instances. This structure collects the implicit
/// variables across all LTM equations in a model so that `compute_layout`
/// can allocate slots and `assemble_module` can compile them.
#[derive(Clone, Debug, PartialEq, Eq, salsa::Update)]
pub struct LtmImplicitVarMeta {
    /// Canonical name of the LTM variable that created this implicit var
    pub ltm_parent_name: String,
    /// Index into the parent's implicit_vars list
    pub index_in_parent: usize,
    /// Whether this implicit var is a stock
    pub is_stock: bool,
    /// Whether this implicit var is a module
    pub is_module: bool,
    /// Sub-model name if is_module is true
    pub model_name: Option<String>,
    /// Size in slots (for scalar vars: 1; for modules: sub-model n_slots)
    pub size: usize,
}

/// Cached implicit variable info for all LTM synthetic variables.
///
/// Parses each LTM equation to discover implicit modules (PREVIOUS
/// instances), caching the results. Both `compute_layout` and
/// `assemble_module` read this to allocate slots and compile fragments
/// for PREVIOUS module instances within LTM equations.
#[salsa::tracked(returns(ref))]
pub fn model_ltm_implicit_var_info(
    db: &dyn Db,
    model: SourceModel,
    project: SourceProject,
) -> HashMap<String, LtmImplicitVarMeta> {
    if !project.ltm_enabled(db) {
        return HashMap::new();
    }

    let ltm_vars = if project.ltm_discovery_mode(db) {
        model_ltm_all_link_synthetic_variables(db, model, project)
    } else {
        model_ltm_synthetic_variables(db, model, project)
    };

    let dims = project_datamodel_dims(db, project);
    let units_ctx = project_units_context(db, project);

    let mut result = HashMap::new();

    for ltm_var in &ltm_vars.vars {
        let parsed = parse_ltm_equation(&ltm_var.name, &ltm_var.equation, dims, units_ctx);

        let project_models = project.models(db);

        for (idx, implicit_dm_var) in parsed.implicit_vars.iter().enumerate() {
            let im_name = canonicalize(implicit_dm_var.get_ident()).into_owned();
            let is_module = matches!(implicit_dm_var, datamodel::Variable::Module(_));
            let is_stock = matches!(implicit_dm_var, datamodel::Variable::Stock(_));
            let model_name = if let datamodel::Variable::Module(m) = implicit_dm_var {
                Some(m.model_name.clone())
            } else {
                None
            };
            let size = if is_module {
                model_name
                    .as_deref()
                    .and_then(|mn| {
                        let sub_canonical = canonicalize(mn);
                        project_models
                            .get(sub_canonical.as_ref())
                            .map(|sm| compute_layout(db, *sm, project, false).n_slots)
                    })
                    .unwrap_or(1)
            } else {
                1
            };

            result.insert(
                im_name,
                LtmImplicitVarMeta {
                    ltm_parent_name: ltm_var.name.clone(),
                    index_in_parent: idx,
                    is_stock,
                    is_module,
                    model_name,
                    size,
                },
            );
        }
    }

    result
}

/// Compile a single LTM synthetic variable's equation to symbolic
/// bytecodes.
///
/// This is the per-link compilation granularity that enables incremental
/// recomputation: when a variable's equation changes, salsa only
/// recompiles fragments for affected links. Equation edits that don't
/// change the dependency set return their cached fragment (AC1.2).
///
/// LTM equations are pure scalar aux equations that may reference:
/// - Model variables (stocks, flows, auxes) from the parent model
/// - Other LTM variables (loop scores referencing link scores)
/// - Implicit module variables (PREVIOUS instances created by module
///   expansion)
/// - Implicit time/dt/initial_time/final_time variables
///
/// Since PREVIOUS still uses module expansion (not the LoadPrev opcode),
/// the parsed equation will contain implicit module variables that need
/// to be handled the same way as in `compile_var_fragment`.
#[salsa::tracked(returns(ref))]
pub fn compile_ltm_var_fragment(
    db: &dyn Db,
    link_id: LtmLinkId<'_>,
    model: SourceModel,
    project: SourceProject,
) -> Option<VarFragmentResult> {
    let lsv = link_score_equation_text(db, link_id, model, project).as_ref()?;

    compile_ltm_equation_fragment(db, &lsv.name, &lsv.equation, model, project)
}

/// Compile an arbitrary LTM equation string to symbolic bytecodes.
///
/// Shared implementation used by `compile_ltm_var_fragment` (link scores)
/// and the loop/relative score compilation in `assemble_module`. Handles
/// PREVIOUS module expansion by building a mini-context that includes
/// both model variables and implicit module variables.
pub(super) fn compile_ltm_equation_fragment(
    db: &dyn Db,
    var_name: &str,
    equation: &str,
    model: SourceModel,
    project: SourceProject,
) -> Option<VarFragmentResult> {
    use crate::compiler::symbolic::{
        CompiledVarFragment, PerVarBytecodes, ReverseOffsetMap, VariableLayout,
    };

    let dims = project_datamodel_dims(db, project);
    let dim_context = crate::dimensions::DimensionsContext::from(dims.as_slice());
    let converted_dims: Vec<crate::dimensions::Dimension> = dims
        .iter()
        .map(crate::dimensions::Dimension::from)
        .collect();

    let units_ctx = project_units_context(db, project);

    let parsed = parse_ltm_equation(var_name, equation, dims, units_ctx);

    // Check for parse errors
    if parsed
        .variable
        .equation_errors()
        .is_some_and(|e| !e.is_empty())
    {
        return None;
    }

    // Lower the variable. LTM vars are always scalar auxes.
    let models = HashMap::new();
    let scope = crate::model::ScopeStage0 {
        models: &models,
        dimensions: &dim_context,
        model_name: "",
    };
    let lowered = crate::model::lower_variable(&scope, &parsed.variable);

    let model_name_ident = Ident::new(model.name(db));
    let var_name_canonical = canonicalize(var_name).into_owned();
    let var_ident_canonical: Ident<Canonical> = Ident::new(&var_name_canonical);

    // Arena for sub-model stub variables allocated by build_submodel_metadata
    let arena = bumpalo::Bump::new();

    let mut mini_metadata: HashMap<Ident<Canonical>, crate::compiler::VariableMetadata<'_>> =
        HashMap::new();

    // LTM vars are always compiled in the root model context
    let mut mini_offset = crate::vm::IMPLICIT_VAR_COUNT;

    // Add implicit time/dt/initial_time/final_time variables
    {
        use std::sync::LazyLock;
        static IMPLICIT_TIME: LazyLock<crate::variable::Variable> =
            LazyLock::new(|| crate::variable::Variable::Var {
                ident: Ident::new("time"),
                ast: None,
                init_ast: None,
                eqn: None,
                units: None,
                tables: vec![],
                non_negative: false,
                is_flow: false,
                is_table_only: false,
                errors: vec![],
                unit_errors: vec![],
            });
        static IMPLICIT_DT: LazyLock<crate::variable::Variable> =
            LazyLock::new(|| crate::variable::Variable::Var {
                ident: Ident::new("dt"),
                ast: None,
                init_ast: None,
                eqn: None,
                units: None,
                tables: vec![],
                non_negative: false,
                is_flow: false,
                is_table_only: false,
                errors: vec![],
                unit_errors: vec![],
            });
        static IMPLICIT_INITIAL_TIME: LazyLock<crate::variable::Variable> =
            LazyLock::new(|| crate::variable::Variable::Var {
                ident: Ident::new("initial_time"),
                ast: None,
                init_ast: None,
                eqn: None,
                units: None,
                tables: vec![],
                non_negative: false,
                is_flow: false,
                is_table_only: false,
                errors: vec![],
                unit_errors: vec![],
            });
        static IMPLICIT_FINAL_TIME: LazyLock<crate::variable::Variable> =
            LazyLock::new(|| crate::variable::Variable::Var {
                ident: Ident::new("final_time"),
                ast: None,
                init_ast: None,
                eqn: None,
                units: None,
                tables: vec![],
                non_negative: false,
                is_flow: false,
                is_table_only: false,
                errors: vec![],
                unit_errors: vec![],
            });
        mini_metadata.insert(
            Ident::new("time"),
            crate::compiler::VariableMetadata {
                offset: 0,
                size: 1,
                var: &IMPLICIT_TIME,
            },
        );
        mini_metadata.insert(
            Ident::new("dt"),
            crate::compiler::VariableMetadata {
                offset: 1,
                size: 1,
                var: &IMPLICIT_DT,
            },
        );
        mini_metadata.insert(
            Ident::new("initial_time"),
            crate::compiler::VariableMetadata {
                offset: 2,
                size: 1,
                var: &IMPLICIT_INITIAL_TIME,
            },
        );
        mini_metadata.insert(
            Ident::new("final_time"),
            crate::compiler::VariableMetadata {
                offset: 3,
                size: 1,
                var: &IMPLICIT_FINAL_TIME,
            },
        );
    }

    // Add self (the LTM var itself)
    mini_metadata.insert(
        var_ident_canonical.clone(),
        crate::compiler::VariableMetadata {
            offset: mini_offset,
            size: 1,
            var: &lowered,
        },
    );
    mini_offset += 1;

    // Collect dependency variable names from the lowered AST
    let dep_idents = if let Some(ast) = lowered.ast() {
        crate::variable::identifier_set(ast, &[], None)
    } else {
        HashSet::new()
    };

    let source_vars = model.variables(db);
    let project_models = project.models(db);
    let implicit_info = model_implicit_var_info(db, model, project);
    let ltm_implicit_info = model_ltm_implicit_var_info(db, model, project);

    let mut dep_variables: Vec<(Ident<Canonical>, crate::variable::Variable, usize)> = Vec::new();
    let mut implicit_module_vars: Vec<(Ident<Canonical>, crate::variable::Variable, usize)> =
        Vec::new();
    let mut implicit_module_refs: HashMap<Ident<Canonical>, crate::vm::ModuleKey> = HashMap::new();
    let mut implicit_submodels: Vec<(String, SourceModel)> = Vec::new();

    // Process dependencies from the parsed AST
    for dep_ident_str in &dep_idents {
        let dep_str = dep_ident_str.as_str();
        let effective = dep_str.strip_prefix('\u{00B7}').unwrap_or(dep_str);

        if effective == var_name_canonical
            || matches!(effective, "time" | "dt" | "initial_time" | "final_time")
        {
            continue;
        }

        // Handle module output references (contains middle dot)
        if let Some(dot_pos) = effective.find('\u{00B7}') {
            let module_var_name = &effective[..dot_pos];
            let module_ident: Ident<Canonical> = Ident::new(module_var_name);

            if mini_metadata.contains_key(&module_ident)
                || implicit_module_vars
                    .iter()
                    .any(|(id, _, _)| id == &module_ident)
            {
                continue;
            }

            // Check if this is an explicit model variable (module type)
            if let Some(mod_source_var) = source_vars.get(module_var_name) {
                if mod_source_var.kind(db) == SourceVariableKind::Module {
                    let mod_model_name = mod_source_var.model_name(db);
                    let sub_canonical = canonicalize(mod_model_name);
                    let sub_size = project_models
                        .get(sub_canonical.as_ref())
                        .map(|sm| compute_layout(db, *sm, project, false).n_slots)
                        .unwrap_or(1);

                    let mod_input_prefix = format!("{module_var_name}\u{00B7}");
                    let module_inputs = build_module_inputs(
                        model.name(db),
                        &mod_input_prefix,
                        mod_source_var
                            .module_refs(db)
                            .iter()
                            .map(|mr| (canonicalize(&mr.src), canonicalize(&mr.dst))),
                    );

                    let mod_var = crate::variable::Variable::Module {
                        ident: module_ident.clone(),
                        model_name: Ident::new(mod_model_name),
                        units: None,
                        inputs: module_inputs.clone(),
                        errors: vec![],
                        unit_errors: vec![],
                    };
                    dep_variables.push((module_ident.clone(), mod_var, sub_size));

                    let input_set: BTreeSet<Ident<Canonical>> =
                        module_inputs.iter().map(|mi| mi.dst.clone()).collect();
                    implicit_module_refs
                        .insert(module_ident, (Ident::new(mod_model_name), input_set));

                    if let Some(sub_model) = project_models.get(sub_canonical.as_ref()) {
                        implicit_submodels.push((mod_model_name.to_string(), *sub_model));
                    }
                }
                continue;
            }

            // Check if this is an implicit module from the LTM equation's own
            // PREVIOUS expansion
            let mut found_in_parsed = false;
            for implicit_dm_var in &parsed.implicit_vars {
                if let datamodel::Variable::Module(dm_module) = implicit_dm_var
                    && canonicalize(&dm_module.ident) == module_var_name
                {
                    let sub_canonical = canonicalize(&dm_module.model_name);
                    let sub_size = project_models
                        .get(sub_canonical.as_ref())
                        .map(|sm| compute_layout(db, *sm, project, false).n_slots)
                        .unwrap_or(1);

                    let input_prefix = format!("{module_var_name}\u{00B7}");
                    let module_inputs = build_module_inputs(
                        model.name(db),
                        &input_prefix,
                        dm_module
                            .references
                            .iter()
                            .map(|mr| (canonicalize(&mr.src), canonicalize(&mr.dst))),
                    );

                    let im_var = crate::variable::Variable::Module {
                        ident: module_ident.clone(),
                        model_name: Ident::new(&dm_module.model_name),
                        units: None,
                        inputs: module_inputs.clone(),
                        errors: vec![],
                        unit_errors: vec![],
                    };
                    implicit_module_vars.push((module_ident.clone(), im_var, sub_size));

                    let input_set: BTreeSet<Ident<Canonical>> =
                        module_inputs.iter().map(|mi| mi.dst.clone()).collect();
                    implicit_module_refs.insert(
                        module_ident.clone(),
                        (Ident::new(&dm_module.model_name), input_set),
                    );

                    if let Some(sub_model) = project_models.get(sub_canonical.as_ref()) {
                        implicit_submodels.push((dm_module.model_name.clone(), *sub_model));
                    }

                    found_in_parsed = true;
                    break;
                }
            }

            if !found_in_parsed {
                // Check the model's own implicit vars (SMOOTH, DELAY, etc.)
                if let Some(im_meta) = implicit_info.get(module_var_name)
                    && im_meta.is_module
                    && let Some(im_model_name) = im_meta.model_name.as_deref()
                {
                    let sub_canonical = canonicalize(im_model_name);
                    let sub_size = project_models
                        .get(sub_canonical.as_ref())
                        .map(|sm| compute_layout(db, *sm, project, false).n_slots)
                        .unwrap_or(1);

                    let parent_parsed =
                        parse_source_variable(db, im_meta.parent_source_var, project);
                    let input_prefix = format!("{module_var_name}\u{00B7}");
                    let module_inputs = parent_parsed
                        .implicit_vars
                        .iter()
                        .find_map(|iv| match iv {
                            datamodel::Variable::Module(dm_module)
                                if canonicalize(dm_module.ident.as_str()) == module_var_name =>
                            {
                                Some(build_module_inputs(
                                    model.name(db),
                                    &input_prefix,
                                    dm_module
                                        .references
                                        .iter()
                                        .map(|mr| (canonicalize(&mr.src), canonicalize(&mr.dst))),
                                ))
                            }
                            _ => None,
                        })
                        .unwrap_or_default();

                    let mod_var = crate::variable::Variable::Module {
                        ident: module_ident.clone(),
                        model_name: Ident::new(im_model_name),
                        units: None,
                        inputs: module_inputs.clone(),
                        errors: vec![],
                        unit_errors: vec![],
                    };
                    dep_variables.push((module_ident.clone(), mod_var, sub_size));

                    let input_set: BTreeSet<Ident<Canonical>> =
                        module_inputs.iter().map(|mi| mi.dst.clone()).collect();
                    implicit_module_refs
                        .insert(module_ident, (Ident::new(im_model_name), input_set));

                    if let Some(sub_model) = project_models.get(sub_canonical.as_ref()) {
                        implicit_submodels.push((im_model_name.to_string(), *sub_model));
                    }
                }
                // Also check LTM implicit vars from other LTM equations
                else if let Some(ltm_im_meta) = ltm_implicit_info.get(module_var_name)
                    && ltm_im_meta.is_module
                    && let Some(im_model_name) = ltm_im_meta.model_name.as_deref()
                {
                    let sub_canonical = canonicalize(im_model_name);
                    let sub_size = project_models
                        .get(sub_canonical.as_ref())
                        .map(|sm| compute_layout(db, *sm, project, false).n_slots)
                        .unwrap_or(1);

                    // Parse the parent LTM equation to get implicit var references
                    let parent_ltm_vars = if project.ltm_discovery_mode(db) {
                        model_ltm_all_link_synthetic_variables(db, model, project)
                    } else {
                        model_ltm_synthetic_variables(db, model, project)
                    };
                    let parent_ltm = parent_ltm_vars
                        .vars
                        .iter()
                        .find(|v| v.name == ltm_im_meta.ltm_parent_name);
                    let module_inputs = if let Some(parent_lsv) = parent_ltm {
                        let parent_parsed = parse_ltm_equation(
                            &parent_lsv.name,
                            &parent_lsv.equation,
                            dims,
                            units_ctx,
                        );
                        let input_prefix = format!("{module_var_name}\u{00B7}");
                        parent_parsed
                            .implicit_vars
                            .iter()
                            .find_map(|iv| match iv {
                                datamodel::Variable::Module(dm_module)
                                    if canonicalize(dm_module.ident.as_str())
                                        == module_var_name =>
                                {
                                    Some(build_module_inputs(
                                        model.name(db),
                                        &input_prefix,
                                        dm_module.references.iter().map(|mr| {
                                            (canonicalize(&mr.src), canonicalize(&mr.dst))
                                        }),
                                    ))
                                }
                                _ => None,
                            })
                            .unwrap_or_default()
                    } else {
                        Vec::new()
                    };

                    let mod_var = crate::variable::Variable::Module {
                        ident: module_ident.clone(),
                        model_name: Ident::new(im_model_name),
                        units: None,
                        inputs: module_inputs.clone(),
                        errors: vec![],
                        unit_errors: vec![],
                    };
                    dep_variables.push((module_ident.clone(), mod_var, sub_size));

                    let input_set: BTreeSet<Ident<Canonical>> =
                        module_inputs.iter().map(|mi| mi.dst.clone()).collect();
                    implicit_module_refs
                        .insert(module_ident, (Ident::new(im_model_name), input_set));

                    if let Some(sub_model) = project_models.get(sub_canonical.as_ref()) {
                        implicit_submodels.push((im_model_name.to_string(), *sub_model));
                    }
                }
            }
            continue;
        }

        let dep_ident = Ident::new(effective);
        if mini_metadata.contains_key(&dep_ident) {
            continue;
        }

        // Look up in explicit model variables
        if let Some(dep_source_var) = source_vars.get(effective) {
            let dep_dims = variable_dimensions(db, *dep_source_var, project);
            let dep_size = variable_size(db, *dep_source_var, project);
            let dep_var = build_stub_variable(db, dep_source_var, &dep_ident, dep_dims);
            dep_variables.push((dep_ident, dep_var, dep_size));
        } else if implicit_info.contains_key(effective) {
            // Dep is an implicit var from the model (SMOOTH/DELAY internal)
            dep_variables.push((
                dep_ident.clone(),
                crate::variable::Variable::Var {
                    ident: dep_ident,
                    ast: None,
                    init_ast: None,
                    eqn: None,
                    units: None,
                    tables: vec![],
                    non_negative: false,
                    is_flow: false,
                    is_table_only: false,
                    errors: vec![],
                    unit_errors: vec![],
                },
                1,
            ));
        }
        // Dep could also be another LTM var (e.g., loop score refs link scores)
        // These are scalar auxes with 1 slot.
        else {
            dep_variables.push((
                dep_ident.clone(),
                crate::variable::Variable::Var {
                    ident: dep_ident,
                    ast: None,
                    init_ast: None,
                    eqn: None,
                    units: None,
                    tables: vec![],
                    non_negative: false,
                    is_flow: false,
                    is_table_only: false,
                    errors: vec![],
                    unit_errors: vec![],
                },
                1,
            ));
        }
    }

    // Add dep metadata
    for (dep_ident, dep_var, dep_size) in &dep_variables {
        if !mini_metadata.contains_key(dep_ident) {
            mini_metadata.insert(
                dep_ident.clone(),
                crate::compiler::VariableMetadata {
                    offset: mini_offset,
                    size: *dep_size,
                    var: dep_var,
                },
            );
            mini_offset += dep_size;
        }
    }

    // Add implicit module vars from PREVIOUS expansion
    for (im_ident, im_var, im_size) in &implicit_module_vars {
        if !mini_metadata.contains_key(im_ident) {
            mini_metadata.insert(
                im_ident.clone(),
                crate::compiler::VariableMetadata {
                    offset: mini_offset,
                    size: *im_size,
                    var: im_var,
                },
            );
            mini_offset += im_size;
        }
    }

    // Build the all_metadata map
    let mut all_metadata: HashMap<
        Ident<Canonical>,
        HashMap<Ident<Canonical>, crate::compiler::VariableMetadata<'_>>,
    > = HashMap::new();
    all_metadata.insert(model_name_ident.clone(), mini_metadata);

    // Populate sub-model metadata for implicit module sub-models
    for (_sub_name, sub_model) in &implicit_submodels {
        build_submodel_metadata(&arena, db, *sub_model, project, &mut all_metadata);
    }

    let mini_layout =
        crate::compiler::symbolic::layout_from_metadata(&all_metadata, &model_name_ident)
            .unwrap_or_else(|_| VariableLayout::new(HashMap::new(), 0));
    let rmap = ReverseOffsetMap::from_layout(&mini_layout);

    // LTM vars don't have graphical functions or lookup tables
    let tables: HashMap<Ident<Canonical>, Vec<crate::compiler::Table>> = HashMap::new();

    let inputs = BTreeSet::new();
    let module_models = model_module_map(db, model, project).clone();

    let core = crate::compiler::ContextCore {
        dimensions: &converted_dims,
        dimensions_ctx: &dim_context,
        model_name: &model_name_ident,
        metadata: &all_metadata,
        module_models: &module_models,
        inputs: &inputs,
    };

    let build_var = |is_initial: bool| {
        crate::compiler::Var::new(
            &crate::compiler::Context::new(core, &var_ident_canonical, is_initial),
            &lowered,
        )
    };

    let compile_phase = |exprs: &[crate::compiler::Expr]| -> Option<PerVarBytecodes> {
        if exprs.is_empty() {
            return None;
        }

        let module_inputs_set: HashSet<Ident<Canonical>> = inputs.iter().cloned().collect();
        let module = crate::compiler::Module {
            ident: model_name_ident.clone(),
            inputs: module_inputs_set,
            n_slots: mini_offset,
            n_temps: 0,
            temp_sizes: vec![],
            runlist_initials: vec![],
            runlist_initials_by_var: vec![],
            runlist_flows: exprs.to_vec(),
            runlist_stocks: vec![],
            offsets: all_metadata
                .iter()
                .map(|(k, v)| {
                    (
                        k.clone(),
                        v.iter()
                            .map(|(vk, vm)| (vk.clone(), (vm.offset, vm.size)))
                            .collect(),
                    )
                })
                .collect(),
            runlist_order: vec![var_ident_canonical.clone()],
            tables: tables.clone(),
            dimensions: converted_dims.clone(),
            dimensions_ctx: dim_context.clone(),
            module_refs: implicit_module_refs.clone(),
        };

        let mut temp_sizes_map: HashMap<u32, usize> = HashMap::new();
        for expr in exprs {
            crate::compiler::extract_temp_sizes_pub(expr, &mut temp_sizes_map);
        }
        let n_temps = temp_sizes_map.len();
        let mut temp_sizes: Vec<usize> = vec![0; n_temps];
        for (id, size) in &temp_sizes_map {
            if (*id as usize) < temp_sizes.len() {
                temp_sizes[*id as usize] = *size;
            }
        }

        let module = crate::compiler::Module {
            n_temps,
            temp_sizes: temp_sizes.clone(),
            ..module
        };

        match module.compile() {
            Ok(compiled) => {
                let sym_bc =
                    crate::compiler::symbolic::symbolize_bytecode(&compiled.compiled_flows, &rmap)
                        .ok()?;

                let ctx = &*compiled.context;
                let sym_views: Vec<_> = ctx
                    .static_views
                    .iter()
                    .map(|sv| crate::compiler::symbolic::symbolize_static_view(sv, &rmap))
                    .collect::<Result<Vec<_>, _>>()
                    .ok()?;
                let sym_mods: Vec<_> = ctx
                    .modules
                    .iter()
                    .map(|md| crate::compiler::symbolic::symbolize_module_decl(md, &rmap))
                    .collect::<Result<Vec<_>, _>>()
                    .ok()?;

                let temp_sizes_vec: Vec<(u32, usize)> =
                    temp_sizes_map.iter().map(|(&k, &v)| (k, v)).collect();

                let dim_lists: Vec<Vec<u16>> = ctx
                    .dim_lists
                    .iter()
                    .map(|(n, arr)| arr[..(*n as usize)].to_vec())
                    .collect();

                Some(PerVarBytecodes {
                    symbolic: sym_bc,
                    graphical_functions: ctx.graphical_functions.clone(),
                    module_decls: sym_mods,
                    static_views: sym_views,
                    temp_sizes: temp_sizes_vec,
                    dim_lists,
                })
            }
            Err(_) => None,
        }
    };

    // LTM vars are always flow-phase only (scalar auxes, not stocks)
    let flow_bytecodes = match build_var(false) {
        Ok(var_result) => compile_phase(&var_result.ast),
        Err(_) => None,
    };

    Some(VarFragmentResult {
        fragment: CompiledVarFragment {
            ident: var_name_canonical,
            initial_bytecodes: None,
            flow_bytecodes,
            stock_bytecodes: None,
        },
    })
}

/// Compile a single implicit variable (PREVIOUS module instance) from an
/// LTM equation to symbolic bytecodes.
///
/// This is analogous to `compile_implicit_var_fragment` but for implicit
/// variables generated by LTM equation parsing rather than by
/// SourceVariable parsing. The parent is an LTM equation (not a
/// SourceVariable), so we reconstruct the parse result from the LTM
/// equation text.
#[allow(clippy::too_many_arguments)]
pub(super) fn compile_ltm_implicit_var_fragment(
    db: &dyn Db,
    parsed: &ParsedVariableResult,
    idx: usize,
    meta: &LtmImplicitVarMeta,
    model: SourceModel,
    project: SourceProject,
    _dep_graph: &ModelDepGraphResult,
    module_input_names: &[String],
) -> Option<VarFragmentResult> {
    use crate::compiler::symbolic::{
        CompiledVarFragment, PerVarBytecodes, ReverseOffsetMap, VariableLayout,
    };

    let implicit_dm_var = parsed.implicit_vars.get(idx)?;
    let implicit_name = canonicalize(implicit_dm_var.get_ident()).into_owned();

    let dims = project_datamodel_dims(db, project);
    let dim_context = crate::dimensions::DimensionsContext::from(dims.as_slice());
    let converted_dims: Vec<crate::dimensions::Dimension> = dims
        .iter()
        .map(crate::dimensions::Dimension::from)
        .collect();

    let units_ctx = project_units_context(db, project);

    let mut dummy_implicits = Vec::new();
    let parsed_implicit = crate::variable::parse_var(
        dims,
        implicit_dm_var,
        &mut dummy_implicits,
        units_ctx,
        |mi| Ok(Some(mi.clone())),
    );

    if parsed_implicit
        .equation_errors()
        .is_some_and(|e| !e.is_empty())
    {
        return None;
    }

    // Module-type implicit vars need direct Module construction
    let lowered = if meta.is_module {
        if let datamodel::Variable::Module(dm_module) = implicit_dm_var {
            let module_inputs: Vec<crate::variable::ModuleInput> = dm_module
                .references
                .iter()
                .filter_map(|mr| {
                    let ident_prefix = format!("{}\u{00B7}", canonicalize(&implicit_name));
                    let src = canonicalize(&mr.src);
                    let dst = canonicalize(&mr.dst);
                    if src.starts_with(&ident_prefix) {
                        return None;
                    }
                    let dst_stripped = dst.strip_prefix(&ident_prefix)?;
                    let src_str = if model.name(db) == "main" && src.starts_with('\u{00B7}') {
                        &src['\u{00B7}'.len_utf8()..]
                    } else {
                        &src
                    };
                    Some(crate::variable::ModuleInput {
                        src: Ident::new(src_str),
                        dst: Ident::new(dst_stripped),
                    })
                })
                .collect();
            crate::variable::Variable::Module {
                ident: Ident::new(&implicit_name),
                model_name: Ident::new(&dm_module.model_name),
                units: None,
                inputs: module_inputs,
                errors: vec![],
                unit_errors: vec![],
            }
        } else {
            return None;
        }
    } else {
        let models = HashMap::new();
        let scope = crate::model::ScopeStage0 {
            models: &models,
            dimensions: &dim_context,
            model_name: "",
        };
        crate::model::lower_variable(&scope, &parsed_implicit)
    };

    let model_name_ident = Ident::new(model.name(db));
    let var_ident_canonical: Ident<Canonical> = Ident::new(&implicit_name);

    // Arena for sub-model stub variables
    let arena = bumpalo::Bump::new();

    let mut mini_metadata: HashMap<Ident<Canonical>, crate::compiler::VariableMetadata<'_>> =
        HashMap::new();
    // LTM implicit vars are in the root model context
    let mut mini_offset = crate::vm::IMPLICIT_VAR_COUNT;

    // Add implicit time/dt/initial_time/final_time
    {
        use std::sync::LazyLock;
        static IMPLICIT_TIME: LazyLock<crate::variable::Variable> =
            LazyLock::new(|| crate::variable::Variable::Var {
                ident: Ident::new("time"),
                ast: None,
                init_ast: None,
                eqn: None,
                units: None,
                tables: vec![],
                non_negative: false,
                is_flow: false,
                is_table_only: false,
                errors: vec![],
                unit_errors: vec![],
            });
        static IMPLICIT_DT: LazyLock<crate::variable::Variable> =
            LazyLock::new(|| crate::variable::Variable::Var {
                ident: Ident::new("dt"),
                ast: None,
                init_ast: None,
                eqn: None,
                units: None,
                tables: vec![],
                non_negative: false,
                is_flow: false,
                is_table_only: false,
                errors: vec![],
                unit_errors: vec![],
            });
        static IMPLICIT_INITIAL_TIME: LazyLock<crate::variable::Variable> =
            LazyLock::new(|| crate::variable::Variable::Var {
                ident: Ident::new("initial_time"),
                ast: None,
                init_ast: None,
                eqn: None,
                units: None,
                tables: vec![],
                non_negative: false,
                is_flow: false,
                is_table_only: false,
                errors: vec![],
                unit_errors: vec![],
            });
        static IMPLICIT_FINAL_TIME: LazyLock<crate::variable::Variable> =
            LazyLock::new(|| crate::variable::Variable::Var {
                ident: Ident::new("final_time"),
                ast: None,
                init_ast: None,
                eqn: None,
                units: None,
                tables: vec![],
                non_negative: false,
                is_flow: false,
                is_table_only: false,
                errors: vec![],
                unit_errors: vec![],
            });
        mini_metadata.insert(
            Ident::new("time"),
            crate::compiler::VariableMetadata {
                offset: 0,
                size: 1,
                var: &IMPLICIT_TIME,
            },
        );
        mini_metadata.insert(
            Ident::new("dt"),
            crate::compiler::VariableMetadata {
                offset: 1,
                size: 1,
                var: &IMPLICIT_DT,
            },
        );
        mini_metadata.insert(
            Ident::new("initial_time"),
            crate::compiler::VariableMetadata {
                offset: 2,
                size: 1,
                var: &IMPLICIT_INITIAL_TIME,
            },
        );
        mini_metadata.insert(
            Ident::new("final_time"),
            crate::compiler::VariableMetadata {
                offset: 3,
                size: 1,
                var: &IMPLICIT_FINAL_TIME,
            },
        );
    }

    let project_models = project.models(db);
    let self_size = meta.size;

    mini_metadata.insert(
        var_ident_canonical.clone(),
        crate::compiler::VariableMetadata {
            offset: mini_offset,
            size: self_size,
            var: &lowered,
        },
    );
    mini_offset += self_size;

    // Collect dependencies from the implicit var itself
    let source_vars = model.variables(db);
    let mut dep_variables: Vec<(Ident<Canonical>, crate::variable::Variable, usize)> = Vec::new();
    let mut module_refs: HashMap<Ident<Canonical>, crate::vm::ModuleKey> = HashMap::new();

    // For module-type implicit vars, build module_refs from the dm_module references
    if meta.is_module
        && let datamodel::Variable::Module(dm_module) = implicit_dm_var
    {
        let input_prefix = format!("{implicit_name}\u{00B7}");
        let input_set: BTreeSet<Ident<Canonical>> = dm_module
            .references
            .iter()
            .filter_map(|mr| {
                let dst_canonical = canonicalize(&mr.dst);
                let bare = dst_canonical.strip_prefix(&input_prefix)?;
                Some(Ident::new(bare))
            })
            .collect();
        module_refs.insert(
            var_ident_canonical.clone(),
            (Ident::new(&dm_module.model_name), input_set),
        );

        // Populate sub-model metadata
        let sub_canonical = canonicalize(&dm_module.model_name);
        if let Some(sub_model) = project_models.get(sub_canonical.as_ref()) {
            build_submodel_metadata(&arena, db, *sub_model, project, &mut {
                let mut all_md: HashMap<
                    Ident<Canonical>,
                    HashMap<Ident<Canonical>, crate::compiler::VariableMetadata<'_>>,
                > = HashMap::new();
                all_md.insert(model_name_ident.clone(), mini_metadata.clone());
                all_md
            });
        }

        // Add dependency stubs for module input sources
        for mr in &dm_module.references {
            let src = canonicalize(&mr.src);
            let effective = src.strip_prefix('\u{00B7}').unwrap_or(&src);
            if effective == implicit_name.as_str()
                || matches!(effective, "time" | "dt" | "initial_time" | "final_time")
            {
                continue;
            }
            if effective.contains('\u{00B7}') {
                continue;
            }
            let dep_ident = Ident::new(effective);
            if mini_metadata.contains_key(&dep_ident)
                || dep_variables.iter().any(|(id, _, _)| id == &dep_ident)
            {
                continue;
            }
            if let Some(dep_sv) = source_vars.get(effective) {
                let dep_dims = variable_dimensions(db, *dep_sv, project);
                let dep_size = variable_size(db, *dep_sv, project);
                let dep_var = build_stub_variable(db, dep_sv, &dep_ident, dep_dims);
                dep_variables.push((dep_ident, dep_var, dep_size));
            } else {
                // Could be another LTM var or implicit var -- scalar stub
                dep_variables.push((
                    dep_ident.clone(),
                    crate::variable::Variable::Var {
                        ident: dep_ident,
                        ast: None,
                        init_ast: None,
                        eqn: None,
                        units: None,
                        tables: vec![],
                        non_negative: false,
                        is_flow: false,
                        is_table_only: false,
                        errors: vec![],
                        unit_errors: vec![],
                    },
                    1,
                ));
            }
        }
    }

    for (dep_ident, dep_var, dep_size) in &dep_variables {
        if !mini_metadata.contains_key(dep_ident) {
            mini_metadata.insert(
                dep_ident.clone(),
                crate::compiler::VariableMetadata {
                    offset: mini_offset,
                    size: *dep_size,
                    var: dep_var,
                },
            );
            mini_offset += dep_size;
        }
    }

    let mut all_metadata: HashMap<
        Ident<Canonical>,
        HashMap<Ident<Canonical>, crate::compiler::VariableMetadata<'_>>,
    > = HashMap::new();
    all_metadata.insert(model_name_ident.clone(), mini_metadata);

    // Build sub-model metadata for module-type implicit vars
    if meta.is_module
        && let Some(model_name) = &meta.model_name
    {
        let sub_canonical = canonicalize(model_name);
        if let Some(sub_model) = project_models.get(sub_canonical.as_ref()) {
            build_submodel_metadata(&arena, db, *sub_model, project, &mut all_metadata);
        }
    }

    let mini_layout =
        crate::compiler::symbolic::layout_from_metadata(&all_metadata, &model_name_ident)
            .unwrap_or_else(|_| VariableLayout::new(HashMap::new(), 0));
    let rmap = ReverseOffsetMap::from_layout(&mini_layout);

    let tables: HashMap<Ident<Canonical>, Vec<crate::compiler::Table>> = HashMap::new();
    let inputs = canonical_module_input_set(module_input_names);
    let module_models = model_module_map(db, model, project).clone();

    let core = crate::compiler::ContextCore {
        dimensions: &converted_dims,
        dimensions_ctx: &dim_context,
        model_name: &model_name_ident,
        metadata: &all_metadata,
        module_models: &module_models,
        inputs: &inputs,
    };

    let build_var = |is_initial: bool| {
        crate::compiler::Var::new(
            &crate::compiler::Context::new(core, &var_ident_canonical, is_initial),
            &lowered,
        )
    };

    let compile_phase = |exprs: &[crate::compiler::Expr]| -> Option<PerVarBytecodes> {
        if exprs.is_empty() {
            return None;
        }

        let module_inputs_set: HashSet<Ident<Canonical>> = inputs.iter().cloned().collect();
        let module = crate::compiler::Module {
            ident: model_name_ident.clone(),
            inputs: module_inputs_set,
            n_slots: mini_offset,
            n_temps: 0,
            temp_sizes: vec![],
            runlist_initials: vec![],
            runlist_initials_by_var: vec![],
            runlist_flows: exprs.to_vec(),
            runlist_stocks: vec![],
            offsets: all_metadata
                .iter()
                .map(|(k, v)| {
                    (
                        k.clone(),
                        v.iter()
                            .map(|(vk, vm)| (vk.clone(), (vm.offset, vm.size)))
                            .collect(),
                    )
                })
                .collect(),
            runlist_order: vec![var_ident_canonical.clone()],
            tables: tables.clone(),
            dimensions: converted_dims.clone(),
            dimensions_ctx: dim_context.clone(),
            module_refs: module_refs.clone(),
        };

        let mut temp_sizes_map: HashMap<u32, usize> = HashMap::new();
        for expr in exprs {
            crate::compiler::extract_temp_sizes_pub(expr, &mut temp_sizes_map);
        }
        let n_temps = temp_sizes_map.len();
        let mut temp_sizes: Vec<usize> = vec![0; n_temps];
        for (id, size) in &temp_sizes_map {
            if (*id as usize) < temp_sizes.len() {
                temp_sizes[*id as usize] = *size;
            }
        }

        let module = crate::compiler::Module {
            n_temps,
            temp_sizes: temp_sizes.clone(),
            ..module
        };

        match module.compile() {
            Ok(compiled) => {
                let sym_bc =
                    crate::compiler::symbolic::symbolize_bytecode(&compiled.compiled_flows, &rmap)
                        .ok()?;

                let ctx = &*compiled.context;
                let sym_views: Vec<_> = ctx
                    .static_views
                    .iter()
                    .map(|sv| crate::compiler::symbolic::symbolize_static_view(sv, &rmap))
                    .collect::<Result<Vec<_>, _>>()
                    .ok()?;
                let sym_mods: Vec<_> = ctx
                    .modules
                    .iter()
                    .map(|md| crate::compiler::symbolic::symbolize_module_decl(md, &rmap))
                    .collect::<Result<Vec<_>, _>>()
                    .ok()?;

                let temp_sizes_vec: Vec<(u32, usize)> =
                    temp_sizes_map.iter().map(|(&k, &v)| (k, v)).collect();

                let dim_lists: Vec<Vec<u16>> = ctx
                    .dim_lists
                    .iter()
                    .map(|(n, arr)| arr[..(*n as usize)].to_vec())
                    .collect();

                Some(PerVarBytecodes {
                    symbolic: sym_bc,
                    graphical_functions: ctx.graphical_functions.clone(),
                    module_decls: sym_mods,
                    static_views: sym_views,
                    temp_sizes: temp_sizes_vec,
                    dim_lists,
                })
            }
            Err(_) => None,
        }
    };

    // PREVIOUS modules participate in initials (stock init) and stocks
    // (stock update) phases. The dep_graph won't have LTM implicit vars
    // in its runlists since they are not part of the original model.
    // We compile all available phases.
    let initial_bytecodes = match build_var(true) {
        Ok(var_result) => compile_phase(&var_result.ast),
        Err(_) => None,
    };

    let flow_bytecodes = if !meta.is_stock {
        match build_var(false) {
            Ok(var_result) => compile_phase(&var_result.ast),
            Err(_) => None,
        }
    } else {
        None
    };

    let stock_bytecodes = if meta.is_stock || meta.is_module {
        match build_var(false) {
            Ok(var_result) => compile_phase(&var_result.ast),
            Err(_) => None,
        }
    } else {
        None
    };

    Some(VarFragmentResult {
        fragment: CompiledVarFragment {
            ident: implicit_name,
            initial_bytecodes,
            flow_bytecodes,
            stock_bytecodes,
        },
    })
}
