// Copyright 2026 The Simlin Authors. All rights reserved.
// Use of this source code is governed by the Apache License,
// Version 2.0, that can be found in the LICENSE file.

//! LTM (Loops That Matter) equation parsing and compilation.
//!
//! This module contains the per-equation compilation pipeline for LTM
//! synthetic variables: link scores, loop scores, and relative loop
//! scores. It handles intrinsic PREVIOUS helper rewrites plus other
//! implicit variables produced during parsing, and produces symbolic
//! bytecodes for assembly by `assemble_module`.

use std::collections::{BTreeSet, HashMap, HashSet};

use crate::canonicalize;
use crate::common::{Canonical, Ident};
use crate::datamodel;

use super::{
    Db, LtmLinkId, ModelDepGraphResult, ParsedVariableResult, SourceModel, SourceProject,
    SourceVariableKind, VarFragmentResult, build_module_inputs, build_stub_variable,
    build_submodel_metadata, canonical_module_input_set, compute_layout, link_score_equation_text,
    model_implicit_var_info, model_module_ident_context, model_module_map,
    parse_source_variable_with_module_context, project_datamodel_dims, project_units_context,
    variable_dimensions, variable_size,
};

pub(super) fn ltm_module_idents(
    db: &dyn Db,
    model: SourceModel,
    project: SourceProject,
) -> HashSet<Ident<Canonical>> {
    let source_vars = model.variables(db);
    let mut module_idents: HashSet<Ident<Canonical>> = source_vars
        .iter()
        .filter_map(|(name, source_var)| {
            if source_var.kind(db) == SourceVariableKind::Module {
                Some(Ident::new(name))
            } else {
                None
            }
        })
        .collect();

    for (name, meta) in model_implicit_var_info(db, model, project).iter() {
        if meta.is_module {
            module_idents.insert(Ident::new(name));
        }
    }

    module_idents
}

/// Parse an LTM synthetic variable's equation string.
///
/// Creates a transient `datamodel::Variable::Aux`, runs it through
/// `parse_var` (which invokes `BuiltinVisitor` and
/// `instantiate_implicit_modules`), and returns the parsed variable plus
/// any implicit helper/module variables generated while parsing.
///
/// When `var_dimensions` is non-empty, the equation is wrapped in
/// `Equation::ApplyToAll` so the compiler expands it across all
/// dimension elements. When empty, the equation is scalar (original
/// behavior).
pub(super) fn parse_ltm_equation(
    var_name: &str,
    equation: &str,
    var_dimensions: &[String],
    dims: &[datamodel::Dimension],
    units_ctx: &crate::units::Context,
    module_idents: Option<&HashSet<Ident<Canonical>>>,
) -> ParsedVariableResult {
    let eqn = if var_dimensions.is_empty() {
        datamodel::Equation::Scalar(equation.to_string())
    } else {
        datamodel::Equation::ApplyToAll(var_dimensions.to_vec(), equation.to_string())
    };
    let dm_var = datamodel::Variable::Aux(datamodel::Aux {
        ident: canonicalize(var_name).into_owned(),
        equation: eqn,
        documentation: String::new(),
        units: None,
        gf: None,
        ai_state: None,
        uid: None,
        compat: datamodel::Compat::default(),
    });

    let mut implicit_vars = Vec::new();
    let variable = crate::variable::parse_var_with_module_context(
        dims,
        &dm_var,
        &mut implicit_vars,
        units_ctx,
        |mi| Ok(Some(mi.clone())),
        module_idents,
    );

    ParsedVariableResult {
        variable,
        implicit_vars,
    }
}

pub(super) fn parse_ltm_equation_for_model_with_ids(
    db: &dyn Db,
    var_name: &str,
    equation: &str,
    var_dimensions: &[String],
    project: SourceProject,
    module_idents: &HashSet<Ident<Canonical>>,
) -> ParsedVariableResult {
    let dims = project_datamodel_dims(db, project);
    let units_ctx = project_units_context(db, project);
    parse_ltm_equation(
        var_name,
        equation,
        var_dimensions,
        dims,
        units_ctx,
        Some(module_idents),
    )
}

pub(super) fn parse_ltm_var_with_ids(
    db: &dyn Db,
    ltm_var: &super::LtmSyntheticVar,
    project: SourceProject,
    module_idents: &HashSet<Ident<Canonical>>,
) -> ParsedVariableResult {
    parse_ltm_equation_for_model_with_ids(
        db,
        &ltm_var.name,
        &ltm_var.equation,
        &ltm_var.dimensions,
        project,
        module_idents,
    )
}

/// Metadata about implicit variables generated by LTM equation parsing.
///
/// LTM equations may synthesize helper auxes for intrinsic PREVIOUS/INIT
/// routing and may also expand stdlib module calls such as SMOOTH/DELAY.
/// This structure collects those implicit variables across all LTM
/// equations in a model so that `compute_layout` can allocate slots and
/// `assemble_module` can compile them.
#[derive(Clone, Debug, PartialEq, Eq, salsa::Update)]
pub struct LtmImplicitVarMeta {
    /// Canonical name of the LTM variable that created this implicit var
    pub ltm_parent_name: String,
    /// Index into the parent's implicit_vars list
    pub index_in_parent: usize,
    /// Whether this implicit var is a stock
    pub is_stock: bool,
    /// Whether this implicit var is a module
    pub is_module: bool,
    /// Sub-model name if is_module is true
    pub model_name: Option<String>,
    /// Size in slots (for scalar vars: 1; for modules: sub-model n_slots)
    pub size: usize,
}

/// Cached implicit variable info for all LTM synthetic variables.
///
/// Parses each LTM equation to discover implicit helper/module variables,
/// caching the results. Both `compute_layout` and `assemble_module` read
/// this to allocate slots and compile fragments for those implicit vars
/// within LTM equations.
#[salsa::tracked(returns(ref))]
pub fn model_ltm_implicit_var_info(
    db: &dyn Db,
    model: SourceModel,
    project: SourceProject,
) -> HashMap<String, LtmImplicitVarMeta> {
    if !project.ltm_enabled(db) {
        return HashMap::new();
    }

    let ltm_vars = model_ltm_variables(db, model, project);

    let dims = project_datamodel_dims(db, project);
    let units_ctx = project_units_context(db, project);
    let module_idents = ltm_module_idents(db, model, project);

    let mut result = HashMap::new();

    for ltm_var in &ltm_vars.vars {
        let parsed = parse_ltm_equation(
            &ltm_var.name,
            &ltm_var.equation,
            &ltm_var.dimensions,
            dims,
            units_ctx,
            Some(&module_idents),
        );

        let project_models = project.models(db);

        for (idx, implicit_dm_var) in parsed.implicit_vars.iter().enumerate() {
            let im_name = canonicalize(implicit_dm_var.get_ident()).into_owned();
            let is_module = matches!(implicit_dm_var, datamodel::Variable::Module(_));
            let is_stock = matches!(implicit_dm_var, datamodel::Variable::Stock(_));
            let model_name = if let datamodel::Variable::Module(m) = implicit_dm_var {
                Some(m.model_name.clone())
            } else {
                None
            };
            let size = if is_module {
                model_name
                    .as_deref()
                    .and_then(|mn| {
                        let sub_canonical = canonicalize(mn);
                        project_models
                            .get(sub_canonical.as_ref())
                            .map(|sm| compute_layout(db, *sm, project, false).n_slots)
                    })
                    .unwrap_or(1)
            } else {
                1
            };

            result.insert(
                im_name,
                LtmImplicitVarMeta {
                    ltm_parent_name: ltm_var.name.clone(),
                    index_in_parent: idx,
                    is_stock,
                    is_module,
                    model_name,
                    size,
                },
            );
        }
    }

    result
}

/// Compile a single LTM synthetic variable's equation to symbolic
/// bytecodes.
///
/// This is the per-link compilation granularity that enables incremental
/// recomputation: when a variable's equation changes, salsa only
/// recompiles fragments for affected links. Equation edits that don't
/// change the dependency set return their cached fragment (AC1.2).
///
/// LTM equations are pure scalar aux equations that may reference:
/// - Model variables (stocks, flows, auxes) from the parent model
/// - Other LTM variables (loop scores referencing link scores)
/// - Implicit helper/module variables created during parsing
/// - Implicit time/dt/initial_time/final_time variables
///
/// Parsed LTM equations may synthesize helper auxes for PREVIOUS/INIT
/// and may also expand stdlib module calls, so those implicit vars need
/// to be handled the same way as in `compile_var_fragment`.
#[salsa::tracked(returns(ref))]
pub fn compile_ltm_var_fragment(
    db: &dyn Db,
    link_id: LtmLinkId<'_>,
    model: SourceModel,
    project: SourceProject,
) -> Option<VarFragmentResult> {
    let lsv = link_score_equation_text(db, link_id, model, project).as_ref()?;

    compile_ltm_equation_fragment(db, &lsv.name, &lsv.equation, model, project)
}

/// Compile an arbitrary LTM equation string to symbolic bytecodes.
///
/// Shared implementation used by `compile_ltm_var_fragment` (link scores)
/// and the loop/relative score compilation in `assemble_module`. Builds
/// a mini-context that includes both model variables and implicit vars
/// synthesized while parsing the LTM equation.
pub(super) fn compile_ltm_equation_fragment(
    db: &dyn Db,
    var_name: &str,
    equation: &str,
    model: SourceModel,
    project: SourceProject,
) -> Option<VarFragmentResult> {
    use crate::compiler::symbolic::{
        CompiledVarFragment, PerVarBytecodes, ReverseOffsetMap, VariableLayout,
    };

    let dims = project_datamodel_dims(db, project);
    let dim_context = crate::dimensions::DimensionsContext::from(dims.as_slice());
    let converted_dims: Vec<crate::dimensions::Dimension> = dims
        .iter()
        .map(crate::dimensions::Dimension::from)
        .collect();

    let units_ctx = project_units_context(db, project);
    let module_idents = ltm_module_idents(db, model, project);

    let parsed = parse_ltm_equation(
        var_name,
        equation,
        &[],
        dims,
        units_ctx,
        Some(&module_idents),
    );

    // Check for parse errors
    if parsed
        .variable
        .equation_errors()
        .is_some_and(|e| !e.is_empty())
    {
        return None;
    }

    // Lower the variable. LTM vars are always scalar auxes.
    let models = HashMap::new();
    let scope = crate::model::ScopeStage0 {
        models: &models,
        dimensions: &dim_context,
        model_name: "",
    };
    let lowered = crate::model::lower_variable(&scope, &parsed.variable);

    let model_name_ident = Ident::new(model.name(db));
    let var_name_canonical = canonicalize(var_name).into_owned();
    let var_ident_canonical: Ident<Canonical> = Ident::new(&var_name_canonical);

    // Arena for sub-model stub variables allocated by build_submodel_metadata
    let arena = bumpalo::Bump::new();

    let mut mini_metadata: HashMap<Ident<Canonical>, crate::compiler::VariableMetadata<'_>> =
        HashMap::new();

    // Mini-layout starts after the 4 implicit time vars (time, dt, initial_time, final_time)
    let mut mini_offset = crate::vm::IMPLICIT_VAR_COUNT;

    // Add implicit time/dt/initial_time/final_time variables
    {
        use std::sync::LazyLock;
        static IMPLICIT_TIME: LazyLock<crate::variable::Variable> =
            LazyLock::new(|| crate::variable::Variable::Var {
                ident: Ident::new("time"),
                ast: None,
                init_ast: None,
                eqn: None,
                units: None,
                tables: vec![],
                non_negative: false,
                is_flow: false,
                is_table_only: false,
                errors: vec![],
                unit_errors: vec![],
            });
        static IMPLICIT_DT: LazyLock<crate::variable::Variable> =
            LazyLock::new(|| crate::variable::Variable::Var {
                ident: Ident::new("dt"),
                ast: None,
                init_ast: None,
                eqn: None,
                units: None,
                tables: vec![],
                non_negative: false,
                is_flow: false,
                is_table_only: false,
                errors: vec![],
                unit_errors: vec![],
            });
        static IMPLICIT_INITIAL_TIME: LazyLock<crate::variable::Variable> =
            LazyLock::new(|| crate::variable::Variable::Var {
                ident: Ident::new("initial_time"),
                ast: None,
                init_ast: None,
                eqn: None,
                units: None,
                tables: vec![],
                non_negative: false,
                is_flow: false,
                is_table_only: false,
                errors: vec![],
                unit_errors: vec![],
            });
        static IMPLICIT_FINAL_TIME: LazyLock<crate::variable::Variable> =
            LazyLock::new(|| crate::variable::Variable::Var {
                ident: Ident::new("final_time"),
                ast: None,
                init_ast: None,
                eqn: None,
                units: None,
                tables: vec![],
                non_negative: false,
                is_flow: false,
                is_table_only: false,
                errors: vec![],
                unit_errors: vec![],
            });
        mini_metadata.insert(
            Ident::new("time"),
            crate::compiler::VariableMetadata {
                offset: 0,
                size: 1,
                var: &IMPLICIT_TIME,
            },
        );
        mini_metadata.insert(
            Ident::new("dt"),
            crate::compiler::VariableMetadata {
                offset: 1,
                size: 1,
                var: &IMPLICIT_DT,
            },
        );
        mini_metadata.insert(
            Ident::new("initial_time"),
            crate::compiler::VariableMetadata {
                offset: 2,
                size: 1,
                var: &IMPLICIT_INITIAL_TIME,
            },
        );
        mini_metadata.insert(
            Ident::new("final_time"),
            crate::compiler::VariableMetadata {
                offset: 3,
                size: 1,
                var: &IMPLICIT_FINAL_TIME,
            },
        );
    }

    // Add self (the LTM var itself)
    mini_metadata.insert(
        var_ident_canonical.clone(),
        crate::compiler::VariableMetadata {
            offset: mini_offset,
            size: 1,
            var: &lowered,
        },
    );
    mini_offset += 1;

    // Collect dependency variable names from the lowered AST
    let dep_idents = if let Some(ast) = lowered.ast() {
        crate::variable::identifier_set(ast, &[], None)
    } else {
        HashSet::new()
    };

    let source_vars = model.variables(db);
    let project_models = project.models(db);
    let implicit_info = model_implicit_var_info(db, model, project);
    let ltm_implicit_info = model_ltm_implicit_var_info(db, model, project);

    let mut dep_variables: Vec<(Ident<Canonical>, crate::variable::Variable, usize)> = Vec::new();
    let mut implicit_module_vars: Vec<(Ident<Canonical>, crate::variable::Variable, usize)> =
        Vec::new();
    let mut implicit_module_refs: HashMap<Ident<Canonical>, crate::vm::ModuleKey> = HashMap::new();
    let mut implicit_submodels: Vec<(String, SourceModel)> = Vec::new();

    // Process dependencies from the parsed AST
    for dep_ident_str in &dep_idents {
        let dep_str = dep_ident_str.as_str();
        let effective = dep_str.strip_prefix('\u{00B7}').unwrap_or(dep_str);

        if effective == var_name_canonical
            || matches!(effective, "time" | "dt" | "initial_time" | "final_time")
        {
            continue;
        }

        // Handle module output references (contains middle dot)
        if let Some(dot_pos) = effective.find('\u{00B7}') {
            let module_var_name = &effective[..dot_pos];
            let module_ident: Ident<Canonical> = Ident::new(module_var_name);

            if mini_metadata.contains_key(&module_ident)
                || implicit_module_vars
                    .iter()
                    .any(|(id, _, _)| id == &module_ident)
            {
                continue;
            }

            // Check if this is an explicit model variable (module type)
            if let Some(mod_source_var) = source_vars.get(module_var_name) {
                if mod_source_var.kind(db) == SourceVariableKind::Module {
                    let mod_model_name = mod_source_var.model_name(db);
                    let sub_canonical = canonicalize(mod_model_name);
                    let sub_size = project_models
                        .get(sub_canonical.as_ref())
                        .map(|sm| compute_layout(db, *sm, project, false).n_slots)
                        .unwrap_or(1);

                    let mod_input_prefix = format!("{module_var_name}\u{00B7}");
                    let module_inputs = build_module_inputs(
                        model.name(db),
                        &mod_input_prefix,
                        mod_source_var
                            .module_refs(db)
                            .iter()
                            .map(|mr| (canonicalize(&mr.src), canonicalize(&mr.dst))),
                    );

                    let mod_var = crate::variable::Variable::Module {
                        ident: module_ident.clone(),
                        model_name: Ident::new(mod_model_name),
                        units: None,
                        inputs: module_inputs.clone(),
                        errors: vec![],
                        unit_errors: vec![],
                    };
                    dep_variables.push((module_ident.clone(), mod_var, sub_size));

                    let input_set: BTreeSet<Ident<Canonical>> =
                        module_inputs.iter().map(|mi| mi.dst.clone()).collect();
                    implicit_module_refs
                        .insert(module_ident, (Ident::new(mod_model_name), input_set));

                    if let Some(sub_model) = project_models.get(sub_canonical.as_ref()) {
                        implicit_submodels.push((mod_model_name.to_string(), *sub_model));
                    }
                }
                continue;
            }

            // Check if this is an implicit var from the LTM equation's own
            // parse-time helper/module synthesis.
            let mut found_in_parsed = false;
            for implicit_dm_var in &parsed.implicit_vars {
                if let datamodel::Variable::Module(dm_module) = implicit_dm_var
                    && canonicalize(&dm_module.ident) == module_var_name
                {
                    let sub_canonical = canonicalize(&dm_module.model_name);
                    let sub_size = project_models
                        .get(sub_canonical.as_ref())
                        .map(|sm| compute_layout(db, *sm, project, false).n_slots)
                        .unwrap_or(1);

                    let input_prefix = format!("{module_var_name}\u{00B7}");
                    let module_inputs = build_module_inputs(
                        model.name(db),
                        &input_prefix,
                        dm_module
                            .references
                            .iter()
                            .map(|mr| (canonicalize(&mr.src), canonicalize(&mr.dst))),
                    );

                    let im_var = crate::variable::Variable::Module {
                        ident: module_ident.clone(),
                        model_name: Ident::new(&dm_module.model_name),
                        units: None,
                        inputs: module_inputs.clone(),
                        errors: vec![],
                        unit_errors: vec![],
                    };
                    implicit_module_vars.push((module_ident.clone(), im_var, sub_size));

                    let input_set: BTreeSet<Ident<Canonical>> =
                        module_inputs.iter().map(|mi| mi.dst.clone()).collect();
                    implicit_module_refs.insert(
                        module_ident.clone(),
                        (Ident::new(&dm_module.model_name), input_set),
                    );

                    if let Some(sub_model) = project_models.get(sub_canonical.as_ref()) {
                        implicit_submodels.push((dm_module.model_name.clone(), *sub_model));
                    }

                    found_in_parsed = true;
                    break;
                }
            }

            if !found_in_parsed {
                // Check the model's own implicit vars (SMOOTH, DELAY, etc.)
                if let Some(im_meta) = implicit_info.get(module_var_name)
                    && im_meta.is_module
                    && let Some(im_model_name) = im_meta.model_name.as_deref()
                {
                    let sub_canonical = canonicalize(im_model_name);
                    let sub_size = project_models
                        .get(sub_canonical.as_ref())
                        .map(|sm| compute_layout(db, *sm, project, false).n_slots)
                        .unwrap_or(1);

                    let module_ctx = model_module_ident_context(db, model, vec![]);
                    let parent_parsed = parse_source_variable_with_module_context(
                        db,
                        im_meta.parent_source_var,
                        project,
                        module_ctx,
                    );
                    let input_prefix = format!("{module_var_name}\u{00B7}");
                    let module_inputs = parent_parsed
                        .implicit_vars
                        .iter()
                        .find_map(|iv| match iv {
                            datamodel::Variable::Module(dm_module)
                                if canonicalize(dm_module.ident.as_str()) == module_var_name =>
                            {
                                Some(build_module_inputs(
                                    model.name(db),
                                    &input_prefix,
                                    dm_module
                                        .references
                                        .iter()
                                        .map(|mr| (canonicalize(&mr.src), canonicalize(&mr.dst))),
                                ))
                            }
                            _ => None,
                        })
                        .unwrap_or_default();

                    let mod_var = crate::variable::Variable::Module {
                        ident: module_ident.clone(),
                        model_name: Ident::new(im_model_name),
                        units: None,
                        inputs: module_inputs.clone(),
                        errors: vec![],
                        unit_errors: vec![],
                    };
                    dep_variables.push((module_ident.clone(), mod_var, sub_size));

                    let input_set: BTreeSet<Ident<Canonical>> =
                        module_inputs.iter().map(|mi| mi.dst.clone()).collect();
                    implicit_module_refs
                        .insert(module_ident, (Ident::new(im_model_name), input_set));

                    if let Some(sub_model) = project_models.get(sub_canonical.as_ref()) {
                        implicit_submodels.push((im_model_name.to_string(), *sub_model));
                    }
                }
                // Also check LTM implicit vars from other LTM equations
                else if let Some(ltm_im_meta) = ltm_implicit_info.get(module_var_name)
                    && ltm_im_meta.is_module
                    && let Some(im_model_name) = ltm_im_meta.model_name.as_deref()
                {
                    let sub_canonical = canonicalize(im_model_name);
                    let sub_size = project_models
                        .get(sub_canonical.as_ref())
                        .map(|sm| compute_layout(db, *sm, project, false).n_slots)
                        .unwrap_or(1);

                    // Parse the parent LTM equation to get implicit var references
                    let parent_ltm_vars = model_ltm_variables(db, model, project);
                    let parent_ltm = parent_ltm_vars
                        .vars
                        .iter()
                        .find(|v| v.name == ltm_im_meta.ltm_parent_name);
                    let module_inputs = if let Some(parent_lsv) = parent_ltm {
                        let parent_parsed = parse_ltm_equation(
                            &parent_lsv.name,
                            &parent_lsv.equation,
                            &parent_lsv.dimensions,
                            dims,
                            units_ctx,
                            Some(&module_idents),
                        );
                        let input_prefix = format!("{module_var_name}\u{00B7}");
                        parent_parsed
                            .implicit_vars
                            .iter()
                            .find_map(|iv| match iv {
                                datamodel::Variable::Module(dm_module)
                                    if canonicalize(dm_module.ident.as_str())
                                        == module_var_name =>
                                {
                                    Some(build_module_inputs(
                                        model.name(db),
                                        &input_prefix,
                                        dm_module.references.iter().map(|mr| {
                                            (canonicalize(&mr.src), canonicalize(&mr.dst))
                                        }),
                                    ))
                                }
                                _ => None,
                            })
                            .unwrap_or_default()
                    } else {
                        Vec::new()
                    };

                    let mod_var = crate::variable::Variable::Module {
                        ident: module_ident.clone(),
                        model_name: Ident::new(im_model_name),
                        units: None,
                        inputs: module_inputs.clone(),
                        errors: vec![],
                        unit_errors: vec![],
                    };
                    dep_variables.push((module_ident.clone(), mod_var, sub_size));

                    let input_set: BTreeSet<Ident<Canonical>> =
                        module_inputs.iter().map(|mi| mi.dst.clone()).collect();
                    implicit_module_refs
                        .insert(module_ident, (Ident::new(im_model_name), input_set));

                    if let Some(sub_model) = project_models.get(sub_canonical.as_ref()) {
                        implicit_submodels.push((im_model_name.to_string(), *sub_model));
                    }
                }
            }
            continue;
        }

        let dep_ident = Ident::new(effective);
        if mini_metadata.contains_key(&dep_ident) {
            continue;
        }

        // Look up in explicit model variables
        if let Some(dep_source_var) = source_vars.get(effective) {
            let dep_dims = variable_dimensions(db, *dep_source_var, project);
            let dep_size = variable_size(db, *dep_source_var, project);
            let dep_var = build_stub_variable(db, dep_source_var, &dep_ident, dep_dims);
            dep_variables.push((dep_ident, dep_var, dep_size));
        } else if let Some(im_meta) = implicit_info.get(effective) {
            // Dep is an implicit var from the model (SMOOTH/DELAY expansion).
            // Module-type implicits need their full size and Module variant so
            // the compiler can resolve submodel offset lookups. Scalar implicits
            // (helper auxes) use a plain Var stub.
            if im_meta.is_module
                && let Some(ref mn) = im_meta.model_name
            {
                let sub_size = {
                    let sub_canonical = canonicalize(mn);
                    project_models
                        .get(sub_canonical.as_ref())
                        .map(|sm| compute_layout(db, *sm, project, false).n_slots)
                        .unwrap_or(1)
                };
                dep_variables.push((
                    dep_ident.clone(),
                    crate::variable::Variable::Module {
                        ident: dep_ident.clone(),
                        model_name: Ident::new(mn),
                        units: None,
                        inputs: vec![],
                        errors: vec![],
                        unit_errors: vec![],
                    },
                    sub_size,
                ));
                implicit_module_refs.insert(dep_ident, (Ident::new(mn), BTreeSet::new()));
                let sub_canonical = canonicalize(mn);
                if let Some(sub_model) = project_models.get(sub_canonical.as_ref()) {
                    implicit_submodels.push((mn.to_string(), *sub_model));
                }
            } else {
                dep_variables.push((
                    dep_ident.clone(),
                    crate::variable::Variable::Var {
                        ident: dep_ident,
                        ast: None,
                        init_ast: None,
                        eqn: None,
                        units: None,
                        tables: vec![],
                        non_negative: false,
                        is_flow: false,
                        is_table_only: false,
                        errors: vec![],
                        unit_errors: vec![],
                    },
                    im_meta.size,
                ));
            }
        }
        // Dep could also be another LTM var (e.g., loop score refs link scores)
        // These are scalar auxes with 1 slot.
        else {
            dep_variables.push((
                dep_ident.clone(),
                crate::variable::Variable::Var {
                    ident: dep_ident,
                    ast: None,
                    init_ast: None,
                    eqn: None,
                    units: None,
                    tables: vec![],
                    non_negative: false,
                    is_flow: false,
                    is_table_only: false,
                    errors: vec![],
                    unit_errors: vec![],
                },
                1,
            ));
        }
    }

    // Add dep metadata
    for (dep_ident, dep_var, dep_size) in &dep_variables {
        if !mini_metadata.contains_key(dep_ident) {
            mini_metadata.insert(
                dep_ident.clone(),
                crate::compiler::VariableMetadata {
                    offset: mini_offset,
                    size: *dep_size,
                    var: dep_var,
                },
            );
            mini_offset += dep_size;
        }
    }

    // Add implicit vars synthesized while parsing the LTM equation
    for (im_ident, im_var, im_size) in &implicit_module_vars {
        if !mini_metadata.contains_key(im_ident) {
            mini_metadata.insert(
                im_ident.clone(),
                crate::compiler::VariableMetadata {
                    offset: mini_offset,
                    size: *im_size,
                    var: im_var,
                },
            );
            mini_offset += im_size;
        }
    }

    // Build the all_metadata map
    let mut all_metadata: HashMap<
        Ident<Canonical>,
        HashMap<Ident<Canonical>, crate::compiler::VariableMetadata<'_>>,
    > = HashMap::new();
    all_metadata.insert(model_name_ident.clone(), mini_metadata);

    // Populate sub-model metadata for implicit module sub-models
    for (_sub_name, sub_model) in &implicit_submodels {
        build_submodel_metadata(&arena, db, *sub_model, project, &mut all_metadata);
    }

    let mini_layout =
        crate::compiler::symbolic::layout_from_metadata(&all_metadata, &model_name_ident)
            .unwrap_or_else(|_| VariableLayout::new(HashMap::new(), 0));
    let rmap = ReverseOffsetMap::from_layout(&mini_layout);

    // LTM vars don't have graphical functions or lookup tables
    let tables: HashMap<Ident<Canonical>, Vec<crate::compiler::Table>> = HashMap::new();

    let inputs = BTreeSet::new();
    let mut module_models = model_module_map(db, model, project).clone();

    // Merge LTM implicit module references from LTM equation parsing into the
    // module_models map so the compiler context can resolve module_var_name ->
    // sub_model_name lookups.
    if !implicit_module_refs.is_empty() {
        let current_model_modules = module_models.entry(model_name_ident.clone()).or_default();
        for (var_ident, (sub_model_name, _input_set)) in &implicit_module_refs {
            current_model_modules.insert(var_ident.clone(), sub_model_name.clone());
        }
    }

    let core = crate::compiler::ContextCore {
        dimensions: &converted_dims,
        dimensions_ctx: &dim_context,
        model_name: &model_name_ident,
        metadata: &all_metadata,
        module_models: &module_models,
        inputs: &inputs,
    };

    let build_var = |is_initial: bool| {
        crate::compiler::Var::new(
            &crate::compiler::Context::new(core, &var_ident_canonical, is_initial),
            &lowered,
        )
    };

    let compile_phase = |exprs: &[crate::compiler::Expr]| -> Option<PerVarBytecodes> {
        if exprs.is_empty() {
            return None;
        }

        let module_inputs_set: HashSet<Ident<Canonical>> = inputs.iter().cloned().collect();
        let module = crate::compiler::Module {
            ident: model_name_ident.clone(),
            inputs: module_inputs_set,
            n_slots: mini_offset,
            n_temps: 0,
            temp_sizes: vec![],
            runlist_initials: vec![],
            runlist_initials_by_var: vec![],
            runlist_flows: exprs.to_vec(),
            runlist_stocks: vec![],
            offsets: all_metadata
                .iter()
                .map(|(k, v)| {
                    (
                        k.clone(),
                        v.iter()
                            .map(|(vk, vm)| (vk.clone(), (vm.offset, vm.size)))
                            .collect(),
                    )
                })
                .collect(),
            runlist_order: vec![var_ident_canonical.clone()],
            tables: tables.clone(),
            dimensions: converted_dims.clone(),
            dimensions_ctx: dim_context.clone(),
            module_refs: implicit_module_refs.clone(),
        };

        let mut temp_sizes_map: HashMap<u32, usize> = HashMap::new();
        for expr in exprs {
            crate::compiler::extract_temp_sizes_pub(expr, &mut temp_sizes_map);
        }
        let n_temps = temp_sizes_map.len();
        let mut temp_sizes: Vec<usize> = vec![0; n_temps];
        for (id, size) in &temp_sizes_map {
            if (*id as usize) < temp_sizes.len() {
                temp_sizes[*id as usize] = *size;
            }
        }

        let module = crate::compiler::Module {
            n_temps,
            temp_sizes: temp_sizes.clone(),
            ..module
        };

        match module.compile() {
            Ok(compiled) => {
                let sym_bc =
                    crate::compiler::symbolic::symbolize_bytecode(&compiled.compiled_flows, &rmap)
                        .ok()?;

                let ctx = &*compiled.context;
                let sym_views: Vec<_> = ctx
                    .static_views
                    .iter()
                    .map(|sv| crate::compiler::symbolic::symbolize_static_view(sv, &rmap))
                    .collect::<Result<Vec<_>, _>>()
                    .ok()?;
                let sym_mods: Vec<_> = ctx
                    .modules
                    .iter()
                    .map(|md| crate::compiler::symbolic::symbolize_module_decl(md, &rmap))
                    .collect::<Result<Vec<_>, _>>()
                    .ok()?;

                let temp_sizes_vec: Vec<(u32, usize)> =
                    temp_sizes_map.iter().map(|(&k, &v)| (k, v)).collect();

                let dim_lists: Vec<Vec<u16>> = ctx
                    .dim_lists
                    .iter()
                    .map(|(n, arr)| arr[..(*n as usize)].to_vec())
                    .collect();

                Some(PerVarBytecodes {
                    symbolic: sym_bc,
                    graphical_functions: ctx.graphical_functions.clone(),
                    module_decls: sym_mods,
                    static_views: sym_views,
                    temp_sizes: temp_sizes_vec,
                    dim_lists,
                })
            }
            Err(_) => None,
        }
    };

    // LTM vars are always flow-phase only (scalar auxes, not stocks)
    let flow_bytecodes = match build_var(false) {
        Ok(var_result) => compile_phase(&var_result.ast),
        Err(_) => None,
    };

    Some(VarFragmentResult {
        fragment: CompiledVarFragment {
            ident: var_name_canonical,
            initial_bytecodes: None,
            flow_bytecodes,
            stock_bytecodes: None,
        },
    })
}

/// Compile a single implicit variable from an
/// LTM equation to symbolic bytecodes.
///
/// This is analogous to `compile_implicit_var_fragment` but for implicit
/// variables generated by LTM equation parsing rather than by
/// SourceVariable parsing. The parent is an LTM equation (not a
/// SourceVariable), so we reconstruct the parse result from the LTM
/// equation text.
#[allow(clippy::too_many_arguments)]
pub(super) fn compile_ltm_implicit_var_fragment(
    db: &dyn Db,
    parsed: &ParsedVariableResult,
    idx: usize,
    meta: &LtmImplicitVarMeta,
    model: SourceModel,
    project: SourceProject,
    _dep_graph: &ModelDepGraphResult,
    module_input_names: &[String],
) -> Option<VarFragmentResult> {
    use crate::compiler::symbolic::{
        CompiledVarFragment, PerVarBytecodes, ReverseOffsetMap, VariableLayout,
    };

    let implicit_dm_var = parsed.implicit_vars.get(idx)?;
    let implicit_name = canonicalize(implicit_dm_var.get_ident()).into_owned();

    let dims = project_datamodel_dims(db, project);
    let dim_context = crate::dimensions::DimensionsContext::from(dims.as_slice());
    let converted_dims: Vec<crate::dimensions::Dimension> = dims
        .iter()
        .map(crate::dimensions::Dimension::from)
        .collect();

    let units_ctx = project_units_context(db, project);

    let mut dummy_implicits = Vec::new();
    let parsed_implicit = crate::variable::parse_var(
        dims,
        implicit_dm_var,
        &mut dummy_implicits,
        units_ctx,
        |mi| Ok(Some(mi.clone())),
    );

    if parsed_implicit
        .equation_errors()
        .is_some_and(|e| !e.is_empty())
    {
        return None;
    }

    // Module-type implicit vars need direct Module construction
    let lowered = if meta.is_module {
        if let datamodel::Variable::Module(dm_module) = implicit_dm_var {
            let module_inputs: Vec<crate::variable::ModuleInput> = dm_module
                .references
                .iter()
                .filter_map(|mr| {
                    let ident_prefix = format!("{}\u{00B7}", canonicalize(&implicit_name));
                    let src = canonicalize(&mr.src);
                    let dst = canonicalize(&mr.dst);
                    if src.starts_with(&ident_prefix) {
                        return None;
                    }
                    let dst_stripped = dst.strip_prefix(&ident_prefix)?;
                    let src_str = if model.name(db) == "main" && src.starts_with('\u{00B7}') {
                        &src['\u{00B7}'.len_utf8()..]
                    } else {
                        &src
                    };
                    Some(crate::variable::ModuleInput {
                        src: Ident::new(src_str),
                        dst: Ident::new(dst_stripped),
                    })
                })
                .collect();
            crate::variable::Variable::Module {
                ident: Ident::new(&implicit_name),
                model_name: Ident::new(&dm_module.model_name),
                units: None,
                inputs: module_inputs,
                errors: vec![],
                unit_errors: vec![],
            }
        } else {
            return None;
        }
    } else {
        let models = HashMap::new();
        let scope = crate::model::ScopeStage0 {
            models: &models,
            dimensions: &dim_context,
            model_name: "",
        };
        crate::model::lower_variable(&scope, &parsed_implicit)
    };

    let model_name_ident = Ident::new(model.name(db));
    let var_ident_canonical: Ident<Canonical> = Ident::new(&implicit_name);

    // Arena for sub-model stub variables
    let arena = bumpalo::Bump::new();

    let mut mini_metadata: HashMap<Ident<Canonical>, crate::compiler::VariableMetadata<'_>> =
        HashMap::new();
    // LTM implicit vars are in the root model context
    let mut mini_offset = crate::vm::IMPLICIT_VAR_COUNT;

    // Add implicit time/dt/initial_time/final_time
    {
        use std::sync::LazyLock;
        static IMPLICIT_TIME: LazyLock<crate::variable::Variable> =
            LazyLock::new(|| crate::variable::Variable::Var {
                ident: Ident::new("time"),
                ast: None,
                init_ast: None,
                eqn: None,
                units: None,
                tables: vec![],
                non_negative: false,
                is_flow: false,
                is_table_only: false,
                errors: vec![],
                unit_errors: vec![],
            });
        static IMPLICIT_DT: LazyLock<crate::variable::Variable> =
            LazyLock::new(|| crate::variable::Variable::Var {
                ident: Ident::new("dt"),
                ast: None,
                init_ast: None,
                eqn: None,
                units: None,
                tables: vec![],
                non_negative: false,
                is_flow: false,
                is_table_only: false,
                errors: vec![],
                unit_errors: vec![],
            });
        static IMPLICIT_INITIAL_TIME: LazyLock<crate::variable::Variable> =
            LazyLock::new(|| crate::variable::Variable::Var {
                ident: Ident::new("initial_time"),
                ast: None,
                init_ast: None,
                eqn: None,
                units: None,
                tables: vec![],
                non_negative: false,
                is_flow: false,
                is_table_only: false,
                errors: vec![],
                unit_errors: vec![],
            });
        static IMPLICIT_FINAL_TIME: LazyLock<crate::variable::Variable> =
            LazyLock::new(|| crate::variable::Variable::Var {
                ident: Ident::new("final_time"),
                ast: None,
                init_ast: None,
                eqn: None,
                units: None,
                tables: vec![],
                non_negative: false,
                is_flow: false,
                is_table_only: false,
                errors: vec![],
                unit_errors: vec![],
            });
        mini_metadata.insert(
            Ident::new("time"),
            crate::compiler::VariableMetadata {
                offset: 0,
                size: 1,
                var: &IMPLICIT_TIME,
            },
        );
        mini_metadata.insert(
            Ident::new("dt"),
            crate::compiler::VariableMetadata {
                offset: 1,
                size: 1,
                var: &IMPLICIT_DT,
            },
        );
        mini_metadata.insert(
            Ident::new("initial_time"),
            crate::compiler::VariableMetadata {
                offset: 2,
                size: 1,
                var: &IMPLICIT_INITIAL_TIME,
            },
        );
        mini_metadata.insert(
            Ident::new("final_time"),
            crate::compiler::VariableMetadata {
                offset: 3,
                size: 1,
                var: &IMPLICIT_FINAL_TIME,
            },
        );
    }

    let project_models = project.models(db);
    let self_size = meta.size;

    mini_metadata.insert(
        var_ident_canonical.clone(),
        crate::compiler::VariableMetadata {
            offset: mini_offset,
            size: self_size,
            var: &lowered,
        },
    );
    mini_offset += self_size;

    // Collect dependencies from the implicit var itself
    let source_vars = model.variables(db);
    let mut dep_variables: Vec<(Ident<Canonical>, crate::variable::Variable, usize)> = Vec::new();
    let mut module_refs: HashMap<Ident<Canonical>, crate::vm::ModuleKey> = HashMap::new();

    // For module-type implicit vars, build module_refs from the dm_module references
    if meta.is_module
        && let datamodel::Variable::Module(dm_module) = implicit_dm_var
    {
        let input_prefix = format!("{implicit_name}\u{00B7}");
        let input_set: BTreeSet<Ident<Canonical>> = dm_module
            .references
            .iter()
            .filter_map(|mr| {
                let dst_canonical = canonicalize(&mr.dst);
                let bare = dst_canonical.strip_prefix(&input_prefix)?;
                Some(Ident::new(bare))
            })
            .collect();
        module_refs.insert(
            var_ident_canonical.clone(),
            (Ident::new(&dm_module.model_name), input_set),
        );

        // Add dependency stubs for module input sources
        let ltm_implicit_all = model_ltm_implicit_var_info(db, model, project);
        for mr in &dm_module.references {
            let src = canonicalize(&mr.src);
            let effective = src.strip_prefix('\u{00B7}').unwrap_or(&src);
            if effective == implicit_name.as_str()
                || matches!(effective, "time" | "dt" | "initial_time" | "final_time")
            {
                continue;
            }
            // For submodel references like `module_var·output`, extract the
            // module variable name and add it as a module-type dependency so
            // the compiler context can resolve the submodel offset lookup.
            if let Some(dot_pos) = effective.find('\u{00B7}') {
                let module_var_name = &effective[..dot_pos];
                let dep_ident = Ident::new(module_var_name);
                if mini_metadata.contains_key(&dep_ident)
                    || dep_variables.iter().any(|(id, _, _)| id == &dep_ident)
                {
                    continue;
                }
                // Look up the referenced module in LTM implicit vars
                if let Some(ref_meta) = ltm_implicit_all.get(module_var_name)
                    && ref_meta.is_module
                    && let Some(ref mn) = ref_meta.model_name
                {
                    dep_variables.push((
                        dep_ident.clone(),
                        crate::variable::Variable::Module {
                            ident: dep_ident,
                            model_name: Ident::new(mn),
                            units: None,
                            inputs: vec![],
                            errors: vec![],
                            unit_errors: vec![],
                        },
                        ref_meta.size,
                    ));
                }
                continue;
            }
            let dep_ident = Ident::new(effective);
            if mini_metadata.contains_key(&dep_ident)
                || dep_variables.iter().any(|(id, _, _)| id == &dep_ident)
            {
                continue;
            }
            if let Some(dep_sv) = source_vars.get(effective) {
                let dep_dims = variable_dimensions(db, *dep_sv, project);
                let dep_size = variable_size(db, *dep_sv, project);
                let dep_var = build_stub_variable(db, dep_sv, &dep_ident, dep_dims);
                dep_variables.push((dep_ident, dep_var, dep_size));
            } else {
                // Could be another LTM var or implicit var -- scalar stub
                dep_variables.push((
                    dep_ident.clone(),
                    crate::variable::Variable::Var {
                        ident: dep_ident,
                        ast: None,
                        init_ast: None,
                        eqn: None,
                        units: None,
                        tables: vec![],
                        non_negative: false,
                        is_flow: false,
                        is_table_only: false,
                        errors: vec![],
                        unit_errors: vec![],
                    },
                    1,
                ));
            }
        }
    } else {
        // Non-module implicit vars (e.g., temp args from PREVIOUS rewrite)
        // may reference module variables from the parent model. Collect
        // those dependencies so the compilation context can resolve them.
        let dep_idents = if let Some(ast) = lowered.ast() {
            crate::variable::identifier_set(ast, &[], None)
        } else {
            HashSet::new()
        };

        let implicit_info = model_implicit_var_info(db, model, project);

        for dep_ident_str in &dep_idents {
            let dep_str = dep_ident_str.as_str();
            let effective = dep_str.strip_prefix('\u{00B7}').unwrap_or(dep_str);

            if effective == implicit_name.as_str()
                || matches!(effective, "time" | "dt" | "initial_time" | "final_time")
            {
                continue;
            }

            // Handle dotted module·port references (e.g., module·output).
            // Extract the module variable name and add it as a dependency.
            if let Some(dot_pos) = effective.find('\u{00B7}') {
                let module_var_name = &effective[..dot_pos];
                let dep_ident = Ident::new(module_var_name);
                if mini_metadata.contains_key(&dep_ident)
                    || dep_variables.iter().any(|(id, _, _)| id == &dep_ident)
                {
                    continue;
                }
                // Check model's implicit module vars (SMOOTH/DELAY instances)
                if let Some(im_meta) = implicit_info.get(module_var_name)
                    && im_meta.is_module
                    && let Some(ref mn) = im_meta.model_name
                {
                    dep_variables.push((
                        dep_ident.clone(),
                        crate::variable::Variable::Module {
                            ident: dep_ident,
                            model_name: Ident::new(mn),
                            units: None,
                            inputs: vec![],
                            errors: vec![],
                            unit_errors: vec![],
                        },
                        im_meta.size,
                    ));
                    module_refs.insert(
                        Ident::new(module_var_name),
                        (Ident::new(mn), BTreeSet::new()),
                    );
                } else if let Some(dep_sv) = source_vars.get(module_var_name)
                    && dep_sv.kind(db) == SourceVariableKind::Module
                {
                    let mod_model_name = dep_sv.model_name(db);
                    let sub_canonical = canonicalize(mod_model_name);
                    let sub_size = project_models
                        .get(sub_canonical.as_ref())
                        .map(|sm| compute_layout(db, *sm, project, false).n_slots)
                        .unwrap_or(1);
                    dep_variables.push((
                        dep_ident.clone(),
                        crate::variable::Variable::Module {
                            ident: dep_ident,
                            model_name: Ident::new(mod_model_name),
                            units: None,
                            inputs: vec![],
                            errors: vec![],
                            unit_errors: vec![],
                        },
                        sub_size,
                    ));
                    module_refs.insert(
                        Ident::new(module_var_name),
                        (Ident::new(mod_model_name), BTreeSet::new()),
                    );
                }
                continue;
            }

            let dep_ident = Ident::new(effective);
            if mini_metadata.contains_key(&dep_ident)
                || dep_variables.iter().any(|(id, _, _)| id == &dep_ident)
            {
                continue;
            }

            if let Some(dep_sv) = source_vars.get(effective) {
                let dep_dims = variable_dimensions(db, *dep_sv, project);
                let dep_size = variable_size(db, *dep_sv, project);
                let dep_var = build_stub_variable(db, dep_sv, &dep_ident, dep_dims);
                dep_variables.push((dep_ident, dep_var, dep_size));
            } else {
                dep_variables.push((
                    dep_ident.clone(),
                    crate::variable::Variable::Var {
                        ident: dep_ident,
                        ast: None,
                        init_ast: None,
                        eqn: None,
                        units: None,
                        tables: vec![],
                        non_negative: false,
                        is_flow: false,
                        is_table_only: false,
                        errors: vec![],
                        unit_errors: vec![],
                    },
                    1,
                ));
            }
        }
    }

    for (dep_ident, dep_var, dep_size) in &dep_variables {
        if !mini_metadata.contains_key(dep_ident) {
            mini_metadata.insert(
                dep_ident.clone(),
                crate::compiler::VariableMetadata {
                    offset: mini_offset,
                    size: *dep_size,
                    var: dep_var,
                },
            );
            mini_offset += dep_size;
        }
    }

    let mut all_metadata: HashMap<
        Ident<Canonical>,
        HashMap<Ident<Canonical>, crate::compiler::VariableMetadata<'_>>,
    > = HashMap::new();
    all_metadata.insert(model_name_ident.clone(), mini_metadata);

    // Build sub-model metadata for module-type implicit vars and any
    // module dependencies discovered during dependency collection.
    if meta.is_module
        && let Some(model_name) = &meta.model_name
    {
        let sub_canonical = canonicalize(model_name);
        if let Some(sub_model) = project_models.get(sub_canonical.as_ref()) {
            build_submodel_metadata(&arena, db, *sub_model, project, &mut all_metadata);
        }
    }
    for (sub_model_name, _input_set) in module_refs.values() {
        let sub_canonical = canonicalize(sub_model_name.as_str());
        if let Some(sub_model) = project_models.get(sub_canonical.as_ref())
            && !all_metadata.contains_key(sub_model_name)
        {
            build_submodel_metadata(&arena, db, *sub_model, project, &mut all_metadata);
        }
    }

    let mini_layout =
        crate::compiler::symbolic::layout_from_metadata(&all_metadata, &model_name_ident)
            .unwrap_or_else(|_| VariableLayout::new(HashMap::new(), 0));
    let rmap = ReverseOffsetMap::from_layout(&mini_layout);

    let tables: HashMap<Ident<Canonical>, Vec<crate::compiler::Table>> = HashMap::new();
    let inputs = canonical_module_input_set(module_input_names);
    let mut module_models = model_module_map(db, model, project).clone();

    // Merge ALL LTM implicit module references into the module_models map.
    // A module's inputs may reference outputs from OTHER LTM implicit modules
    // (e.g., PREVIOUS instance #6 reading from PREVIOUS instance #5's output),
    // so we must include all LTM implicit modules, not just the current one.
    {
        let ltm_implicit = model_ltm_implicit_var_info(db, model, project);
        let current_model_modules = module_models.entry(model_name_ident.clone()).or_default();
        // Add the current variable's own module refs
        for (var_ident, (sub_model_name, _input_set)) in &module_refs {
            current_model_modules.insert(var_ident.clone(), sub_model_name.clone());
        }
        // Add all other LTM implicit module refs so cross-references resolve
        for (name, im_meta) in ltm_implicit.iter() {
            if im_meta.is_module
                && let Some(mn) = &im_meta.model_name
            {
                let im_ident: Ident<Canonical> = Ident::new(name);
                current_model_modules.insert(im_ident, Ident::new(mn.as_str()));
            }
        }
    }

    let core = crate::compiler::ContextCore {
        dimensions: &converted_dims,
        dimensions_ctx: &dim_context,
        model_name: &model_name_ident,
        metadata: &all_metadata,
        module_models: &module_models,
        inputs: &inputs,
    };

    let build_var = |is_initial: bool| {
        crate::compiler::Var::new(
            &crate::compiler::Context::new(core, &var_ident_canonical, is_initial),
            &lowered,
        )
    };

    let compile_phase = |exprs: &[crate::compiler::Expr]| -> Option<PerVarBytecodes> {
        if exprs.is_empty() {
            return None;
        }

        let module_inputs_set: HashSet<Ident<Canonical>> = inputs.iter().cloned().collect();
        let module = crate::compiler::Module {
            ident: model_name_ident.clone(),
            inputs: module_inputs_set,
            n_slots: mini_offset,
            n_temps: 0,
            temp_sizes: vec![],
            runlist_initials: vec![],
            runlist_initials_by_var: vec![],
            runlist_flows: exprs.to_vec(),
            runlist_stocks: vec![],
            offsets: all_metadata
                .iter()
                .map(|(k, v)| {
                    (
                        k.clone(),
                        v.iter()
                            .map(|(vk, vm)| (vk.clone(), (vm.offset, vm.size)))
                            .collect(),
                    )
                })
                .collect(),
            runlist_order: vec![var_ident_canonical.clone()],
            tables: tables.clone(),
            dimensions: converted_dims.clone(),
            dimensions_ctx: dim_context.clone(),
            module_refs: module_refs.clone(),
        };

        let mut temp_sizes_map: HashMap<u32, usize> = HashMap::new();
        for expr in exprs {
            crate::compiler::extract_temp_sizes_pub(expr, &mut temp_sizes_map);
        }
        let n_temps = temp_sizes_map.len();
        let mut temp_sizes: Vec<usize> = vec![0; n_temps];
        for (id, size) in &temp_sizes_map {
            if (*id as usize) < temp_sizes.len() {
                temp_sizes[*id as usize] = *size;
            }
        }

        let module = crate::compiler::Module {
            n_temps,
            temp_sizes: temp_sizes.clone(),
            ..module
        };

        match module.compile() {
            Ok(compiled) => {
                let sym_bc =
                    crate::compiler::symbolic::symbolize_bytecode(&compiled.compiled_flows, &rmap)
                        .ok()?;

                let ctx = &*compiled.context;
                let sym_views: Vec<_> = ctx
                    .static_views
                    .iter()
                    .map(|sv| crate::compiler::symbolic::symbolize_static_view(sv, &rmap))
                    .collect::<Result<Vec<_>, _>>()
                    .ok()?;
                let sym_mods: Vec<_> = ctx
                    .modules
                    .iter()
                    .map(|md| crate::compiler::symbolic::symbolize_module_decl(md, &rmap))
                    .collect::<Result<Vec<_>, _>>()
                    .ok()?;

                let temp_sizes_vec: Vec<(u32, usize)> =
                    temp_sizes_map.iter().map(|(&k, &v)| (k, v)).collect();

                let dim_lists: Vec<Vec<u16>> = ctx
                    .dim_lists
                    .iter()
                    .map(|(n, arr)| arr[..(*n as usize)].to_vec())
                    .collect();

                Some(PerVarBytecodes {
                    symbolic: sym_bc,
                    graphical_functions: ctx.graphical_functions.clone(),
                    module_decls: sym_mods,
                    static_views: sym_views,
                    temp_sizes: temp_sizes_vec,
                    dim_lists,
                })
            }
            Err(_) => None,
        }
    };

    // LTM implicit vars participate in whichever phases their lowered
    // form needs. The dep_graph won't have them in its runlists since
    // they are not part of the original model.
    // We compile all available phases.
    let initial_bytecodes = match build_var(true) {
        Ok(var_result) => compile_phase(&var_result.ast),
        Err(_) => None,
    };

    let flow_bytecodes = if !meta.is_stock {
        match build_var(false) {
            Ok(var_result) => compile_phase(&var_result.ast),
            Err(_) => None,
        }
    } else {
        None
    };

    let stock_bytecodes = if meta.is_stock || meta.is_module {
        match build_var(false) {
            Ok(var_result) => compile_phase(&var_result.ast),
            Err(_) => None,
        }
    } else {
        None
    };

    Some(VarFragmentResult {
        fragment: CompiledVarFragment {
            ident: implicit_name,
            initial_bytecodes,
            flow_bytecodes,
            stock_bytecodes,
        },
    })
}

/// Find the output ports for a model by scanning other models' variable
/// dependencies for module·var references that target this model.
///
/// When variable X depends on `module_var·internal_var` and `module_var`
/// maps to this model (via `dynamic_modules`), then `internal_var` is
/// an output port. The result is passed to `enumerate_pathways_to_outputs`
/// so that composite scores are generated for the correct output ports.
fn find_model_output_ports(
    db: &dyn Db,
    model: SourceModel,
    project: SourceProject,
) -> Vec<Ident<Canonical>> {
    let model_name = model.name(db);
    let project_models = project.models(db);
    let middot = '\u{00B7}';
    let mut output_ports: HashSet<Ident<Canonical>> = HashSet::new();

    for (_, other_model) in project_models.iter() {
        if other_model == &model {
            continue;
        }
        let other_edges = super::model_causal_edges(db, *other_model, project);

        // Build a set of module variable names that reference this model
        let module_var_names: HashSet<&String> = other_edges
            .dynamic_modules
            .iter()
            .filter(|(_var_name, mn)| mn.as_str() == model_name.as_str())
            .map(|(var_name, _mn)| var_name)
            .collect();

        if module_var_names.is_empty() {
            continue;
        }

        // Scan dependencies for module·internal_var references
        let other_vars = other_model.variables(db);
        let module_ctx = super::model_module_ident_context(db, *other_model, vec![]);
        for (_, source_var) in other_vars.iter() {
            let deps = super::variable_direct_dependencies(db, *source_var, project);
            for dep in &deps.dt_deps {
                if let Some(dot_pos) = dep.find(middot) {
                    let module_part = &dep[..dot_pos];
                    let internal_var = &dep[dot_pos + middot.len_utf8()..];
                    if module_var_names.contains(&module_part.to_string()) {
                        output_ports.insert(Ident::new(internal_var));
                    }
                }
            }

            // Also check implicit variable deps (SMOOTH/DELAY expansion
            // creates helper auxes whose deps may reference module outputs)
            let parsed = super::parse_source_variable_with_module_context(
                db,
                *source_var,
                project,
                module_ctx,
            );
            for implicit_dm_var in &parsed.implicit_vars {
                if let datamodel::Variable::Module(_) = implicit_dm_var {
                    continue;
                }
                let deps = super::variable_direct_dependencies(db, *source_var, project);
                for iv_dep in &deps.implicit_vars {
                    for dep in &iv_dep.dt_deps {
                        if let Some(dot_pos) = dep.find(middot) {
                            let module_part = &dep[..dot_pos];
                            let internal_var = &dep[dot_pos + middot.len_utf8()..];
                            if module_var_names.contains(&module_part.to_string()) {
                                output_ports.insert(Ident::new(internal_var));
                            }
                        }
                    }
                }
            }
        }
    }

    output_ports.into_iter().collect()
}

/// Unified LTM variable generation for any model (root or sub-model).
///
/// Auto-detects sub-model behavior by checking for input ports with causal
/// pathways to output. Sub-models and discovery mode generate link scores
/// for ALL edges; exhaustive mode on root models generates link scores only
/// for edges in detected loops, plus loop/relative loop scores.
///
/// Pathway and composite scores are generated for models with input ports.
/// Module-containing loops are no longer filtered out because
/// `link_score_equation_text` now handles module links via composite refs.
#[salsa::tracked(returns(ref))]
pub fn model_ltm_variables(
    db: &dyn Db,
    model: SourceModel,
    project: SourceProject,
) -> super::LtmVariablesResult {
    use crate::common::{Canonical, Ident};
    use crate::ltm::{CyclePartitions, Loop, assign_loop_ids};
    use std::collections::HashSet;

    use super::{
        LtmLinkId, LtmSyntheticVar, LtmVariablesResult, causal_graph_with_modules,
        generate_max_abs_chain_str, model_causal_edges, model_cycle_partitions,
        model_loop_circuits, module_input_pathways_from_edges,
    };

    let edges_result = model_causal_edges(db, model, project);
    if edges_result.stocks.is_empty() {
        return LtmVariablesResult { vars: vec![] };
    }

    let is_discovery = project.ltm_discovery_mode(db);

    // Determine output ports for this model. Stdlib models always use
    // the "output" convention. For user-defined models, output ports are
    // determined by which internal variables are referenced from parent
    // models via module·var syntax.
    let model_name_str = model.name(db);
    let output_ports = if model_name_str.starts_with("stdlib\u{205A}") {
        vec![Ident::new("output")]
    } else {
        find_model_output_ports(db, model, project)
    };
    let pathways = if output_ports.is_empty() {
        HashMap::new()
    } else {
        module_input_pathways_from_edges(edges_result, &output_ports)
    };
    let has_input_ports = !pathways.is_empty();

    let mut vars = Vec::new();

    // Pre-compute loops for exhaustive mode. Both the link-score
    // strategy (loop edges only) and loop/relative score generation
    // share this data, so compute once and reuse.
    let loops: Option<Vec<Loop>> = if !is_discovery {
        let circuits_result = model_loop_circuits(db, model, project);
        if circuits_result.circuits.is_empty() {
            if !has_input_ports {
                return LtmVariablesResult { vars: vec![] };
            }
            None
        } else {
            let graph = causal_graph_with_modules(db, model, project);

            let mut detected: Vec<Loop> = circuits_result
                .circuits
                .iter()
                .map(|circuit_strs| {
                    let circuit: Vec<Ident<Canonical>> =
                        circuit_strs.iter().map(|s| Ident::new(s)).collect();
                    let links = graph.circuit_to_links(&circuit);
                    let parent_stocks = graph.find_stocks_in_loop(&circuit);
                    let polarity = graph.calculate_polarity(&links);
                    Loop {
                        id: String::new(),
                        links,
                        stocks: parent_stocks,
                        polarity,
                    }
                })
                .collect();

            assign_loop_ids(&mut detected);
            Some(detected)
        }
    } else {
        None
    };

    // Part 1: Link scores.
    // Sub-models and discovery mode need scores for ALL edges (pathways
    // reference arbitrary edges). Exhaustive root models only need
    // scores for edges that participate in loops.
    if has_input_ports || is_discovery {
        for (from, tos) in &edges_result.edges {
            for to in tos {
                let link_id = LtmLinkId::new(db, from.clone(), to.clone());
                if let Some(lsv) = link_score_equation_text(db, link_id, model, project) {
                    vars.push(lsv.clone());
                }
            }
        }
    } else if let Some(ref detected_loops) = loops {
        let mut seen_links: HashSet<(String, String)> = HashSet::new();
        for loop_item in detected_loops {
            for link in &loop_item.links {
                let key = (link.from.to_string(), link.to.to_string());
                if seen_links.insert(key) {
                    let link_id = LtmLinkId::new(db, link.from.to_string(), link.to.to_string());
                    if let Some(lsv) = link_score_equation_text(db, link_id, model, project) {
                        vars.push(lsv.clone());
                    }
                }
            }
        }
    }

    // Part 2: Loop scores and relative loop scores (exhaustive mode only).
    // Generated for any model with feedback loops, regardless of whether
    // it also has input ports. A model can be both a reusable sub-model
    // AND have internal loops that need scoring.
    if let Some(ref detected_loops) = loops {
        let partitions_result = model_cycle_partitions(db, model, project);
        let partitions = CyclePartitions {
            partitions: partitions_result
                .partitions
                .iter()
                .map(|p| p.iter().map(|s| Ident::new(s)).collect())
                .collect(),
            stock_partition: partitions_result
                .stock_partition
                .iter()
                .map(|(k, v)| (Ident::new(k), *v))
                .collect(),
        };

        let loop_vars =
            crate::ltm_augment::generate_loop_score_variables(detected_loops, &partitions);
        for (name, var) in loop_vars {
            let equation = match var.get_equation() {
                Some(crate::datamodel::Equation::Scalar(eq)) => eq.clone(),
                _ => String::new(),
            };
            vars.push(LtmSyntheticVar {
                name: name.to_string(),
                equation,
                dimensions: vec![],
            });
        }
    }

    // Pathway and composite scores for models with input ports
    for (input_port, port_pathways) in &pathways {
        let mut pathway_names = Vec::new();
        for (idx, pathway_links) in port_pathways.iter().enumerate() {
            let path_var_name = format!(
                "$\u{205A}ltm\u{205A}path\u{205A}{}\u{205A}{}",
                input_port.as_str(),
                idx
            );

            let link_score_refs: Vec<String> = pathway_links
                .iter()
                .map(|link| {
                    format!(
                        "\"$\u{205A}ltm\u{205A}link_score\u{205A}{}\u{2192}{}\"",
                        link.from.as_str(),
                        link.to.as_str()
                    )
                })
                .collect();

            let equation = if link_score_refs.is_empty() {
                "0".to_string()
            } else {
                link_score_refs.join(" * ")
            };

            pathway_names.push(path_var_name.clone());
            vars.push(LtmSyntheticVar {
                name: path_var_name,
                equation,
                dimensions: vec![],
            });
        }

        let composite_name = format!(
            "$\u{205A}ltm\u{205A}composite\u{205A}{}",
            input_port.as_str()
        );
        let equation = generate_max_abs_chain_str(&pathway_names);
        vars.push(LtmSyntheticVar {
            name: composite_name,
            equation,
            dimensions: vec![],
        });
    }

    // Sort by evaluation-order category (link_score before path before
    // composite) so the VM's sequential flow evaluation respects the
    // dependency chain: composites reference paths which reference link
    // scores. Within each category, sort lexically for determinism.
    vars.sort_by(|a, b| {
        fn category(name: &str) -> u8 {
            if name.contains("\u{205A}composite\u{205A}") {
                3
            } else if name.contains("\u{205A}path\u{205A}") {
                2
            } else if name.contains("\u{205A}loop_score\u{205A}")
                || name.contains("\u{205A}rel_loop_score\u{205A}")
            {
                1
            } else {
                0 // link_score and anything else
            }
        }
        category(&a.name)
            .cmp(&category(&b.name))
            .then_with(|| a.name.cmp(&b.name))
    });
    LtmVariablesResult { vars }
}

#[cfg(test)]
#[path = "db_ltm_tests.rs"]
mod db_ltm_tests;
