// @generated from stdlib/*.stmx
// DO NOT EDIT - regenerate with: pnpm rebuild-stdlib
//
// Stdlib SHA256: 7fb58d5c90732144633cb1210aa061b00667f84e6cf762eb0a4d3557fbaecf0c

#![allow(
    clippy::approx_constant,
    clippy::excessive_precision,
    clippy::unreadable_literal,
    unused_imports
)]

use crate::datamodel::view_element::{FlowPoint, LabelSide, LinkPolarity, LinkShape};
use crate::datamodel::{
    Aux, Dt, Equation, Flow, GraphicalFunction, GraphicalFunctionKind, GraphicalFunctionScale,
    LoopMetadata, Model, ModelGroup, Module, ModuleReference, Rect, SimMethod, SimSpecs, Stock,
    StockFlow, Variable, View, ViewElement, Visibility, view_element,
};

pub const MODEL_NAMES: [&str; 7] = [
    "delay1", "delay3", "init", "previous", "smth1", "smth3", "trend",
];

pub fn get(name: &str) -> Option<Model> {
    match name {
        "delay1" => Some(delay1()),
        "delay3" => Some(delay3()),
        "init" => Some(init()),
        "previous" => Some(previous()),
        "smth1" => Some(smth1()),
        "smth3" => Some(smth3()),
        "trend" => Some(trend()),
        _ => None,
    }
}

fn delay1() -> Model {
    Model {
        name: "stdlib⁚delay1".to_string(),
        sim_specs: None,
        variables: vec![
            Variable::Aux(Aux {
                ident: "delay_time".to_string(),
                equation: Equation::Scalar("1".to_string(), None),
                documentation: "".to_string(),
                units: None,
                gf: None,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
            Variable::Aux(Aux {
                ident: "initial_value".to_string(),
                equation: Equation::Scalar("NAN".to_string(), None),
                documentation: "".to_string(),
                units: None,
                gf: None,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
            Variable::Flow(Flow {
                ident: "input".to_string(),
                equation: Equation::Scalar("0".to_string(), None),
                documentation: "".to_string(),
                units: None,
                gf: None,
                non_negative: false,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
            Variable::Flow(Flow {
                ident: "output".to_string(),
                equation: Equation::Scalar("Stock/delay_time".to_string(), None),
                documentation: "".to_string(),
                units: None,
                gf: None,
                non_negative: false,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
            Variable::Stock(Stock {
                ident: "stock".to_string(),
                equation: Equation::Scalar(
                    "(if isModuleInput(initial_value) then initial_value else input) * delay_time"
                        .to_string(),
                    None,
                ),
                documentation: "".to_string(),
                units: None,
                inflows: vec!["input".to_string()],
                outflows: vec!["output".to_string()],
                non_negative: false,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
        ],
        views: vec![View::StockFlow(StockFlow {
            elements: vec![
                ViewElement::Stock(view_element::Stock {
                    name: "Stock".to_string(),
                    uid: 1,
                    x: 232_f64,
                    y: 168_f64,
                    label_side: LabelSide::Top,
                }),
                ViewElement::Flow(view_element::Flow {
                    name: "input".to_string(),
                    uid: 2,
                    x: 169.75_f64,
                    y: 170_f64,
                    label_side: LabelSide::Bottom,
                    points: vec![
                        FlowPoint {
                            x: 130_f64,
                            y: 170_f64,
                            attached_to_uid: Some(8),
                        },
                        FlowPoint {
                            x: 209.5_f64,
                            y: 170_f64,
                            attached_to_uid: Some(1),
                        },
                    ],
                }),
                ViewElement::Flow(view_element::Flow {
                    name: "output".to_string(),
                    uid: 3,
                    x: 291.75_f64,
                    y: 168_f64,
                    label_side: LabelSide::Bottom,
                    points: vec![
                        FlowPoint {
                            x: 254.5_f64,
                            y: 168_f64,
                            attached_to_uid: Some(1),
                        },
                        FlowPoint {
                            x: 353_f64,
                            y: 168_f64,
                            attached_to_uid: Some(9),
                        },
                    ],
                }),
                ViewElement::Aux(view_element::Aux {
                    name: "delay time".to_string(),
                    uid: 4,
                    x: 337.5_f64,
                    y: 233_f64,
                    label_side: LabelSide::Bottom,
                }),
                ViewElement::Link(view_element::Link {
                    uid: 5,
                    from_uid: 4,
                    to_uid: 3,
                    shape: LinkShape::Straight,
                    polarity: None,
                }),
                ViewElement::Link(view_element::Link {
                    uid: 6,
                    from_uid: 1,
                    to_uid: 3,
                    shape: LinkShape::Arc(49.899_f64),
                    polarity: None,
                }),
                ViewElement::Aux(view_element::Aux {
                    name: "initial value".to_string(),
                    uid: 7,
                    x: 221_f64,
                    y: 41_f64,
                    label_side: LabelSide::Bottom,
                }),
                ViewElement::Cloud(view_element::Cloud {
                    uid: 8,
                    flow_uid: 2,
                    x: 130_f64,
                    y: 170_f64,
                }),
                ViewElement::Cloud(view_element::Cloud {
                    uid: 9,
                    flow_uid: 3,
                    x: 353_f64,
                    y: 168_f64,
                }),
            ],
            view_box: Rect {
                x: 0_f64,
                y: 0_f64,
                width: 0_f64,
                height: 0_f64,
            },
            zoom: 1_f64,
            use_lettered_polarity: false,
        })],
        loop_metadata: vec![],
        groups: vec![],
    }
}

fn delay3() -> Model {
    Model {
        name: "stdlib⁚delay3".to_string(),
        sim_specs: None,
        variables: vec![
            Variable::Aux(Aux {
            ident: "delay_time".to_string(),
            equation: Equation::Scalar("1".to_string(), None),
            documentation: "".to_string(),
            units: None,
            gf: None,
            can_be_module_input: false,
            visibility: Visibility::Private,
            ai_state: None,
            uid: None,
        }),
            Variable::Flow(Flow {
            ident: "flow_1".to_string(),
            equation: Equation::Scalar("Stock/(delay_time/3)".to_string(), None),
            documentation: "".to_string(),
            units: None,
            gf: None,
            non_negative: false,
            can_be_module_input: false,
            visibility: Visibility::Private,
            ai_state: None,
            uid: None,
        }),
            Variable::Flow(Flow {
            ident: "flow_2".to_string(),
            equation: Equation::Scalar("Stock_2/(delay_time/3)".to_string(), None),
            documentation: "".to_string(),
            units: None,
            gf: None,
            non_negative: false,
            can_be_module_input: false,
            visibility: Visibility::Private,
            ai_state: None,
            uid: None,
        }),
            Variable::Aux(Aux {
            ident: "initial_value".to_string(),
            equation: Equation::Scalar("NAN".to_string(), None),
            documentation: "".to_string(),
            units: None,
            gf: None,
            can_be_module_input: false,
            visibility: Visibility::Private,
            ai_state: None,
            uid: None,
        }),
            Variable::Flow(Flow {
            ident: "input".to_string(),
            equation: Equation::Scalar("0".to_string(), None),
            documentation: "".to_string(),
            units: None,
            gf: None,
            non_negative: false,
            can_be_module_input: false,
            visibility: Visibility::Private,
            ai_state: None,
            uid: None,
        }),
            Variable::Flow(Flow {
            ident: "output".to_string(),
            equation: Equation::Scalar("Stock_3/(delay_time/3)".to_string(), None),
            documentation: "".to_string(),
            units: None,
            gf: None,
            non_negative: false,
            can_be_module_input: false,
            visibility: Visibility::Private,
            ai_state: None,
            uid: None,
        }),
            Variable::Stock(Stock {
            ident: "stock".to_string(),
            equation: Equation::Scalar("(if isModuleInput(initial_value) then initial_value else input) * (delay_time/3)".to_string(), None),
            documentation: "".to_string(),
            units: None,
            inflows: vec!["input".to_string()],
            outflows: vec!["flow_1".to_string()],
            non_negative: false,
            can_be_module_input: false,
            visibility: Visibility::Private,
            ai_state: None,
            uid: None,
        }),
            Variable::Stock(Stock {
            ident: "stock_2".to_string(),
            equation: Equation::Scalar("(if isModuleInput(initial_value) then initial_value else input) * (delay_time/3)".to_string(), None),
            documentation: "".to_string(),
            units: None,
            inflows: vec!["flow_1".to_string()],
            outflows: vec!["flow_2".to_string()],
            non_negative: false,
            can_be_module_input: false,
            visibility: Visibility::Private,
            ai_state: None,
            uid: None,
        }),
            Variable::Stock(Stock {
            ident: "stock_3".to_string(),
            equation: Equation::Scalar("(if isModuleInput(initial_value) then initial_value else input) * (delay_time/3)".to_string(), None),
            documentation: "".to_string(),
            units: None,
            inflows: vec!["flow_2".to_string()],
            outflows: vec!["output".to_string()],
            non_negative: false,
            can_be_module_input: false,
            visibility: Visibility::Private,
            ai_state: None,
            uid: None,
        })
        ],
        views: vec![View::StockFlow(StockFlow {
            elements: vec![ViewElement::Stock(view_element::Stock {
                name: "Stock".to_string(),
                uid: 1,
                x: 232_f64,
                y: 168_f64,
                label_side: LabelSide::Top,
            }),
                ViewElement::Flow(view_element::Flow {
                    name: "input".to_string(),
                    uid: 2,
                    x: 169.75_f64,
                    y: 170_f64,
                    label_side: LabelSide::Bottom,
                    points: vec![FlowPoint { x: 130_f64, y: 170_f64, attached_to_uid: Some(16) }, FlowPoint { x: 209.5_f64, y: 170_f64, attached_to_uid: Some(1) }],
                }),
                ViewElement::Flow(view_element::Flow {
                    name: "output".to_string(),
                    uid: 3,
                    x: 558.25_f64,
                    y: 171_f64,
                    label_side: LabelSide::Bottom,
                    points: vec![FlowPoint { x: 520.5_f64, y: 171_f64, attached_to_uid: Some(9) }, FlowPoint { x: 620_f64, y: 171_f64, attached_to_uid: Some(17) }],
                }),
                ViewElement::Aux(view_element::Aux {
                name: "delay time".to_string(),
                uid: 4,
                x: 426.5_f64,
                y: 300_f64,
                label_side: LabelSide::Bottom,
            }),
                ViewElement::Link(view_element::Link {
                uid: 5,
                from_uid: 4,
                to_uid: 3,
                shape: LinkShape::Straight,
                polarity: None,
            }),
                ViewElement::Aux(view_element::Aux {
                name: "initial value".to_string(),
                uid: 6,
                x: 221_f64,
                y: 41_f64,
                label_side: LabelSide::Bottom,
            }),
                ViewElement::Flow(view_element::Flow {
                    name: "Flow 1".to_string(),
                    uid: 7,
                    x: 294_f64,
                    y: 169_f64,
                    label_side: LabelSide::Bottom,
                    points: vec![FlowPoint { x: 254.5_f64, y: 169_f64, attached_to_uid: Some(1) }, FlowPoint { x: 345.5_f64, y: 169_f64, attached_to_uid: Some(8) }],
                }),
                ViewElement::Stock(view_element::Stock {
                name: "Stock 2".to_string(),
                uid: 8,
                x: 368_f64,
                y: 170_f64,
                label_side: LabelSide::Top,
            }),
                ViewElement::Stock(view_element::Stock {
                name: "Stock 3".to_string(),
                uid: 9,
                x: 498_f64,
                y: 171_f64,
                label_side: LabelSide::Top,
            }),
                ViewElement::Flow(view_element::Flow {
                    name: "Flow 2".to_string(),
                    uid: 10,
                    x: 427_f64,
                    y: 170_f64,
                    label_side: LabelSide::Bottom,
                    points: vec![FlowPoint { x: 390.5_f64, y: 170_f64, attached_to_uid: Some(8) }, FlowPoint { x: 475.5_f64, y: 170_f64, attached_to_uid: Some(9) }],
                }),
                ViewElement::Link(view_element::Link {
                uid: 11,
                from_uid: 9,
                to_uid: 3,
                shape: LinkShape::Arc(-64.98309999999998_f64),
                polarity: None,
            }),
                ViewElement::Link(view_element::Link {
                uid: 12,
                from_uid: 4,
                to_uid: 10,
                shape: LinkShape::Straight,
                polarity: None,
            }),
                ViewElement::Link(view_element::Link {
                uid: 13,
                from_uid: 4,
                to_uid: 7,
                shape: LinkShape::Straight,
                polarity: None,
            }),
                ViewElement::Link(view_element::Link {
                uid: 14,
                from_uid: 1,
                to_uid: 7,
                shape: LinkShape::Arc(-69.77510000000001_f64),
                polarity: None,
            }),
                ViewElement::Link(view_element::Link {
                uid: 15,
                from_uid: 8,
                to_uid: 10,
                shape: LinkShape::Arc(-65.77229999999997_f64),
                polarity: None,
            }),
                ViewElement::Cloud(view_element::Cloud {
                uid: 16,
                flow_uid: 2,
                x: 130_f64,
                y: 170_f64,
            }),
                ViewElement::Cloud(view_element::Cloud {
                uid: 17,
                flow_uid: 3,
                x: 620_f64,
                y: 171_f64,
            })],
            view_box: Rect { x: 0_f64, y: 0_f64, width: 0_f64, height: 0_f64 },
            zoom: 1_f64,
            use_lettered_polarity: false,
        })],
        loop_metadata: vec![],
        groups: vec![],
    }
}

fn init() -> Model {
    Model {
        name: "stdlib⁚init".to_string(),
        sim_specs: None,
        variables: vec![
            Variable::Aux(Aux {
                ident: "input".to_string(),
                equation: Equation::Scalar("0".to_string(), None),
                documentation: "".to_string(),
                units: None,
                gf: None,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
            Variable::Stock(Stock {
                ident: "output".to_string(),
                equation: Equation::Scalar("input".to_string(), None),
                documentation: "".to_string(),
                units: None,
                inflows: vec![],
                outflows: vec![],
                non_negative: false,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
        ],
        views: vec![View::StockFlow(StockFlow {
            elements: vec![
                ViewElement::Stock(view_element::Stock {
                    name: "Output".to_string(),
                    uid: 1,
                    x: 101.083_f64,
                    y: 199.333_f64,
                    label_side: LabelSide::Top,
                }),
                ViewElement::Aux(view_element::Aux {
                    name: "input".to_string(),
                    uid: 2,
                    x: 106_f64,
                    y: 117_f64,
                    label_side: LabelSide::Bottom,
                }),
            ],
            view_box: Rect {
                x: 0_f64,
                y: 0_f64,
                width: 0_f64,
                height: 0_f64,
            },
            zoom: 1_f64,
            use_lettered_polarity: false,
        })],
        loop_metadata: vec![],
        groups: vec![],
    }
}

fn previous() -> Model {
    Model {
        name: "stdlib⁚previous".to_string(),
        sim_specs: None,
        variables: vec![
            Variable::Flow(Flow {
                ident: "draining".to_string(),
                equation: Equation::Scalar("output / DT".to_string(), None),
                documentation: "".to_string(),
                units: None,
                gf: None,
                non_negative: false,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
            Variable::Aux(Aux {
                ident: "initial_value".to_string(),
                equation: Equation::Scalar("0".to_string(), None),
                documentation: "".to_string(),
                units: None,
                gf: None,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
            Variable::Aux(Aux {
                ident: "input".to_string(),
                equation: Equation::Scalar("0".to_string(), None),
                documentation: "".to_string(),
                units: None,
                gf: None,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
            Variable::Flow(Flow {
                ident: "measuring".to_string(),
                equation: Equation::Scalar("input / DT".to_string(), None),
                documentation: "".to_string(),
                units: None,
                gf: None,
                non_negative: false,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
            Variable::Stock(Stock {
                ident: "output".to_string(),
                equation: Equation::Scalar("initial_value".to_string(), None),
                documentation: "".to_string(),
                units: None,
                inflows: vec!["measuring".to_string()],
                outflows: vec!["draining".to_string()],
                non_negative: false,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
        ],
        views: vec![View::StockFlow(StockFlow {
            elements: vec![
                ViewElement::Stock(view_element::Stock {
                    name: "output".to_string(),
                    uid: 1,
                    x: 418_f64,
                    y: 211_f64,
                    label_side: LabelSide::Top,
                }),
                ViewElement::Flow(view_element::Flow {
                    name: "measuring".to_string(),
                    uid: 2,
                    x: 351.75_f64,
                    y: 211_f64,
                    label_side: LabelSide::Bottom,
                    points: vec![
                        FlowPoint {
                            x: 308_f64,
                            y: 211_f64,
                            attached_to_uid: Some(8),
                        },
                        FlowPoint {
                            x: 395.5_f64,
                            y: 211_f64,
                            attached_to_uid: Some(1),
                        },
                    ],
                }),
                ViewElement::Flow(view_element::Flow {
                    name: "draining".to_string(),
                    uid: 3,
                    x: 468.75_f64,
                    y: 210_f64,
                    label_side: LabelSide::Top,
                    points: vec![
                        FlowPoint {
                            x: 440.5_f64,
                            y: 210_f64,
                            attached_to_uid: Some(1),
                        },
                        FlowPoint {
                            x: 521_f64,
                            y: 210_f64,
                            attached_to_uid: Some(9),
                        },
                    ],
                }),
                ViewElement::Link(view_element::Link {
                    uid: 4,
                    from_uid: 1,
                    to_uid: 3,
                    shape: LinkShape::Arc(39.56_f64),
                    polarity: None,
                }),
                ViewElement::Aux(view_element::Aux {
                    name: "initial value".to_string(),
                    uid: 5,
                    x: 351.75_f64,
                    y: 133_f64,
                    label_side: LabelSide::Bottom,
                }),
                ViewElement::Aux(view_element::Aux {
                    name: "input".to_string(),
                    uid: 6,
                    x: 293_f64,
                    y: 133_f64,
                    label_side: LabelSide::Bottom,
                }),
                ViewElement::Link(view_element::Link {
                    uid: 7,
                    from_uid: 6,
                    to_uid: 2,
                    shape: LinkShape::Arc(48.01299999999998_f64),
                    polarity: None,
                }),
                ViewElement::Cloud(view_element::Cloud {
                    uid: 8,
                    flow_uid: 2,
                    x: 308_f64,
                    y: 211_f64,
                }),
                ViewElement::Cloud(view_element::Cloud {
                    uid: 9,
                    flow_uid: 3,
                    x: 521_f64,
                    y: 210_f64,
                }),
            ],
            view_box: Rect {
                x: 0_f64,
                y: 0_f64,
                width: 0_f64,
                height: 0_f64,
            },
            zoom: 1_f64,
            use_lettered_polarity: false,
        })],
        loop_metadata: vec![],
        groups: vec![],
    }
}

fn smth1() -> Model {
    Model {
        name: "stdlib⁚smth1".to_string(),
        sim_specs: None,
        variables: vec![
            Variable::Aux(Aux {
                ident: "delay_time".to_string(),
                equation: Equation::Scalar("1".to_string(), None),
                documentation: "".to_string(),
                units: None,
                gf: None,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
            Variable::Flow(Flow {
                ident: "flow".to_string(),
                equation: Equation::Scalar("(input - Output)/delay_time".to_string(), None),
                documentation: "".to_string(),
                units: None,
                gf: None,
                non_negative: false,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
            Variable::Aux(Aux {
                ident: "initial_value".to_string(),
                equation: Equation::Scalar("NAN".to_string(), None),
                documentation: "".to_string(),
                units: None,
                gf: None,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
            Variable::Aux(Aux {
                ident: "input".to_string(),
                equation: Equation::Scalar("0".to_string(), None),
                documentation: "".to_string(),
                units: None,
                gf: None,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
            Variable::Stock(Stock {
                ident: "output".to_string(),
                equation: Equation::Scalar(
                    "if isModuleInput(initial_value) then initial_value else input".to_string(),
                    None,
                ),
                documentation: "".to_string(),
                units: None,
                inflows: vec!["flow".to_string()],
                outflows: vec![],
                non_negative: false,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
        ],
        views: vec![View::StockFlow(StockFlow {
            elements: vec![
                ViewElement::Link(view_element::Link {
                    uid: 1,
                    from_uid: 3,
                    to_uid: 2,
                    shape: LinkShape::Arc(121.43_f64),
                    polarity: None,
                }),
                ViewElement::Flow(view_element::Flow {
                    name: "flow".to_string(),
                    uid: 2,
                    x: 167.708_f64,
                    y: 165.333_f64,
                    label_side: LabelSide::Bottom,
                    points: vec![
                        FlowPoint {
                            x: 103.833_f64,
                            y: 165.333_f64,
                            attached_to_uid: Some(9),
                        },
                        FlowPoint {
                            x: 219.583_f64,
                            y: 165.333_f64,
                            attached_to_uid: Some(3),
                        },
                    ],
                }),
                ViewElement::Stock(view_element::Stock {
                    name: "Output".to_string(),
                    uid: 3,
                    x: 242.083_f64,
                    y: 165.333_f64,
                    label_side: LabelSide::Top,
                }),
                ViewElement::Aux(view_element::Aux {
                    name: "delay time".to_string(),
                    uid: 4,
                    x: 118_f64,
                    y: 274.833_f64,
                    label_side: LabelSide::Bottom,
                }),
                ViewElement::Aux(view_element::Aux {
                    name: "input".to_string(),
                    uid: 5,
                    x: 106_f64,
                    y: 117_f64,
                    label_side: LabelSide::Bottom,
                }),
                ViewElement::Link(view_element::Link {
                    uid: 6,
                    from_uid: 5,
                    to_uid: 2,
                    shape: LinkShape::Straight,
                    polarity: None,
                }),
                ViewElement::Link(view_element::Link {
                    uid: 7,
                    from_uid: 4,
                    to_uid: 2,
                    shape: LinkShape::Arc(-62.065800000000024_f64),
                    polarity: None,
                }),
                ViewElement::Aux(view_element::Aux {
                    name: "initial value".to_string(),
                    uid: 8,
                    x: 242.083_f64,
                    y: 54_f64,
                    label_side: LabelSide::Bottom,
                }),
                ViewElement::Cloud(view_element::Cloud {
                    uid: 9,
                    flow_uid: 2,
                    x: 103.833_f64,
                    y: 165.333_f64,
                }),
            ],
            view_box: Rect {
                x: 0_f64,
                y: 0_f64,
                width: 0_f64,
                height: 0_f64,
            },
            zoom: 1_f64,
            use_lettered_polarity: false,
        })],
        loop_metadata: vec![],
        groups: vec![],
    }
}

fn smth3() -> Model {
    Model {
        name: "stdlib⁚smth3".to_string(),
        sim_specs: None,
        variables: vec![
            Variable::Aux(Aux {
                ident: "delay_time".to_string(),
                equation: Equation::Scalar("1".to_string(), None),
                documentation: "".to_string(),
                units: None,
                gf: None,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
            Variable::Flow(Flow {
                ident: "flow_1".to_string(),
                equation: Equation::Scalar("(input - Stock_1)/(delay_time/3)".to_string(), None),
                documentation: "".to_string(),
                units: None,
                gf: None,
                non_negative: false,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
            Variable::Flow(Flow {
                ident: "flow_2".to_string(),
                equation: Equation::Scalar("(Stock_1 - Stock_2)/(delay_time/3)".to_string(), None),
                documentation: "".to_string(),
                units: None,
                gf: None,
                non_negative: false,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
            Variable::Flow(Flow {
                ident: "flow_3".to_string(),
                equation: Equation::Scalar("(Stock_2 - Output)/(delay_time/3)".to_string(), None),
                documentation: "".to_string(),
                units: None,
                gf: None,
                non_negative: false,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
            Variable::Aux(Aux {
                ident: "initial_value".to_string(),
                equation: Equation::Scalar("NAN".to_string(), None),
                documentation: "".to_string(),
                units: None,
                gf: None,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
            Variable::Aux(Aux {
                ident: "input".to_string(),
                equation: Equation::Scalar("0".to_string(), None),
                documentation: "".to_string(),
                units: None,
                gf: None,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
            Variable::Stock(Stock {
                ident: "output".to_string(),
                equation: Equation::Scalar(
                    "if isModuleInput(initial_value) then initial_value else input".to_string(),
                    None,
                ),
                documentation: "".to_string(),
                units: None,
                inflows: vec!["flow_3".to_string()],
                outflows: vec![],
                non_negative: false,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
            Variable::Stock(Stock {
                ident: "stock_1".to_string(),
                equation: Equation::Scalar(
                    "if isModuleInput(initial_value) then initial_value else input".to_string(),
                    None,
                ),
                documentation: "".to_string(),
                units: None,
                inflows: vec!["flow_1".to_string()],
                outflows: vec![],
                non_negative: false,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
            Variable::Stock(Stock {
                ident: "stock_2".to_string(),
                equation: Equation::Scalar(
                    "if isModuleInput(initial_value) then initial_value else input".to_string(),
                    None,
                ),
                documentation: "".to_string(),
                units: None,
                inflows: vec!["flow_2".to_string()],
                outflows: vec![],
                non_negative: false,
                can_be_module_input: false,
                visibility: Visibility::Private,
                ai_state: None,
                uid: None,
            }),
        ],
        views: vec![View::StockFlow(StockFlow {
            elements: vec![
                ViewElement::Link(view_element::Link {
                    uid: 1,
                    from_uid: 7,
                    to_uid: 6,
                    shape: LinkShape::Arc(121.43_f64),
                    polarity: None,
                }),
                ViewElement::Link(view_element::Link {
                    uid: 2,
                    from_uid: 7,
                    to_uid: 9,
                    shape: LinkShape::Arc(86.82_f64),
                    polarity: None,
                }),
                ViewElement::Link(view_element::Link {
                    uid: 3,
                    from_uid: 8,
                    to_uid: 9,
                    shape: LinkShape::Arc(113.96199999999999_f64),
                    polarity: None,
                }),
                ViewElement::Link(view_element::Link {
                    uid: 4,
                    from_uid: 10,
                    to_uid: 11,
                    shape: LinkShape::Arc(145.713_f64),
                    polarity: None,
                }),
                ViewElement::Link(view_element::Link {
                    uid: 5,
                    from_uid: 8,
                    to_uid: 11,
                    shape: LinkShape::Straight,
                    polarity: None,
                }),
                ViewElement::Flow(view_element::Flow {
                    name: "flow 1".to_string(),
                    uid: 6,
                    x: 167.708_f64,
                    y: 165.333_f64,
                    label_side: LabelSide::Bottom,
                    points: vec![
                        FlowPoint {
                            x: 103.833_f64,
                            y: 165.333_f64,
                            attached_to_uid: Some(19),
                        },
                        FlowPoint {
                            x: 219.583_f64,
                            y: 165.333_f64,
                            attached_to_uid: Some(7),
                        },
                    ],
                }),
                ViewElement::Stock(view_element::Stock {
                    name: "Stock 1".to_string(),
                    uid: 7,
                    x: 242.083_f64,
                    y: 165.333_f64,
                    label_side: LabelSide::Top,
                }),
                ViewElement::Stock(view_element::Stock {
                    name: "Stock 2".to_string(),
                    uid: 8,
                    x: 306.833_f64,
                    y: 248.333_f64,
                    label_side: LabelSide::Top,
                }),
                ViewElement::Flow(view_element::Flow {
                    name: "flow 2".to_string(),
                    uid: 9,
                    x: 233.083_f64,
                    y: 248.333_f64,
                    label_side: LabelSide::Bottom,
                    points: vec![
                        FlowPoint {
                            x: 187.833_f64,
                            y: 248.333_f64,
                            attached_to_uid: Some(20),
                        },
                        FlowPoint {
                            x: 284.333_f64,
                            y: 248.333_f64,
                            attached_to_uid: Some(8),
                        },
                    ],
                }),
                ViewElement::Stock(view_element::Stock {
                    name: "Output".to_string(),
                    uid: 10,
                    x: 391.833_f64,
                    y: 317.333_f64,
                    label_side: LabelSide::Top,
                }),
                ViewElement::Flow(view_element::Flow {
                    name: "flow 3".to_string(),
                    uid: 11,
                    x: 306.833_f64,
                    y: 320.333_f64,
                    label_side: LabelSide::Bottom,
                    points: vec![
                        FlowPoint {
                            x: 232.333_f64,
                            y: 320.333_f64,
                            attached_to_uid: Some(21),
                        },
                        FlowPoint {
                            x: 369.333_f64,
                            y: 320.333_f64,
                            attached_to_uid: Some(10),
                        },
                    ],
                }),
                ViewElement::Aux(view_element::Aux {
                    name: "delay time".to_string(),
                    uid: 12,
                    x: 118_f64,
                    y: 274.833_f64,
                    label_side: LabelSide::Bottom,
                }),
                ViewElement::Aux(view_element::Aux {
                    name: "input".to_string(),
                    uid: 13,
                    x: 106_f64,
                    y: 117_f64,
                    label_side: LabelSide::Bottom,
                }),
                ViewElement::Link(view_element::Link {
                    uid: 14,
                    from_uid: 13,
                    to_uid: 6,
                    shape: LinkShape::Straight,
                    polarity: None,
                }),
                ViewElement::Link(view_element::Link {
                    uid: 15,
                    from_uid: 12,
                    to_uid: 6,
                    shape: LinkShape::Arc(-62.065800000000024_f64),
                    polarity: None,
                }),
                ViewElement::Link(view_element::Link {
                    uid: 16,
                    from_uid: 12,
                    to_uid: 9,
                    shape: LinkShape::Arc(-6.249799999999993_f64),
                    polarity: None,
                }),
                ViewElement::Link(view_element::Link {
                    uid: 17,
                    from_uid: 12,
                    to_uid: 11,
                    shape: LinkShape::Arc(15.771000000000015_f64),
                    polarity: None,
                }),
                ViewElement::Aux(view_element::Aux {
                    name: "initial value".to_string(),
                    uid: 18,
                    x: 242.083_f64,
                    y: 54_f64,
                    label_side: LabelSide::Bottom,
                }),
                ViewElement::Cloud(view_element::Cloud {
                    uid: 19,
                    flow_uid: 6,
                    x: 103.833_f64,
                    y: 165.333_f64,
                }),
                ViewElement::Cloud(view_element::Cloud {
                    uid: 20,
                    flow_uid: 9,
                    x: 187.833_f64,
                    y: 248.333_f64,
                }),
                ViewElement::Cloud(view_element::Cloud {
                    uid: 21,
                    flow_uid: 11,
                    x: 232.333_f64,
                    y: 320.333_f64,
                }),
            ],
            view_box: Rect {
                x: 0_f64,
                y: 0_f64,
                width: 0_f64,
                height: 0_f64,
            },
            zoom: 1_f64,
            use_lettered_polarity: false,
        })],
        loop_metadata: vec![],
        groups: vec![],
    }
}

fn trend() -> Model {
    Model {
        name: "stdlib⁚trend".to_string(),
        sim_specs: None,
        variables: vec![
            Variable::Aux(Aux {
            ident: "delay_time".to_string(),
            equation: Equation::Scalar("1".to_string(), None),
            documentation: "".to_string(),
            units: None,
            gf: None,
            can_be_module_input: false,
            visibility: Visibility::Private,
            ai_state: None,
            uid: None,
        }),
            Variable::Flow(Flow {
            ident: "flow".to_string(),
            equation: Equation::Scalar("(input-Stock)/delay_time".to_string(), None),
            documentation: "".to_string(),
            units: None,
            gf: None,
            non_negative: false,
            can_be_module_input: false,
            visibility: Visibility::Private,
            ai_state: None,
            uid: None,
        }),
            Variable::Aux(Aux {
            ident: "initial_value".to_string(),
            equation: Equation::Scalar("NAN".to_string(), None),
            documentation: "".to_string(),
            units: None,
            gf: None,
            can_be_module_input: false,
            visibility: Visibility::Private,
            ai_state: None,
            uid: None,
        }),
            Variable::Aux(Aux {
            ident: "input".to_string(),
            equation: Equation::Scalar("0".to_string(), None),
            documentation: "".to_string(),
            units: None,
            gf: None,
            can_be_module_input: false,
            visibility: Visibility::Private,
            ai_state: None,
            uid: None,
        }),
            Variable::Aux(Aux {
            ident: "output".to_string(),
            equation: Equation::Scalar("SAFEDIV(input-Stock, ABS(Stock)*delay_time)".to_string(), None),
            documentation: "".to_string(),
            units: None,
            gf: None,
            can_be_module_input: false,
            visibility: Visibility::Private,
            ai_state: None,
            uid: None,
        }),
            Variable::Stock(Stock {
            ident: "stock".to_string(),
            equation: Equation::Scalar("if isModuleInput(initial_value) then input / (1 + delay_time * initial_value) else input".to_string(), None),
            documentation: "".to_string(),
            units: None,
            inflows: vec!["flow".to_string()],
            outflows: vec![],
            non_negative: false,
            can_be_module_input: false,
            visibility: Visibility::Private,
            ai_state: None,
            uid: None,
        })
        ],
        views: vec![View::StockFlow(StockFlow {
            elements: vec![ViewElement::Link(view_element::Link {
                uid: 1,
                from_uid: 3,
                to_uid: 4,
                shape: LinkShape::Arc(135_f64),
                polarity: None,
            }),
                ViewElement::Link(view_element::Link {
                uid: 2,
                from_uid: 3,
                to_uid: 5,
                shape: LinkShape::Straight,
                polarity: None,
            }),
                ViewElement::Stock(view_element::Stock {
                name: "Stock".to_string(),
                uid: 3,
                x: 268.33299999999997_f64,
                y: 244.333_f64,
                label_side: LabelSide::Top,
            }),
                ViewElement::Flow(view_element::Flow {
                    name: "flow".to_string(),
                    uid: 4,
                    x: 196.083_f64,
                    y: 244.333_f64,
                    label_side: LabelSide::Bottom,
                    points: vec![FlowPoint { x: 134.333_f64, y: 244.333_f64, attached_to_uid: Some(13) }, FlowPoint { x: 245.83299999999997_f64, y: 244.333_f64, attached_to_uid: Some(3) }],
                }),
                ViewElement::Aux(view_element::Aux {
                name: "output".to_string(),
                uid: 5,
                x: 347.333_f64,
                y: 181.333_f64,
                label_side: LabelSide::Bottom,
            }),
                ViewElement::Aux(view_element::Aux {
                name: "delay time".to_string(),
                uid: 6,
                x: 255_f64,
                y: 176.333_f64,
                label_side: LabelSide::Bottom,
            }),
                ViewElement::Link(view_element::Link {
                uid: 7,
                from_uid: 6,
                to_uid: 4,
                shape: LinkShape::Straight,
                polarity: None,
            }),
                ViewElement::Link(view_element::Link {
                uid: 8,
                from_uid: 6,
                to_uid: 5,
                shape: LinkShape::Straight,
                polarity: None,
            }),
                ViewElement::Aux(view_element::Aux {
                name: "input".to_string(),
                uid: 9,
                x: 197_f64,
                y: 118_f64,
                label_side: LabelSide::Bottom,
            }),
                ViewElement::Link(view_element::Link {
                uid: 10,
                from_uid: 9,
                to_uid: 4,
                shape: LinkShape::Straight,
                polarity: None,
            }),
                ViewElement::Link(view_element::Link {
                uid: 11,
                from_uid: 9,
                to_uid: 5,
                shape: LinkShape::Arc(15.254999999999995_f64),
                polarity: None,
            }),
                ViewElement::Aux(view_element::Aux {
                name: "initial value".to_string(),
                uid: 12,
                x: 268.333_f64,
                y: 92_f64,
                label_side: LabelSide::Bottom,
            }),
                ViewElement::Cloud(view_element::Cloud {
                uid: 13,
                flow_uid: 4,
                x: 134.333_f64,
                y: 244.333_f64,
            })],
            view_box: Rect { x: 0_f64, y: 0_f64, width: 0_f64, height: 0_f64 },
            zoom: 1_f64,
            use_lettered_polarity: false,
        })],
        loop_metadata: vec![],
        groups: vec![],
    }
}
