// Copyright 2019 The Model Authors. All rights reserved.
// Use of this source code is governed by the Apache License,
// Version 2.0, that can be found in the LICENSE file.

// DO NOT EDIT: auto-generated by ./support/build-stdlib.js

import { Map } from 'immutable';

/* tslint:disable: max-line-length */
export const xmileModels = Map<string, any>([
  [
    'delay1',
    {
      '@class': 'File',
      data: {
        version: '1.0',
        namespace: 'http://docs.oasis-open.org/xmile/ns/XMILE/v1.0',
        header: {
          '@class': 'Header',
          data: {
            vendor: 'isee systems, inc.',
            product: {
              '@class': 'Product',
              data: { name: 'Stella Architect', lang: 'en', version: '1.4.1' },
            },
            name: 'delay1',
            uuid: '65758527-4979-4e04-b61c-25c628175fd0',
          },
        },
        simSpec: {
          '@class': 'SimSpec',
          data: { start: 1, stop: 13, dt: 0.25, dtReciprocal: 4, saveStep: 0.25, method: 'euler' },
        },
        models: [
          {
            '@class': 'Model',
            data: {
              name: 'stdlib·delay1',
              variables: [
                {
                  '@class': 'Variable',
                  data: {
                    type: 'stock',
                    name: 'Stock',
                    eqn: '(IF initial_value = NAN THEN input ELSE initial_value) * delay_time',
                    inflows: ['input'],
                    outflows: ['output'],
                  },
                },
                { '@class': 'Variable', data: { type: 'flow', name: 'input', eqn: '0' } },
                {
                  '@class': 'Variable',
                  data: { type: 'flow', name: 'output', eqn: 'Stock/delay_time' },
                },
                { '@class': 'Variable', data: { type: 'aux', name: 'delay time', eqn: '1' } },
                { '@class': 'Variable', data: { type: 'aux', name: 'initial value', eqn: 'NAN' } },
              ],
              views: [
                {
                  '@class': 'View',
                  data: {
                    type: 'stock_flow',
                    zoom: 100,
                    scrollX: 0,
                    scrollY: 0,
                    pageWidth: 756,
                    pageHeight: 584,
                    elements: [
                      { '@class': 'ViewElement', data: { type: 'style' } },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'stock', name: 'Stock', x: 232, y: 168 },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'flow',
                          name: 'input',
                          x: 169.75,
                          y: 170,
                          pts: [
                            { '@class': 'Point', data: { x: 130, y: 170 } },
                            { '@class': 'Point', data: { x: 209.5, y: 170 } },
                          ],
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'flow',
                          name: 'output',
                          x: 291.75,
                          y: 168,
                          pts: [
                            { '@class': 'Point', data: { x: 254.5, y: 168 } },
                            { '@class': 'Point', data: { x: 353, y: 168 } },
                          ],
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'aux', name: 'delay time', x: 337.5, y: 233 },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 1,
                          from: 'delay_time',
                          to: 'output',
                          angle: 125.14,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 2,
                          from: 'stock',
                          to: 'output',
                          angle: 310.101,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'aux', name: 'initial value', x: 221, y: 41 },
                      },
                    ],
                  },
                },
              ],
            },
          },
        ],
      },
    },
  ],
  [
    'delay3',
    {
      '@class': 'File',
      data: {
        version: '1.0',
        namespace: 'http://docs.oasis-open.org/xmile/ns/XMILE/v1.0',
        header: {
          '@class': 'Header',
          data: {
            vendor: 'isee systems, inc.',
            product: {
              '@class': 'Product',
              data: { name: 'Stella Professional', lang: 'en', version: '1.8.2' },
            },
            name: 'delay3',
            uuid: '65758527-4979-4e04-b61c-25c628175fd0',
          },
        },
        simSpec: {
          '@class': 'SimSpec',
          data: { start: 1, stop: 13, dt: 0.25, dtReciprocal: 4, saveStep: 0.25, method: 'euler' },
        },
        models: [
          {
            '@class': 'Model',
            data: {
              name: 'stdlib·delay3',
              variables: [
                {
                  '@class': 'Variable',
                  data: {
                    type: 'stock',
                    name: 'Stock',
                    eqn: '(IF initial_value = NAN THEN input ELSE initial_value) * (delay_time/3)',
                    inflows: ['input'],
                    outflows: ['flow_1'],
                  },
                },
                { '@class': 'Variable', data: { type: 'flow', name: 'input', eqn: '0' } },
                {
                  '@class': 'Variable',
                  data: { type: 'flow', name: 'output', eqn: 'Stock_3/(delay_time/3)' },
                },
                { '@class': 'Variable', data: { type: 'aux', name: 'delay time', eqn: '1' } },
                { '@class': 'Variable', data: { type: 'aux', name: 'initial value', eqn: 'NAN' } },
                {
                  '@class': 'Variable',
                  data: { type: 'flow', name: 'Flow 1', eqn: 'Stock/(delay_time/3)' },
                },
                {
                  '@class': 'Variable',
                  data: {
                    type: 'stock',
                    name: 'Stock 2',
                    eqn: '(IF initial_value = NAN THEN input ELSE initial_value) * (delay_time/3)',
                    inflows: ['flow_1'],
                    outflows: ['flow_2'],
                  },
                },
                {
                  '@class': 'Variable',
                  data: {
                    type: 'stock',
                    name: 'Stock 3',
                    eqn: '(IF initial_value = NAN THEN input ELSE initial_value) * (delay_time/3)',
                    inflows: ['flow_2'],
                    outflows: ['output'],
                  },
                },
                {
                  '@class': 'Variable',
                  data: { type: 'flow', name: 'Flow 2', eqn: 'Stock_2/(delay_time/3)' },
                },
              ],
              views: [
                {
                  '@class': 'View',
                  data: {
                    type: 'stock_flow',
                    zoom: 100,
                    scrollX: 0,
                    scrollY: 0,
                    pageWidth: 305,
                    pageHeight: 213,
                    elements: [
                      { '@class': 'ViewElement', data: { type: 'style' } },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'stock', name: 'Stock', x: 232, y: 168 },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'flow',
                          name: 'input',
                          x: 169.75,
                          y: 170,
                          pts: [
                            { '@class': 'Point', data: { x: 130, y: 170 } },
                            { '@class': 'Point', data: { x: 209.5, y: 170 } },
                          ],
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'flow',
                          name: 'output',
                          x: 558.25,
                          y: 171,
                          pts: [
                            { '@class': 'Point', data: { x: 520.5, y: 171 } },
                            { '@class': 'Point', data: { x: 620, y: 171 } },
                          ],
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'aux', name: 'delay time', x: 426.5, y: 300 },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 1,
                          from: 'delay_time',
                          to: 'output',
                          angle: 44.3958,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'aux', name: 'initial value', x: 221, y: 41 },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'flow',
                          name: 'Flow 1',
                          x: 294,
                          y: 169,
                          pts: [
                            { '@class': 'Point', data: { x: 254.5, y: 169 } },
                            { '@class': 'Point', data: { x: 345.5, y: 169 } },
                          ],
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'stock', name: 'Stock 2', x: 368, y: 170 },
                      },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'stock', name: 'Stock 3', x: 498, y: 171 },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'flow',
                          name: 'Flow 2',
                          x: 427,
                          y: 170,
                          pts: [
                            { '@class': 'Point', data: { x: 390.5, y: 170 } },
                            { '@class': 'Point', data: { x: 475.5, y: 170 } },
                          ],
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 2,
                          from: 'stock_3',
                          to: 'output',
                          angle: 64.9831,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 3,
                          from: 'delay_time',
                          to: 'flow_2',
                          angle: 89.7796,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 4,
                          from: 'delay_time',
                          to: 'flow_1',
                          angle: 135.326,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 5,
                          from: 'stock',
                          to: 'flow_1',
                          angle: 69.7751,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 6,
                          from: 'stock_2',
                          to: 'flow_2',
                          angle: 65.7723,
                        },
                      },
                    ],
                  },
                },
              ],
            },
          },
        ],
      },
    },
  ],
  [
    'smth1',
    {
      '@class': 'File',
      data: {
        version: '1.0',
        namespace: 'http://docs.oasis-open.org/xmile/ns/XMILE/v1.0',
        header: {
          '@class': 'Header',
          data: {
            vendor: 'isee systems, inc.',
            product: {
              '@class': 'Product',
              data: { name: 'Stella Architect', lang: 'en', version: '1.4.1' },
            },
            name: 'smth1',
            uuid: '65758527-4979-4e04-b61c-25c628175fd0',
          },
        },
        simSpec: {
          '@class': 'SimSpec',
          data: { start: 1, stop: 13, dt: 0.25, dtReciprocal: 4, saveStep: 0.25, method: 'euler' },
        },
        models: [
          {
            '@class': 'Model',
            data: {
              name: 'stdlib·smth1',
              variables: [
                {
                  '@class': 'Variable',
                  data: { type: 'flow', name: 'flow', eqn: '(input - Output)/(delay_time/3)' },
                },
                {
                  '@class': 'Variable',
                  data: {
                    type: 'stock',
                    name: 'Output',
                    eqn: 'IF (initial_value = NAN) THEN input ELSE initial_value',
                    inflows: ['flow'],
                  },
                },
                { '@class': 'Variable', data: { type: 'aux', name: 'delay time', eqn: '1' } },
                { '@class': 'Variable', data: { type: 'aux', name: 'input', eqn: '0' } },
                { '@class': 'Variable', data: { type: 'aux', name: 'initial value', eqn: 'NAN' } },
              ],
              views: [
                {
                  '@class': 'View',
                  data: {
                    type: 'stock_flow',
                    zoom: 100,
                    scrollX: 0,
                    scrollY: 0,
                    pageWidth: 764,
                    pageHeight: 576,
                    elements: [
                      { '@class': 'ViewElement', data: { type: 'style' } },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 1,
                          from: 'output',
                          to: 'flow',
                          angle: 238.57,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'flow',
                          name: 'flow',
                          x: 167.708,
                          y: 165.333,
                          pts: [
                            { '@class': 'Point', data: { x: 103.833, y: 165.333 } },
                            { '@class': 'Point', data: { x: 219.583, y: 165.333 } },
                          ],
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'stock', name: 'Output', x: 242.083, y: 165.333 },
                      },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'aux', name: 'delay time', x: 118, y: 274.833 },
                      },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'aux', name: 'input', x: 106, y: 117 },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 2,
                          from: 'input',
                          to: 'flow',
                          angle: 321.93,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 3,
                          from: 'delay_time',
                          to: 'flow',
                          angle: 62.0658,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'aux', name: 'initial value', x: 242.083, y: 54 },
                      },
                    ],
                  },
                },
              ],
            },
          },
        ],
      },
    },
  ],
  [
    'smth3',
    {
      '@class': 'File',
      data: {
        version: '1.0',
        namespace: 'http://docs.oasis-open.org/xmile/ns/XMILE/v1.0',
        header: {
          '@class': 'Header',
          data: {
            vendor: 'isee systems, inc.',
            product: {
              '@class': 'Product',
              data: { name: 'Stella Architect', lang: 'en', version: '1.4.1' },
            },
            name: 'smth3',
            uuid: '65758527-4979-4e04-b61c-25c628175fd0',
          },
        },
        simSpec: {
          '@class': 'SimSpec',
          data: { start: 1, stop: 13, dt: 0.25, dtReciprocal: 4, saveStep: 0.25, method: 'euler' },
        },
        models: [
          {
            '@class': 'Model',
            data: {
              name: 'stdlib·smth3',
              variables: [
                {
                  '@class': 'Variable',
                  data: { type: 'flow', name: 'flow 1', eqn: '(input - Stock_1)/(delay_time/3)' },
                },
                {
                  '@class': 'Variable',
                  data: {
                    type: 'stock',
                    name: 'Stock 1',
                    eqn: 'IF (initial_value = NAN) THEN input ELSE initial_value',
                    inflows: ['flow_1'],
                  },
                },
                {
                  '@class': 'Variable',
                  data: {
                    type: 'stock',
                    name: 'Stock 2',
                    eqn: 'IF (initial_value = NAN) THEN input ELSE initial_value',
                    inflows: ['flow_2'],
                  },
                },
                {
                  '@class': 'Variable',
                  data: { type: 'flow', name: 'flow 2', eqn: '(Stock_1 - Stock_2)/(delay_time/3)' },
                },
                {
                  '@class': 'Variable',
                  data: {
                    type: 'stock',
                    name: 'Output',
                    eqn: 'IF (initial_value = NAN) THEN input ELSE initial_value',
                    inflows: ['flow_3'],
                  },
                },
                {
                  '@class': 'Variable',
                  data: { type: 'flow', name: 'flow 3', eqn: '(Stock_2 - Output)/(delay_time/3)' },
                },
                { '@class': 'Variable', data: { type: 'aux', name: 'delay time', eqn: '1' } },
                { '@class': 'Variable', data: { type: 'aux', name: 'input', eqn: '0' } },
                { '@class': 'Variable', data: { type: 'aux', name: 'initial value', eqn: 'NAN' } },
              ],
              views: [
                {
                  '@class': 'View',
                  data: {
                    type: 'stock_flow',
                    zoom: 100,
                    scrollX: 0,
                    scrollY: 0,
                    pageWidth: 764,
                    pageHeight: 576,
                    elements: [
                      { '@class': 'ViewElement', data: { type: 'style' } },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 1,
                          from: 'stock_1',
                          to: 'flow_1',
                          angle: 238.57,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 2,
                          from: 'stock_1',
                          to: 'flow_2',
                          angle: 273.18,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 3,
                          from: 'stock_2',
                          to: 'flow_2',
                          angle: 246.038,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 4,
                          from: 'output',
                          to: 'flow_3',
                          angle: 214.287,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 5,
                          from: 'stock_2',
                          to: 'flow_3',
                          angle: 270,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'flow',
                          name: 'flow 1',
                          x: 167.708,
                          y: 165.333,
                          pts: [
                            { '@class': 'Point', data: { x: 103.833, y: 165.333 } },
                            { '@class': 'Point', data: { x: 219.583, y: 165.333 } },
                          ],
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'stock', name: 'Stock 1', x: 242.083, y: 165.333 },
                      },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'stock', name: 'Stock 2', x: 306.833, y: 248.333 },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'flow',
                          name: 'flow 2',
                          x: 242.083,
                          y: 248.333,
                          pts: [
                            { '@class': 'Point', data: { x: 187.833, y: 248.333 } },
                            { '@class': 'Point', data: { x: 284.333, y: 248.333 } },
                          ],
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'stock', name: 'Output', x: 391.833, y: 317.333 },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'flow',
                          name: 'flow 3',
                          x: 306.833,
                          y: 320.333,
                          pts: [
                            { '@class': 'Point', data: { x: 232.333, y: 320.333 } },
                            { '@class': 'Point', data: { x: 369.333, y: 320.333 } },
                          ],
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'aux', name: 'delay time', x: 118, y: 274.833 },
                      },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'aux', name: 'input', x: 106, y: 117 },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 6,
                          from: 'input',
                          to: 'flow_1',
                          angle: 321.93,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 7,
                          from: 'delay_time',
                          to: 'flow_1',
                          angle: 62.0658,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 8,
                          from: 'delay_time',
                          to: 'flow_2',
                          angle: 6.2498,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 9,
                          from: 'delay_time',
                          to: 'flow_3',
                          angle: 344.229,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'aux', name: 'initial value', x: 242.083, y: 54 },
                      },
                    ],
                  },
                },
              ],
            },
          },
        ],
      },
    },
  ],
  [
    'trend',
    {
      '@class': 'File',
      data: {
        version: '1.0',
        namespace: 'http://docs.oasis-open.org/xmile/ns/XMILE/v1.0',
        header: {
          '@class': 'Header',
          data: {
            vendor: 'isee systems, inc.',
            product: {
              '@class': 'Product',
              data: { name: 'Stella Architect', lang: 'en', version: '1.4.1' },
            },
            name: 'trend',
            uuid: '5d773e8c-1d7c-4d1d-955e-fadbb441a915',
          },
        },
        simSpec: {
          '@class': 'SimSpec',
          data: { start: 1, stop: 13, dt: 0.25, dtReciprocal: 4, saveStep: 0.25, method: 'euler' },
        },
        models: [
          {
            '@class': 'Model',
            data: {
              name: 'stdlib·trend',
              variables: [
                {
                  '@class': 'Variable',
                  data: {
                    type: 'stock',
                    name: 'Stock',
                    eqn: 'IF (initial_value = NAN) THEN input ELSE initial_value',
                    inflows: ['flow'],
                  },
                },
                {
                  '@class': 'Variable',
                  data: { type: 'flow', name: 'flow', eqn: '(input-Stock)/delay_time' },
                },
                {
                  '@class': 'Variable',
                  data: { type: 'aux', name: 'output', eqn: '(input-Stock)/(Stock*delay_time)' },
                },
                { '@class': 'Variable', data: { type: 'aux', name: 'delay time', eqn: '1' } },
                { '@class': 'Variable', data: { type: 'aux', name: 'input', eqn: '0' } },
                { '@class': 'Variable', data: { type: 'aux', name: 'initial value', eqn: 'NAN' } },
              ],
              views: [
                {
                  '@class': 'View',
                  data: {
                    type: 'stock_flow',
                    zoom: 100,
                    scrollX: 0,
                    scrollY: 0,
                    pageWidth: 764,
                    pageHeight: 576,
                    elements: [
                      { '@class': 'ViewElement', data: { type: 'style' } },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'connector', uid: 1, from: 'stock', to: 'flow', angle: 225 },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 2,
                          from: 'stock',
                          to: 'output',
                          angle: 38.5713,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'stock',
                          name: 'Stock',
                          x: 245.833,
                          y: 226.833,
                          width: 45,
                          height: 35,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'flow',
                          name: 'flow',
                          x: 196.083,
                          y: 244.333,
                          pts: [
                            { '@class': 'Point', data: { x: 134.333, y: 244.333 } },
                            { '@class': 'Point', data: { x: 245.833, y: 244.333 } },
                          ],
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'aux', name: 'output', x: 347.333, y: 181.333 },
                      },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'aux', name: 'delay time', x: 255, y: 176.333 },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 3,
                          from: 'delay_time',
                          to: 'flow',
                          angle: 229.093,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 4,
                          from: 'delay_time',
                          to: 'output',
                          angle: 356.9,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'aux', name: 'input', x: 197, y: 118 },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 5,
                          from: 'input',
                          to: 'flow',
                          angle: 269.584,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: {
                          type: 'connector',
                          uid: 6,
                          from: 'input',
                          to: 'output',
                          angle: 344.745,
                        },
                      },
                      {
                        '@class': 'ViewElement',
                        data: { type: 'aux', name: 'initial value', x: 268.333, y: 92 },
                      },
                    ],
                  },
                },
              ],
            },
          },
        ],
      },
    },
  ],
]);
