#!/bin/bash
# Copyright 2021 The Simlin Authors. All rights reserved.
# Use of this source code is governed by the Apache License,
# Version 2.0, that can be found in the LICENSE file.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

PROTO_FILE="$ROOT_DIR/src/simlin-engine/src/project_io.proto"
OUTPUT_FILE="$ROOT_DIR/src/simlin-engine/src/project_io.gen.rs"

# Read the toolchain channel from rust-toolchain.toml so the temp crate uses the
# same Rust version as the repo (e.g., for edition 2024 support)
TOOLCHAIN=$(grep '^channel' "$ROOT_DIR/rust-toolchain.toml" | cut -d '"' -f 2)
export RUSTUP_TOOLCHAIN="$TOOLCHAIN"

# Compute SHA256 hash of the proto file
PROTO_HASH=$(sha256sum "$PROTO_FILE" | cut -d ' ' -f 1)

# Create a temporary directory for the prost-build project
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

# Create a minimal Cargo project that uses prost-build
mkdir -p "$TEMP_DIR/src"
cat > "$TEMP_DIR/Cargo.toml" << 'EOF'
[package]
name = "proto-gen"
version = "0.1.0"
edition = "2024"

[build-dependencies]
prost-build = "0.14"
EOF

cat > "$TEMP_DIR/src/lib.rs" << 'EOF'
// placeholder
EOF

cat > "$TEMP_DIR/build.rs" << EOF
fn main() {
    let mut config = prost_build::Config::new();
    config.protoc_arg("--experimental_allow_proto3_optional");
    config.out_dir("$TEMP_DIR");
    config.compile_protos(&["$PROTO_FILE"], &["$(dirname "$PROTO_FILE")"]).unwrap();
}
EOF

# Run the build to generate the protobuf code
cd "$TEMP_DIR"
cargo build 2>/dev/null

# Prepend the header to the generated file
{
    echo "// @generated by prost-build from project_io.proto"
    echo "// DO NOT EDIT - regenerate with: pnpm build:gen-protobufs"
    echo "//"
    echo "// Proto file SHA256: $PROTO_HASH"
    echo "// prost-build version: 0.14"
    echo ""
    cat "$TEMP_DIR/project_io.rs"
} > "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE"
