#!/bin/bash
# Copyright 2021 The Simlin Authors. All rights reserved.
# Use of this source code is governed by the Apache License,
# Version 2.0, that can be found in the LICENSE file.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

PROTO_FILE="$ROOT_DIR/src/simlin-engine/src/project_io.proto"
OUTPUT_FILE="$ROOT_DIR/src/simlin-engine/src/project_io.gen.rs"

# Read the toolchain channel from rust-toolchain.toml so the temp crate uses the
# same Rust version as the repo (e.g., for edition 2024 support)
TOOLCHAIN=$(grep '^channel' "$ROOT_DIR/rust-toolchain.toml" | cut -d '"' -f 2)
export RUSTUP_TOOLCHAIN="$TOOLCHAIN"

# The generator must be exactly the version of the `buffa` runtime the
# workspace links: generated code calls runtime internals (`__private` helpers,
# trait methods) that are not covered by semver, so a newer buffa-build than
# the locked runtime can emit code the runtime cannot compile. Cargo.lock is
# the source of truth for that runtime version.
BUFFA_VERSION=$(awk '/^name = "buffa"$/ { getline; gsub(/"/, "", $3); print $3; exit }' "$ROOT_DIR/Cargo.lock")
if [ -z "$BUFFA_VERSION" ]; then
    echo "error: no buffa package in $ROOT_DIR/Cargo.lock" >&2
    exit 1
fi

# Compute SHA256 hash of the proto file
PROTO_HASH=$(sha256sum "$PROTO_FILE" | cut -d ' ' -f 1)

# Create a temporary directory for the buffa-build project
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

# Create a minimal Cargo project that uses buffa-build
mkdir -p "$TEMP_DIR/src" "$TEMP_DIR/out"
cat > "$TEMP_DIR/Cargo.toml" << EOF
[package]
name = "proto-gen"
version = "0.1.0"
edition = "2024"

[build-dependencies]
buffa-build = "=$BUFFA_VERSION"
EOF

cat > "$TEMP_DIR/src/lib.rs" << 'EOF'
// placeholder
EOF

# Codegen options, each chosen for how the engine uses these types (as a
# serialization format converted to and from `datamodel` in serde.rs):
# - no views: nothing decodes zero-copy, and views roughly double the output.
# - one file per package: a single checked-in file carrying the hash header
#   below, with the oneof enums re-exported where the message modules name them
#   (`variable::V`, `view_element::Element`, ...).
# - unknown fields dropped: the engine never re-emits a message it decoded, so
#   preserving them buys nothing, and without the hidden bookkeeping field the
#   messages stay constructible with plain struct literals.
# - no `with_*` setters: unused.
# - idiomatic field names: the proto has camelCase fields (`viewBox`), which
#   read as snake_case Rust fields (`view_box`) without renaming anything on
#   the wire.
# - oneof variants stored inline: no oneof here is recursive, so the default
#   per-variant `Box` would only add an allocation per variant.
cat > "$TEMP_DIR/build.rs" << EOF
fn main() {
    buffa_build::Config::new()
        .files(&["$PROTO_FILE"])
        .includes(&["$(dirname "$PROTO_FILE")"])
        .out_dir("$TEMP_DIR/out")
        .generate_views(false)
        .file_per_package(true)
        .preserve_unknown_fields(false)
        .generate_with_setters(false)
        .idiomatic_field_names(true)
        .unbox_oneof()
        .compile()
        .unwrap();
}
EOF

# Run the build to generate the protobuf code. buffa-build shells out to
# `protoc`; surface its stderr on failure (a missing protoc is the common case)
# instead of exiting silently with nothing written.
cd "$TEMP_DIR"
if ! cargo build 2>"$TEMP_DIR/build.log"; then
    cat "$TEMP_DIR/build.log" >&2
    echo "error: buffa-build failed; see output above" >&2
    exit 1
fi

# Prepend the header to the generated file
{
    echo "// @generated by buffa-build from project_io.proto"
    echo "// DO NOT EDIT - regenerate with: pnpm build:gen-protobufs"
    echo "//"
    echo "// Proto file SHA256: $PROTO_HASH"
    echo "// buffa-build version: $BUFFA_VERSION"
    echo ""
    cat "$TEMP_DIR/out/project_io.rs"
} > "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE"
