// Copyright 2026 The Simlin Authors. All rights reserved.
// Use of this source code is governed by the Apache License,
// Version 2.0, that can be found in the LICENSE file.

//! Integration tests for systems format simulation.
//!
//! Each test parses a `.txt` systems file, translates it to a datamodel
//! project, runs it via the VM, and compares results against expected CSV
//! output generated by the Python `systems` package.

mod test_helpers;

use simlin_engine::Vm;
use simlin_engine::db::{SimlinDb, compile_project_incremental, sync_from_datamodel_incremental};
use simlin_engine::load_csv;

use test_helpers::ensure_results;

/// Parse a systems format file, simulate it via the VM, and compare
/// results against expected CSV output.
fn simulate_systems_file(txt_path: &str, csv_path: &str, rounds: u64) {
    eprintln!("systems model: {txt_path}");

    let contents = std::fs::read_to_string(txt_path)
        .unwrap_or_else(|e| panic!("failed to read {txt_path}: {e}"));
    let systems_model = simlin_engine::systems::parse(&contents)
        .unwrap_or_else(|e| panic!("failed to parse {txt_path}: {e}"));
    let datamodel_project = simlin_engine::systems::translate::translate(&systems_model, rounds)
        .unwrap_or_else(|e| panic!("failed to translate {txt_path}: {e}"));

    let expected =
        load_csv(csv_path, b',').unwrap_or_else(|e| panic!("failed to load {csv_path}: {e}"));

    let mut db = SimlinDb::default();
    let sync = sync_from_datamodel_incremental(&mut db, &datamodel_project, None);
    let compiled = compile_project_incremental(&db, sync.project, "main")
        .unwrap_or_else(|e| panic!("VM compilation failed for {txt_path}: {e:?}"));
    let mut vm =
        Vm::new(compiled).unwrap_or_else(|e| panic!("VM creation failed for {txt_path}: {e}"));
    vm.run_to_end()
        .unwrap_or_else(|e| panic!("VM execution failed for {txt_path}: {e}"));
    let results = vm.into_results();
    ensure_results(&expected, &results);
}

#[test]
fn simulates_hiring() {
    simulate_systems_file(
        "../../test/systems-format/hiring.txt",
        "../../test/systems-format/hiring_output.csv",
        5,
    );
}

#[test]
fn simulates_links() {
    simulate_systems_file(
        "../../test/systems-format/links.txt",
        "../../test/systems-format/links_output.csv",
        5,
    );
}

#[test]
fn simulates_maximums() {
    simulate_systems_file(
        "../../test/systems-format/maximums.txt",
        "../../test/systems-format/maximums_output.csv",
        5,
    );
}

#[test]
fn simulates_projects() {
    simulate_systems_file(
        "../../test/systems-format/projects.txt",
        "../../test/systems-format/projects_output.csv",
        5,
    );
}

#[test]
fn simulates_cross_stock() {
    simulate_systems_file(
        "../../test/systems-format/cross_stock.txt",
        "../../test/systems-format/cross_stock_output.csv",
        5,
    );
}

#[test]
fn simulates_extended_syntax() {
    simulate_systems_file(
        "../../test/systems-format/extended_syntax.txt",
        "../../test/systems-format/extended_syntax_output.csv",
        5,
    );
}
