name: Visual Regression Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  visual-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
      
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Install wasm-bindgen-cli
        run: |
          cargo install wasm-bindgen-cli --version 0.2.92 || true
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Build WASM modules
        run: |
          cd src/engine && ./build.sh && cd ../..
          cd src/importer && ./build.sh && cd ../..
          cd src/xmutil && cargo build --release --target wasm32-unknown-unknown && cd ../..
      
      - name: Build application
        run: yarn build
      
      - name: Install Playwright browsers
        run: npx playwright install chromium
      
      - name: Run visual regression tests
        run: yarn test:visual
        env:
          CI: true
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      
      - name: Upload visual diff artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: visual-diffs
          path: test-results/
          retention-days: 7
      
      # Comment on PR with results (only on PR)
      - name: Comment PR with results
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v7
        with:
          script: |
            const artifactUrl = `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `❌ Visual regression tests failed. [View artifacts](${artifactUrl}) to see the differences.`
            });

  # Separate job to update baselines when needed
  update-baselines:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
      
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      
      - name: Install wasm-bindgen-cli
        run: |
          cargo install wasm-bindgen-cli --version 0.2.92 || true
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Build WASM modules
        run: |
          cd src/engine && ./build.sh && cd ../..
          cd src/importer && ./build.sh && cd ../..
          cd src/xmutil && cargo build --release --target wasm32-unknown-unknown && cd ../..
      
      - name: Build application
        run: yarn build
      
      - name: Install Playwright browsers
        run: npx playwright install chromium
      
      - name: Update visual baselines
        run: yarn test:visual:update
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'chore: update visual regression baselines'
          title: 'Update Visual Regression Baselines'
          body: |
            This PR updates the visual regression test baselines.
            
            Please review the changes carefully to ensure they are intentional.
          branch: update-visual-baselines
          delete-branch: true