// Copyright 2026 The Simlin Authors. All rights reserved.
// Use of this source code is governed by the Apache License,
// Version 2.0, that can be found in the LICENSE file.

//! Build script for `simlin-serve`.
//!
//! When `SIMLIN_SERVE_BUILD_WEB=1` is set, the script shells out to `pnpm`
//! to install dependencies and build the SPA into `web/dist/`. The cross-build
//! flow (Task 20) sets the variable inside the Docker container so the
//! resulting binary always embeds a fresh frontend bundle. Local developers
//! can leave it unset and run `pnpm build` in `web/` manually for a faster
//! `cargo build` loop.
//!
//! `cargo:rerun-if-changed` directives are emitted unconditionally so cargo
//! invalidates this script (and re-runs it) whenever a frontend source file
//! changes — the env-var gate decides whether the heavy work happens, not
//! whether to reconsider the inputs.

use std::path::PathBuf;
use std::process::Command;

/// Spawnable name for the `pnpm` launcher. On Windows the launcher is
/// `pnpm.cmd` (a PowerShell-friendly batch file shipped by the
/// `pnpm/action-setup` GitHub Action and by `corepack`); `Command::new`
/// uses `CreateProcess` directly and does NOT consult `PATHEXT`, so a
/// bare `"pnpm"` lookup fails with `ERROR_FILE_NOT_FOUND` on Windows
/// runners even though `pnpm` is on `PATH` in the surrounding shell.
/// Linux and macOS install pnpm as a plain executable so the bare name
/// resolves there.
fn pnpm_program() -> &'static str {
    if cfg!(target_os = "windows") {
        "pnpm.cmd"
    } else {
        "pnpm"
    }
}

fn main() -> anyhow::Result<()> {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR")?);
    let web_dir = manifest_dir.join("web");
    let web_src = web_dir.join("src");
    let web_index = web_dir.join("index.html");
    let web_package = web_dir.join("package.json");
    let web_dist = web_dir.join("dist");

    println!("cargo:rerun-if-changed={}", web_src.display());
    println!("cargo:rerun-if-changed={}", web_index.display());
    println!("cargo:rerun-if-changed={}", web_package.display());
    println!("cargo:rerun-if-env-changed=SIMLIN_SERVE_BUILD_WEB");

    // `rust-embed` errors if its `#[folder = ...]` target doesn't exist on
    // disk at compile time, even when the directory is supposed to be
    // generated by an earlier build step. Pre-creating an empty `web/dist/`
    // keeps `cargo build` working when developers haven't yet run the
    // frontend build; the embedded asset set is just empty until they do.
    if !web_dist.exists() {
        std::fs::create_dir_all(&web_dist)?;
    }

    if std::env::var("SIMLIN_SERVE_BUILD_WEB").as_deref() != Ok("1") {
        return Ok(());
    }

    let pnpm = pnpm_program();
    let install = Command::new(pnpm)
        .arg("install")
        .arg("--frozen-lockfile")
        .current_dir(&web_dir)
        .status()?;
    if !install.success() {
        anyhow::bail!(
            "`{} install --frozen-lockfile` failed in {}",
            pnpm,
            web_dir.display()
        );
    }

    let build = Command::new(pnpm)
        .arg("build")
        .current_dir(&web_dir)
        .status()?;
    if !build.success() {
        anyhow::bail!("`{} build` failed in {}", pnpm, web_dir.display());
    }

    Ok(())
}
